# Generated by Django 6.1 on 2026-09-14 07:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('projectId', models.UUIDField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(default='todo', max_length=20)),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('assigneeName', models.CharField(blank=True, default='', max_length=160)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('estimate', models.CharField(blank=True, default='', max_length=40)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Task',
                'ordering': ['-createdAt'],
            },
        ),
    ]
