# Generated by Django 6.1 on 2026-09-14 07:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("status", models.CharField(default="active", max_length=20)),
                ("health", models.IntegerField(default=100)),
                ("progress", models.IntegerField(default=0)),
                ("ownerName", models.CharField(blank=True, default="", max_length=160)),
                ("dueDate", models.DateField(blank=True, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(blank=True, null=True)),
                ("deletedAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Project",
                "ordering": ["-createdAt"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenantId", "code"), name="UQG_Project_tenant_code"
                    )
                ],
            },
        ),
    ]
