/** Versioned application-interface paths. Feature code never assembles API versions or auth headers. */
export const apiEndpoints = {
  auth: { login: "auth/login", refresh: "auth/refresh", logout: "auth/logout", me: "me", passwordChange: "auth/password/change" },
  identity: { sessions: "me/sessions", revokeAllSessions: "me/sessions/revoke-all", mfaSetup: "me/mfa/setup", mfaConfirm: "me/mfa/confirm", mfaDisable: "me/mfa/disable", apiKeys: "api-keys", apiKey: (id: string) => `api-keys/${id}` },
  tenants: "tenants",
  users: "users",
  roles: "roles",
  documents: "documents",
  projects: { list: "projects/", create: "projects/", detail: (id: string) => `projects/${id}`, update: (id: string) => `projects/${id}`, status: (id: string) => `projects/${id}/status` },
  tasks: { list: "tasks/", create: "tasks/", detail: (id: string) => `tasks/${id}`, status: (id: string) => `tasks/${id}/status` },
  analytics: {
    metricDefinitions: "analytics/metric-definitions",
    metricDefinition: (id: string) => `analytics/metric-definitions/${id}`,
    metricReadings: "analytics/metric-readings",
    metricReading: (id: string) => `analytics/metric-readings/${id}`,
    metricReadingBatch: "analytics/metric-readings/batch",
    metricReadingSummary: "analytics/metric-readings/summary",
  },
  communication: {
    conversations: "communication/conversations",
    conversation: (id: string) => `communication/conversations/${id}`,
    conversationArchive: (id: string) => `communication/conversations/${id}/archive`,
    conversationParticipants: (id: string) => `communication/conversations/${id}/participants`,
    conversationParticipant: (conversationId: string, userId: string) =>
      `communication/conversations/${conversationId}/participants/${userId}`,
    conversationLeave: (id: string) => `communication/conversations/${id}/leave`,
    conversationPreferences: (id: string) => `communication/conversations/${id}/preferences`,
    conversationMessages: (id: string) => `communication/conversations/${id}/messages`,
    conversationRead: (id: string) => `communication/conversations/${id}/read`,
    conversationPins: (id: string) => `communication/conversations/${id}/pins`,
    conversationPin: (conversationId: string, messageId: string) =>
      `communication/conversations/${conversationId}/pins/${messageId}`,
    message: (id: string) => `communication/messages/${id}`,
    messageReactions: (id: string) => `communication/messages/${id}/reactions`,
    messageSearch: "communication/messages/search",
    attachmentUpload: "communication/attachments/upload",
    presence: "communication/presence",
  },
  maintenance: {
    devices: "maintenance/devices",
    device: (id: string) => `maintenance/devices/${id}`,
    deviceStatus: (id: string) => `maintenance/devices/${id}/status`,
    devicePm: (id: string) => `maintenance/devices/${id}/pm`,
    devicesDuePm: "maintenance/devices/due-pm",
    pmSchedule: "maintenance/pm-schedule",
    workOrders: "maintenance/work-orders",
    workOrdersGeneratePm: "maintenance/work-orders/generate-pm",
    workOrder: (id: string) => `maintenance/work-orders/${id}`,
    workOrderRoute: (id: string) => `maintenance/work-orders/${id}/route`,
    workOrderAssign: (id: string) => `maintenance/work-orders/${id}/assign`,
    workOrderStatus: (id: string) => `maintenance/work-orders/${id}/status`,
    workOrderApprove: (id: string) => `maintenance/work-orders/${id}/approve`,
    workOrderReject: (id: string) => `maintenance/work-orders/${id}/reject`,
    workOrderHistory: (id: string) => `maintenance/work-orders/${id}/history`,
    spareParts: "maintenance/spare-parts",
    sparePart: (id: string) => `maintenance/spare-parts/${id}`,
    partTransactions: (id: string) => `maintenance/spare-parts/${id}/transactions`,
    workOrderParts: (id: string) => `maintenance/work-orders/${id}/parts`,
    deviceAttachments: (id: string) => `maintenance/devices/${id}/attachments`,
    workOrderAttachments: (id: string) => `maintenance/work-orders/${id}/attachments`,
    maintenanceAttachment: (id: string) => `maintenance/attachments/${id}`,
    maintenanceAttachmentDownload: (id: string) => `maintenance/attachments/${id}/download`,
    deviceReport: (id: string) => `maintenance/devices/${id}/report`,
    deviceTimeline: (id: string) => `maintenance/devices/${id}/timeline`,
    // -- Phase 26: equipment registry ---------------------------------------
    locations: "maintenance/locations",
    location: (id: string) => `maintenance/locations/${id}`,
    personnel: "maintenance/personnel",
    personnelMember: (id: string) => `maintenance/personnel/${id}`,
    deviceProfile: (id: string) => `maintenance/devices/${id}/profile`,
    deviceNameplate: (id: string) => `maintenance/devices/${id}/nameplate`,
    assetTree: "maintenance/assets/tree",
    deviceAncestry: (id: string) => `maintenance/devices/${id}/ancestry`,
    deviceMovements: (id: string) => `maintenance/devices/${id}/movements`,
    deviceRetirement: (id: string) => `maintenance/devices/${id}/retirement`,
    deviceSpecifications: (id: string) => `maintenance/devices/${id}/specifications`,
    devicePmPlans: (id: string) => `maintenance/devices/${id}/pm-plans`,
    pmPlan: (id: string) => `maintenance/pm-plans/${id}`,
    pmPlanExecutions: (id: string) => `maintenance/pm-plans/${id}/executions`,
    deviceBom: (id: string) => `maintenance/devices/${id}/bom`,
    deviceBomItem: (deviceId: string, partId: string) =>
      `maintenance/devices/${deviceId}/bom/${partId}`,
    deviceAssignments: (id: string) => `maintenance/devices/${id}/assignments`,
    deviceAnalytics: (id: string) => `maintenance/devices/${id}/analytics`,
    fleetAnalytics: "maintenance/analytics/fleet",
    partUsageReport: (partId: string) => `maintenance/analytics/parts/${partId}`,
    workOrderClosure: (id: string) => `maintenance/work-orders/${id}/closure`,
    // -- Time & cost tracking (ثبت زمان و هزینه) ------------------------------
    workOrderLabour: (id: string) => `maintenance/work-orders/${id}/labour`,
    labourEntry: (id: string) => `maintenance/labour-entries/${id}`,
    workOrderCostSummary: (id: string) => `maintenance/work-orders/${id}/cost-summary`,
    maintenanceCostReport: "maintenance/reports/maintenance-costs",
    // -- Meter readings (ثبت قرائت دستی و سنسوری) ----------------------------
    deviceMeterPoints: (id: string) => `maintenance/devices/${id}/meter-points`,
    deviceMeterReadings: (id: string) => `maintenance/devices/${id}/meter-readings`,
    meterPoints: "maintenance/meter-points",
    meterPoint: (id: string) => `maintenance/meter-points/${id}`,
    meterPointReadings: (id: string) => `maintenance/meter-points/${id}/readings`,
    meterPointSummary: (id: string) => `maintenance/meter-points/${id}/summary`,
    meterReadings: "maintenance/meter-readings",
    meterReadingIngest: "maintenance/meter-readings/ingest",
    meterReadingCorrect: (id: string) => `maintenance/meter-readings/${id}/correct`,
    meterPmStatus: "maintenance/meter-pm-status",
    workOrderTimerStart: (id: string) => `maintenance/work-orders/${id}/timer/start`,
    workOrderTimerStop: (id: string) => `maintenance/work-orders/${id}/timer/stop`,
    workOrderTimers: (id: string) => `maintenance/work-orders/${id}/timers`,
    workTimerActive: "maintenance/work-timers/active",
    workTimer: (id: string) => `maintenance/work-timers/${id}`,
    scanResolve: "maintenance/scan",
    offlineSync: "maintenance/sync",
    offlineSyncHistory: "maintenance/sync/history",
    reviewCycles: "maintenance/performance-reviews/cycles",
    reviewCycle: (id: string) => `maintenance/performance-reviews/cycles/${id}`,
    reviewScores: "maintenance/performance-reviews/scores",
    reviewScore: (id: string) => `maintenance/performance-reviews/scores/${id}`,
    reviewCompute: "maintenance/performance-reviews/compute",
    reviewResults: "maintenance/performance-reviews/results",
    workCalendars: "maintenance/work-calendars",
    workCalendar: (id: string) => `maintenance/work-calendars/${id}`,
    calendarHolidays: "maintenance/work-calendars/holidays",
    calendarHoliday: (id: string) => `maintenance/work-calendars/holidays/${id}`,
    workShifts: "maintenance/work-calendars/shifts",
    workShift: (id: string) => `maintenance/work-calendars/shifts/${id}`,
    shiftAssignments: "maintenance/work-calendars/assignments",
    shiftAssignment: (id: string) => `maintenance/work-calendars/assignments/${id}`,
    capacityPlan: "maintenance/work-calendars/capacity",
    workingDay: "maintenance/work-calendars/working-day",
  },
  audit: "platform/audit-events",
  notifications: { list: "notifications", broadcasts: "notifications/broadcasts", unreadCount: "notifications/broadcasts/unread-count", read: (id: string) => `notifications/${id}/read`, broadcastRead: (id: string) => `notifications/broadcasts/${id}/read`, readBulk: "notifications/read-bulk", search: "notifications/search" },
  intelligence: {
    overview: (projectId: string) => `projects/${projectId}/intelligence/`,
    state: (projectId: string) => `projects/${projectId}/intelligence/state/`,
    architecture: (projectId: string) => `projects/${projectId}/intelligence/architecture/`,
    dependencies: (projectId: string) => `projects/${projectId}/intelligence/dependencies/`,
    insights: (projectId: string) => `projects/${projectId}/intelligence/insights/`,
    recommendations: (projectId: string) => `projects/${projectId}/intelligence/recommendations/`,
    context: (projectId: string) => `projects/${projectId}/intelligence/context/`,
    buildContext: (projectId: string) => `projects/${projectId}/intelligence/context/build/`,
    analyze: (projectId: string) => `projects/${projectId}/intelligence/analyze/`,
    reanalyze: (projectId: string) => `projects/${projectId}/intelligence/reanalyze/`,
    changes: (projectId: string) => `projects/${projectId}/intelligence/changes/`,
    resume: (projectId: string) => `projects/${projectId}/intelligence/resume/`,
    compare: (projectId: string) => `projects/${projectId}/intelligence/compare/`,
  },
} as const;
