/** Versioned application-interface paths. Feature code never assembles API versions or auth headers. */
export const apiEndpoints = {
  auth: { login: "auth/login", refresh: "auth/refresh", logout: "auth/logout", me: "me", passwordChange: "auth/password/change" },
  identity: { sessions: "me/sessions", revokeAllSessions: "me/sessions/revoke-all", mfaSetup: "me/mfa/setup", mfaConfirm: "me/mfa/confirm", mfaDisable: "me/mfa/disable", apiKeys: "api-keys", apiKey: (id: string) => `api-keys/${id}` },
  tenants: "tenants",
  users: "users",
  roles: "roles",
  projects: { list: "projects/", create: "projects/", detail: (id: string) => `projects/${id}`, update: (id: string) => `projects/${id}`, status: (id: string) => `projects/${id}/status` },
  tasks: { list: "tasks/", create: "tasks/", detail: (id: string) => `tasks/${id}`, status: (id: string) => `tasks/${id}/status` },
  maintenance: {
    devices: "maintenance/devices",
    device: (id: string) => `maintenance/devices/${id}`,
    deviceStatus: (id: string) => `maintenance/devices/${id}/status`,
    devicePm: (id: string) => `maintenance/devices/${id}/pm`,
    devicesDuePm: "maintenance/devices/due-pm",
    workOrders: "maintenance/work-orders",
    workOrdersGeneratePm: "maintenance/work-orders/generate-pm",
    workOrder: (id: string) => `maintenance/work-orders/${id}`,
    workOrderRoute: (id: string) => `maintenance/work-orders/${id}/route`,
    workOrderAssign: (id: string) => `maintenance/work-orders/${id}/assign`,
    workOrderStatus: (id: string) => `maintenance/work-orders/${id}/status`,
    workOrderApprove: (id: string) => `maintenance/work-orders/${id}/approve`,
    workOrderReject: (id: string) => `maintenance/work-orders/${id}/reject`,
    workOrderHistory: (id: string) => `maintenance/work-orders/${id}/history`,
    spareParts: "maintenance/spare-parts",
    sparePart: (id: string) => `maintenance/spare-parts/${id}`,
    workOrderParts: (id: string) => `maintenance/work-orders/${id}/parts`,
    deviceReport: (id: string) => `maintenance/devices/${id}/report`,
    deviceTimeline: (id: string) => `maintenance/devices/${id}/timeline`,
  },
  audit: "platform/audit-events",
  notifications: { list: "notifications", broadcasts: "notifications/broadcasts", unreadCount: "notifications/broadcasts/unread-count", read: (id: string) => `notifications/${id}/read`, broadcastRead: (id: string) => `notifications/broadcasts/${id}/read`, readBulk: "notifications/read-bulk", search: "notifications/search" },
  intelligence: {
    overview: (projectId: string) => `projects/${projectId}/intelligence/`,
    state: (projectId: string) => `projects/${projectId}/intelligence/state/`,
    architecture: (projectId: string) => `projects/${projectId}/intelligence/architecture/`,
    dependencies: (projectId: string) => `projects/${projectId}/intelligence/dependencies/`,
    insights: (projectId: string) => `projects/${projectId}/intelligence/insights/`,
    recommendations: (projectId: string) => `projects/${projectId}/intelligence/recommendations/`,
    context: (projectId: string) => `projects/${projectId}/intelligence/context/`,
    buildContext: (projectId: string) => `projects/${projectId}/intelligence/context/build/`,
    analyze: (projectId: string) => `projects/${projectId}/intelligence/analyze/`,
    reanalyze: (projectId: string) => `projects/${projectId}/intelligence/reanalyze/`,
    changes: (projectId: string) => `projects/${projectId}/intelligence/changes/`,
    resume: (projectId: string) => `projects/${projectId}/intelligence/resume/`,
    compare: (projectId: string) => `projects/${projectId}/intelligence/compare/`,
  },
} as const;
