import { useMemo, useState } from "react";
import { NavLink, useLocation } from "react-router-dom";
import { useLocalization } from "../core/localization/localizationContext";
import { PERMISSIONS } from "../core/permissions/permissionContext";
import { demoActivity } from "../features/demo/demoData";
import { demoTenants } from "../core/tenant/tenantContext";
import { DataTable, type DataTableColumn } from "../shared/components/DataTable";
import { ActivityFeed } from "../shared/components/featureComponents";
import { Modal, Toast } from "../shared/components/overlays";
import { Avatar, Badge, Button, Card, CardHeader, PermissionGuard, SectionHeader, StatusBadge, TextInput } from "../shared/components/primitives";
import { Icon } from "../shared/components/Icon";

interface UserRecord { id: string; name: string; email: string; role: string; status: "active" | "pending" | "archived"; lastActive: string; access: string; }
const users: UserRecord[] = [
  { id: "u1", name: "Maya Chen", email: "maya.chen@example.test", role: "Platform Administrator", status: "active", lastActive: "Now", access: "All domains" },
  { id: "u2", name: "Jon Bell", email: "jon.bell@example.test", role: "Workspace Manager", status: "active", lastActive: "12 min ago", access: "Projects · Quality" },
  { id: "u3", name: "Sara Novak", email: "sara.novak@example.test", role: "Operations Lead", status: "active", lastActive: "2 hr ago", access: "Operations" },
  { id: "u4", name: "Owen Wright", email: "owen.wright@example.test", role: "Auditor", status: "active", lastActive: "Yesterday", access: "Read-only" },
  { id: "u5", name: "Leila Haddad", email: "leila.haddad@example.test", role: "Member", status: "pending", lastActive: "Invitation sent", access: "Service" },
];

export function AdministrationPage(): JSX.Element {
  const { t } = useLocalization();
  const location = useLocation();
  const section = location.pathname.split("/").pop() ?? "users";
  const [addUserOpen, setAddUserOpen] = useState(false);
  const [toast, setToast] = useState("");
  const nav = [{ id: "users", label: t("admin.users"), icon: "users" as const, path: "/app/administration/users" }, { id: "roles", label: t("admin.roles"), icon: "key" as const, path: "/app/administration/roles" }, { id: "tenants", label: t("admin.tenants"), icon: "building" as const, path: "/app/administration/tenants" }, { id: "audit", label: t("admin.audit"), icon: "activity" as const, path: "/app/administration/audit" }];
  return <div className="page"><SectionHeader eyebrow={t("nav.administration")} title={t("admin.title")} subtitle={t("admin.subtitle")} actions={<PermissionGuard permission={PERMISSIONS.userManage}><Button variant="primary" icon="plus" onClick={() => setAddUserOpen(true)}>{t("admin.addUser")}</Button></PermissionGuard>} /><div className="admin-layout"><aside className="admin-nav">{nav.map((item) => <NavLink to={item.path} key={item.id} className={({ isActive }) => `admin-nav__item ${isActive ? "is-active" : ""}`}><Icon name={item.icon} size={17} /><span>{item.label}</span><Icon name="chevronRight" size={14} /></NavLink>)}</aside><div className="admin-content">{section === "roles" ? <Roles /> : section === "tenants" ? <Tenants /> : section === "audit" ? <Audit /> : <Users />}</div></div><Modal open={addUserOpen} title={t("admin.addUser")} onClose={() => setAddUserOpen(false)} footer={<><Button variant="secondary" onClick={() => setAddUserOpen(false)}>{t("common.cancel")}</Button><Button variant="primary" onClick={() => { setAddUserOpen(false); setToast("Invitation sent."); }}>{t("common.save")}</Button></>}><div className="form-grid"><TextInput label={t("admin.user")} placeholder="Name" required /><TextInput label="Email" type="email" required /><TextInput label={t("admin.role")} defaultValue="Member" /></div></Modal>{toast && <Toast message={toast} onClose={() => setToast("")} />}</div>;
}

function Users(): JSX.Element { const { t } = useLocalization(); const columns = useMemo<DataTableColumn<UserRecord>[]>(() => [{ key: "name", label: t("admin.user"), accessor: (row) => `${row.name} ${row.email}`, sortable: true, width: "28%", render: (row) => <div className="person-cell"><Avatar name={row.name} size="sm" tone="purple" /><div><strong>{row.name}</strong><span>{row.email}</span></div></div> }, { key: "role", label: t("admin.role"), accessor: (row) => row.role, sortable: true }, { key: "status", label: t("project.status"), accessor: (row) => row.status, render: (row) => <StatusBadge status={row.status} /> }, { key: "lastActive", label: t("admin.lastActive"), accessor: (row) => row.lastActive }, { key: "access", label: t("admin.access"), accessor: (row) => row.access, render: (row) => <span className="muted-cell">{row.access}</span> }, { key: "action", label: t("project.actions"), hideable: false, render: () => <Button variant="ghost" size="sm" icon="edit">{t("common.edit")}</Button> }], [t]); return <div className="admin-section"><Card padding="none"><CardHeader title={t("admin.users")} subtitle="Manage people, roles and tenant memberships." /><DataTable columns={columns} data={users} rowKey={(row) => row.id} exportName="tekarai-users" /></Card></div>; }

function Roles(): JSX.Element { const { t } = useLocalization(); const roles = [{ name: "Platform Administrator", members: 2, permissions: 48, scope: "Global" }, { name: "Workspace Manager", members: 6, permissions: 31, scope: "Tenant" }, { name: "Operations Lead", members: 14, permissions: 22, scope: "Tenant" }, { name: "Auditor", members: 3, permissions: 12, scope: "Tenant" }, { name: "Member", members: 223, permissions: 9, scope: "Tenant" }]; return <div className="admin-section"><Card padding="md"><CardHeader title={t("admin.roles")} subtitle="Permission bundles are evaluated server-side and mirrored here for rendering." action={<PermissionGuard permission={PERMISSIONS.roleManage}><Button variant="primary" size="sm" icon="plus">Create role</Button></PermissionGuard>} /><div className="role-list">{roles.map((role) => <div className="role-row" key={role.name}><span className="role-row__icon"><Icon name="key" size={17} /></span><div><strong>{role.name}</strong><span>{role.scope} scope · {role.permissions} permissions</span></div><span className="role-row__members">{role.members} members</span><Button variant="ghost" size="sm" icon="edit">{t("common.edit")}</Button></div>)}</div></Card><Card padding="md"><CardHeader title={t("admin.permissions")} /><div className="permission-matrix">{["project.view", "project.create", "project.update", "task.view", "document.upload", "report.view", "audit.view", "projectIntelligence.analyze"].map((permission) => <div key={permission}><code>{permission}</code><span><i className="status-dot status-dot--green" />Granted to 4 roles</span></div>)}</div></Card></div>; }

function Tenants(): JSX.Element { const { t } = useLocalization(); return <div className="admin-section"><Card padding="md"><CardHeader title={t("admin.tenants")} subtitle="Global platform operators can manage tenant lifecycle and isolation." /><div className="tenant-admin-list">{demoTenants.map((tenant) => <div className="tenant-admin-row" key={tenant.id}><span className="tenant-avatar tenant-avatar--large">{tenant.name.slice(0, 1)}</span><div><strong>{tenant.name}</strong><span>{tenant.code} · {tenant.industry}</span></div><Badge tone="success" dot>{tenant.status}</Badge><span>{tenant.members} members</span><Button variant="ghost" size="sm" icon="settings">{t("common.view")}</Button></div>)}</div></Card></div>; }

function Audit(): JSX.Element { const { t } = useLocalization(); return <div className="admin-section"><Card padding="md"><CardHeader title={t("admin.audit")} subtitle="Immutable activity records with correlation and tenant context." action={<Button variant="secondary" size="sm" icon="download">{t("common.export")}</Button>} /><ActivityFeed items={demoActivity} /></Card><Card padding="md"><CardHeader title="Audit controls" /><div className="audit-controls"><div><Icon name="shield" size={20} /><strong>Append-only stream</strong><span>Audit records cannot be edited from the GUI.</span></div><div><Icon name="lock" size={20} /><strong>Tenant-scoped</strong><span>Queries require a valid tenant context and audit.view.</span></div><div><Icon name="clock" size={20} /><strong>Retention governed</strong><span>Retention follows platform and tenant policy.</span></div></div></Card></div>; }
