import { useEffect, useState } from "react";
import { useLocation } from "react-router-dom";
import { useLocalization } from "../core/localization/localizationContext";
import { useApiClient } from "../core/api/apiContext";
import { useAsyncResource } from "../core/api/serverState";
import { PERMISSIONS } from "../core/permissions/permissionContext";
import { useTenant } from "../core/tenant/tenantContext";
import { loadIntelligence } from "../features/intelligence/intelligenceService";
import { demoIntelligence } from "../features/demo/demoData";
import type { IntelligenceData, IntelligenceRecommendation } from "../shared/types/intelligence";
import { BarChart, DonutChart } from "../shared/components/charts";
import { Modal, Toast } from "../shared/components/overlays";
import { Badge, Button, Card, CardHeader, PermissionGuard, ProgressBar, SectionHeader, StatusBadge, TextArea, TextInput } from "../shared/components/primitives";
import { Icon } from "../shared/components/Icon";

type IntelligenceTab = "overview" | "architecture" | "dependencies" | "changes" | "insights" | "recommendations" | "context";

const riskLabel = (v: string): string => v === "high" ? "بالا" : v === "medium" ? "متوسط" : "کم";
const severityLabel = (v: string): string => v === "critical" ? "بحرانی" : v === "high" ? "بالا" : v === "medium" ? "متوسط" : "پایین";
const priorityLabel = (v: string): string => v === "high" ? "بالا" : v === "medium" ? "متوسط" : "پایین";
const depTypeLabel = (v: string): string => v === "internal" ? "داخلی" : "خارجی";
const changeKindLabel = (v: string): string => v === "added" ? "افزوده‌شده" : v === "deleted" ? "حذف‌شده" : "به‌روزرسانی";


export function IntelligencePage(): JSX.Element {
  const { t } = useLocalization();
  const api = useApiClient();
  const { selectedTenant } = useTenant();
  const location = useLocation();
  const intelligenceResource = useAsyncResource((signal) => loadIntelligence(api, demoIntelligence.projectId, signal), [api, selectedTenant.id], { initialData: demoIntelligence, cacheKey: `${selectedTenant.id}:project-intelligence:${demoIntelligence.projectId}` });
  const [data, setData] = useState<IntelligenceData>(demoIntelligence);
  useEffect(() => { if (intelligenceResource.data) setData(intelligenceResource.data); }, [intelligenceResource.data]);
  const [tab, setTab] = useState<IntelligenceTab>(location.hash === "#insights" ? "insights" : "overview");
  const [analyzing, setAnalyzing] = useState(false);
  const [analysisProgress, setAnalysisProgress] = useState(0);
  const [contextOpen, setContextOpen] = useState(false);
  const [task, setTask] = useState("");
  const [toast, setToast] = useState("");
  useEffect(() => { if (location.hash === "#insights") setTab("insights"); }, [location.hash]);
  const tabs: { id: IntelligenceTab; label: string; icon: "activity" | "layers" | "link" | "clock" | "lightbulb" | "target" | "book" }[] = [
    { id: "overview", label: t("intelligence.overview"), icon: "activity" }, { id: "architecture", label: t("intelligence.architecture"), icon: "layers" }, { id: "dependencies", label: t("intelligence.dependencies"), icon: "link" }, { id: "changes", label: t("intelligence.changes"), icon: "clock" }, { id: "insights", label: t("intelligence.insights"), icon: "lightbulb" }, { id: "recommendations", label: t("intelligence.recommendations"), icon: "target" }, { id: "context", label: t("intelligence.context"), icon: "book" },
  ];
  const runAnalysis = (): void => {
    setAnalyzing(true); setAnalysisProgress(0); setData((current) => ({ ...current, state: "scanning" }));
    const interval = window.setInterval(() => setAnalysisProgress((current) => {
      const next = Math.min(100, current + 20);
      if (next === 100) { window.clearInterval(interval); setAnalyzing(false); setData((currentData) => ({ ...currentData, state: "ready", lastAnalysis: new Date().toISOString() })); setToast(t("intelligence.contextBuilt")); }
      return next;
    }), 220);
  };
  const buildContext = (): void => { if (!task.trim()) return; setContextOpen(false); setToast(t("intelligence.contextBuilt")); };
  const updateRecommendation = (id: string, status: IntelligenceRecommendation["status"]): void => setData((current) => ({ ...current, recommendations: current.recommendations.map((item) => item.id === id ? { ...item, status } : item) }));

  return <div className="page"><SectionHeader eyebrow={t("nav.intelligence")} title={t("intelligence.title")} subtitle={t("intelligence.subtitle")} actions={<div className="section-actions"><StatusBadge status={data.state === "ready" ? "active" : data.state === "scanning" ? "running" : data.state} /><PermissionGuard permission={PERMISSIONS.intelligenceAnalyze}><Button variant="primary" icon="sparkles" loading={analyzing} onClick={runAnalysis}>{analyzing ? `${analysisProgress}%` : t("intelligence.analyze")}</Button></PermissionGuard></div>} />
    {analyzing && <div className="job-progress" role="status"><div><span><span className="live-dot" />Analysis job running</span><strong>{analysisProgress}%</strong></div><ProgressBar value={analysisProgress} showValue={false} tone="purple" /></div>}
    <Card className="intelligence-project-bar" padding="md"><div className="intelligence-project-bar__identity"><span className="project-cell__icon project-cell__icon--large"><Icon name="folder" size={20} /></span><div><span className="eyebrow">NOVA-24 · تحلیل فضای کاری</span><h2>{data.projectName}</h2><p>آخرین تحلیل {data.lastAnalysis.slice(0, 10)} · {data.analysisVersion}</p></div></div><div className="intelligence-project-bar__facts"><div><span>{t("intelligence.files")}</span><strong>{data.filesAnalyzed}</strong></div><div><span>{t("intelligence.health")}</span><strong className="text-success">{data.healthScore}%</strong></div><div><span>{t("intelligence.insights")}</span><strong>{data.insights.length}</strong></div><div><span>{t("intelligence.recommendations")}</span><strong>{data.recommendations.length}</strong></div></div></Card>
    <div className="intelligence-tabs" role="tablist">{tabs.map((item) => <button key={item.id} role="tab" aria-selected={tab === item.id} className={tab === item.id ? "is-active" : ""} onClick={() => setTab(item.id)}><Icon name={item.icon} size={15} />{item.label}</button>)}</div>
    {tab === "overview" && <Overview data={data} />}{tab === "architecture" && <Architecture data={data} />}{tab === "dependencies" && <Dependencies data={data} />}{tab === "changes" && <Changes data={data} />}{tab === "insights" && <Insights data={data} />}{tab === "recommendations" && <Recommendations data={data} onUpdate={updateRecommendation} />}{tab === "context" && <Context data={data} onBuild={() => setContextOpen(true)} />}
    <Modal open={contextOpen} title={t("intelligence.buildContext")} onClose={() => setContextOpen(false)} footer={<><Button variant="secondary" onClick={() => setContextOpen(false)}>{t("common.cancel")}</Button><Button variant="primary" icon="sparkles" onClick={buildContext}>{t("intelligence.buildContext")}</Button></>}><TextArea label={t("intelligence.taskPrompt")} value={task} onChange={(event) => setTask(event.target.value)} rows={4} placeholder={t("intelligence.taskPrompt")} required /><TextInput label={t("intelligence.tokenBudget")} type="number" defaultValue="4000" min="256" max="100000" /></Modal>
    {toast && <Toast message={toast} onClose={() => setToast("")} />}
  </div>;
}

function Overview({ data }: { data: IntelligenceData }): JSX.Element { const { t } = useLocalization(); return <div className="intelligence-grid"><Card padding="md"><CardHeader title={t("intelligence.health")} subtitle="امتیاز قابل‌توضیح از تحلیل‌گرهای قطعی." /><div className="health-overview"><DonutChart value={data.healthScore} label="امتیاز" color="#27b27e" ariaLabel={`Project health ${data.healthScore} percent`} /><div className="health-overview__breakdown">{data.healthBreakdown.map((item) => <div key={item.label}><div><strong>{item.label}</strong><span>{item.score}%</span></div><ProgressBar value={item.score} showValue={false} tone={item.score < 80 ? "amber" : "green"} /><small>{item.detail}</small></div>)}</div></div></Card><Card padding="md"><CardHeader title="زبان‌ها" subtitle="تشخیص از روی نوع فایل و تعداد خطوط کد." /><BarChart data={data.languages.map((item) => item.percentage)} labels={data.languages.map((item) => item.name)} color="#2878ff" ariaLabel="Project language percentages" /><div className="language-list">{data.languages.map((item) => <div key={item.name}><span><i className="legend-dot legend-dot--blue" />{item.name}</span><strong>{item.percentage}%</strong><small>{item.loc.toLocaleString()} خط کد</small></div>)}</div></Card><Card padding="md" className="intelligence-full"><CardHeader title="شواهد مسیر تحلیل" subtitle="اسنپ‌شات → مشاهده → تحلیل → دانش → بینش → پیشنهاد." /><div className="pipeline"><PipelineStep label="اسنپ‌شات" value="تغییرناپذیر" tone="blue" /><PipelineStep label="مشاهده" value={`${data.filesAnalyzed} فایل`} tone="purple" /><PipelineStep label="تحلیل" value={data.analysisVersion} tone="green" /><PipelineStep label="دانش" value="نسخه‌بندی‌شده" tone="amber" /><PipelineStep label="تصمیم" value="بازبینی انسانی" tone="blue" /></div></Card></div>; }
function PipelineStep({ label, value, tone }: { label: string; value: string; tone: "blue" | "purple" | "green" | "amber" }): JSX.Element { return <div className="pipeline-step"><span className={`pipeline-step__icon pipeline-step__icon--${tone}`}><Icon name={label === "اسنپ‌شات" ? "cloud" : label === "مشاهده" ? "search" : label === "تحلیل" ? "sparkles" : label === "دانش" ? "book" : "shield"} size={17} /></span><strong>{label}</strong><span>{value}</span></div>; }
function Architecture({ data }: { data: IntelligenceData }): JSX.Element { const { t } = useLocalization(); return <div className="intelligence-grid"><Card padding="md"><CardHeader title={t("intelligence.architecture")} subtitle="سلامت لایه‌ها و توزیع ماژول‌ها." /><div className="architecture-layers">{data.architecture.map((item, index) => <div className="architecture-layer" key={item.layer}><div className="architecture-layer__number">0{index + 1}</div><div className="architecture-layer__main"><div><strong>{item.layer}</strong><span>{item.modules} ماژول</span></div><ProgressBar value={item.score} tone={item.score < 80 ? "amber" : "blue"} /></div><strong>{item.score}%</strong></div>)}</div></Card><Card padding="md"><CardHeader title="جهت وابستگی" subtitle="جهت مورد انتظار: نمایش → کاربرد → دامنه → زیرساخت." /><div className="direction-diagram"><span>نمایش</span><Icon name="arrowDown" size={16} /><span>کاربرد</span><Icon name="arrowDown" size={16} /><span>دامنه</span><Icon name="arrowDown" size={16} /><span>زیرساخت</span></div><div className="callout callout--success"><Icon name="checkCircle" size={17} /><span>در اسنپ‌شات فعلی تخطی بحرانی لایه‌ای دیده نشد.</span></div></Card></div>; }
function Dependencies({ data }: { data: IntelligenceData }): JSX.Element { const { t } = useLocalization(); return <Card padding="md"><CardHeader title={t("intelligence.dependencies")} subtitle="بسته‌های داخلی و خارجی که تحلیل‌گر وابستگی یافته است." /><div className="dependency-list">{data.dependencies.map((dependency) => <div className="dependency-row" key={dependency.name}><span className={`dependency-type dependency-type--${dependency.type}`}>{dependency.type === "internal" ? "↗" : "◉"}</span><div><strong>{dependency.name}</strong><span>{depTypeLabel(dependency.type)} · {dependency.version}</span></div><Badge tone={dependency.risk === "high" ? "danger" : dependency.risk === "medium" ? "warning" : "success"}>{riskLabel(dependency.risk)} ریسک</Badge><Button variant="ghost" size="sm" icon="external">{t("common.view")}</Button></div>)}</div></Card>; }
function Changes({ data }: { data: IntelligenceData }): JSX.Element { const { t } = useLocalization(); return <Card padding="md"><CardHeader title={t("intelligence.changes")} subtitle="تغییرات اخیر از تاریخچه‌ی تغییرناپذیر پروژه." action={<Button variant="secondary" size="sm" icon="refresh">{t("common.refresh")}</Button>} /><div className="change-list">{data.changes.map((change) => <div className="change-row" key={change.path}><span className={`change-kind change-kind--${change.kind}`}>{change.kind === "added" ? "+" : change.kind === "deleted" ? "−" : "~"}</span><div><strong>{change.path}</strong><span>{change.author} · {change.timestamp}</span></div><Badge tone={change.kind === "deleted" ? "danger" : change.kind === "added" ? "success" : "info"}>{changeKindLabel(change.kind)}</Badge></div>)}</div></Card>; }
function Insights({ data }: { data: IntelligenceData }): JSX.Element { return <div className="insight-list">{data.insights.map((insight) => <Card padding="md" className={`insight-card insight-card--${insight.severity}`} key={insight.id}><div className="insight-card__top"><Badge tone={insight.severity === "high" ? "danger" : insight.severity === "medium" ? "warning" : insight.severity === "critical" ? "danger" : "info"}>{severityLabel(insight.severity)}</Badge><span>اطمینان {Math.round(insight.confidence * 100)}٪</span></div><h2>{insight.title}</h2><p>{insight.what}</p><div className="evidence-box"><strong>چرا مهم است</strong><span>{insight.why}</span><strong>شواهد</strong><span>{insight.evidence}</span></div><footer><Icon name="book" size={14} />{insight.source}</footer></Card>)}</div>; }
function Recommendations({ data, onUpdate }: { data: IntelligenceData; onUpdate: (id: string, status: IntelligenceRecommendation["status"]) => void }): JSX.Element { const { t } = useLocalization(); return <div className="recommendation-list">{data.recommendations.map((recommendation) => <Card padding="md" className="recommendation-card" key={recommendation.id}><div className="recommendation-card__top"><Badge tone={recommendation.priority === "high" ? "danger" : recommendation.priority === "medium" ? "warning" : "info"}>{priorityLabel(recommendation.priority)}</Badge><StatusBadge status={recommendation.status === "review" ? "pending" : recommendation.status === "accepted" ? "completed" : recommendation.status === "deferred" ? "archived" : "active"} /></div><h2>{recommendation.title}</h2><div className="recommendation-facts"><div><span>مسئله</span><p>{recommendation.problem}</p></div><div><span>منفعت مورد انتظار</span><p>{recommendation.benefit}</p></div><div><span>ریسک</span><p>{recommendation.risk}</p></div></div><div className="recommendation-card__actions"><PermissionGuard permission={PERMISSIONS.intelligenceAnalyze}><Button variant="primary" size="sm" icon="check" disabled={recommendation.status === "accepted"} onClick={() => onUpdate(recommendation.id, "accepted")}>پذیرفتن</Button><Button variant="ghost" size="sm" icon="clock" onClick={() => onUpdate(recommendation.id, "deferred")}>به تعویق انداختن</Button></PermissionGuard><Button variant="ghost" size="sm" icon="book">{t("common.view")}</Button></div></Card>)}</div>; }
function Context({ data, onBuild }: { data: IntelligenceData; onBuild: () => void }): JSX.Element { const { t } = useLocalization(); return <div className="context-layout"><Card padding="md"><CardHeader title={t("intelligence.context")} subtitle="زمینه‌ی متناسب با وظیفه و سقف توکن برای دستیارها." action={<PermissionGuard permission={PERMISSIONS.intelligenceAnalyze}><Button variant="primary" size="sm" icon="sparkles" onClick={onBuild}>{t("intelligence.buildContext")}</Button></PermissionGuard>} /><div className="context-metadata"><div><span>مولد</span><strong>سازنده‌ی زمینه ۱.۴</strong></div><div><span>سقف توکن</span><strong>۴٬۰۰۰</strong></div><div><span>فایل‌های شامل</span><strong>{data.contextFiles.length}</strong></div><div><span>موارد حذف</span><strong>عبارات محرمانه · باینری‌ها · تولیدشده‌ها</strong></div></div><div className="context-files">{data.contextFiles.map((file, index) => <div key={file}><span>{String(index + 1).padStart(2, "0")}</span><code>{file}</code><Icon name="checkCircle" size={16} /></div>)}</div></Card><Card padding="md" className="context-side"><CardHeader title="قرارداد زمینه" /><div className="contract-list"><span><Icon name="shield" size={15} />مرتبط با سازمان</span><span><Icon name="lock" size={15} />فیلتر بر اساس دسترسی</span><span><Icon name="clock" size={15} />پیوست‌شده به نسخه</span><span><Icon name="target" size={15} />مرتبط با وظیفه</span></div></Card></div>; }
