import { useMemo, useState } from "react";
import { useLocalization } from "../core/localization/localizationContext";
import { useNotifications } from "../core/notifications/notificationContext";
import { Toast } from "../shared/components/overlays";
import { Badge, Button, Card, CardHeader, SectionHeader } from "../shared/components/primitives";
import { Icon } from "../shared/components/Icon";

export function NotificationsPage(): JSX.Element {
  const { t } = useLocalization();
  const { notifications, unreadCount, markRead, markAllRead } = useNotifications();
  const [filter, setFilter] = useState<"all" | "unread" | "important">("all");
  const [toast, setToast] = useState("");
  const visible = useMemo(() => notifications.filter((item) => filter === "all" || filter === "unread" && !item.read || filter === "important" && (item.priority === "critical" || item.priority === "high")), [filter, notifications]);
  return <div className="page"><SectionHeader eyebrow={t("nav.workspace")} title={t("notification.title")} subtitle={t("notification.subtitle")} actions={unreadCount > 0 ? <Button variant="secondary" icon="check" onClick={() => { markAllRead(); setToast(t("notification.markAll")); }}>{t("notification.markAll")}</Button> : undefined} /><Card className="notifications-card" padding="none"><CardHeader title={`${unreadCount} ${t("notification.unread")}`} action={<div className="segmented-control" role="tablist">{(["all", "unread", "important"] as const).map((item) => <button key={item} role="tab" aria-selected={filter === item} className={filter === item ? "is-active" : ""} onClick={() => setFilter(item)}>{item === "all" ? t("notification.all") : item === "unread" ? t("notification.unread") : t("notification.important")}</button>)}</div>} />{visible.length === 0 ? <div className="state state--empty"><span className="state__icon"><Icon name="bell" size={24} /></span><h3>{t("notification.empty")}</h3></div> : <div className="notification-list">{visible.map((notification) => <article className={`notification-row ${notification.read ? "is-read" : "is-unread"}`} key={notification.id}><span className={`notification-row__icon notification-row__icon--${notification.type}`}><Icon name={notification.type === "task" ? "checkSquare" : notification.type === "project" ? "folder" : notification.type === "security" ? "shield" : notification.type === "insight" ? "lightbulb" : "bell"} size={18} /></span><div className="notification-row__body"><div className="notification-row__title"><h3>{notification.title}</h3>{notification.priority === "critical" && <Badge tone="danger">{t("common.priority.critical")}</Badge>}</div><p>{notification.body}</p><span>{notification.createdAt}</span></div><div className="notification-row__actions">{!notification.read && <Button variant="ghost" size="sm" icon="check" onClick={() => markRead(notification.id)}>{t("notification.read")}</Button>}{notification.actionLabel && <Button variant="secondary" size="sm" icon="arrowRight" onClick={() => { markRead(notification.id); setToast(`${notification.title} opened.`); }}>{notification.actionLabel}</Button>}</div></article>)}</div>}</Card>{toast && <Toast message={toast} onClose={() => setToast("")} />}</div>;
}
