import { useEffect, useMemo, useState } from "react";
import { runtimeConfig } from "../app/configuration/runtimeConfig";
import { useApiClient } from "../core/api/apiContext";
import { PERMISSIONS } from "../core/permissions/permissionContext";
import { DataTable, type DataTableColumn } from "../shared/components/DataTable";
import { Modal, Toast } from "../shared/components/overlays";
import { Badge, Button, Card, CardHeader, PermissionGuard, SectionHeader, SelectInput, TextInput, TextArea } from "../shared/components/primitives";

type Supplier = { id: string; code: string; name: string; status: string; contactName: string; phone: string; defaultLeadTimeDays: number; currency: string };
type DocumentRow = { id: string; number?: string; status: string; total?: string | number; createdAt?: string; supplierId?: string; };
const demoSuppliers: Supplier[] = [{ id: "sup-demo", code: "SUP-001", name: "تأمین‌کننده نمونه", status: "active", contactName: "واحد فروش", phone: "", defaultLeadTimeDays: 7, currency: "IRR" }];
const tabs = ["overview", "suppliers", "requisitions", "orders", "receipts", "returns", "invoices"] as const;
type Tab = typeof tabs[number];

export function ProcurementPage(): JSX.Element {
  const api = useApiClient(); const [tab, setTab] = useState<Tab>("overview");
  const [suppliers, setSuppliers] = useState<Supplier[]>(runtimeConfig.demoMode ? demoSuppliers : []);
  const [rows, setRows] = useState<DocumentRow[]>([]); const [loading, setLoading] = useState(!runtimeConfig.demoMode); const [toast, setToast] = useState("");
  const [supplierOpen, setSupplierOpen] = useState(false); const [supplierForm, setSupplierForm] = useState({ code: "", name: "", contactName: "", phone: "", defaultLeadTimeDays: "7", paymentTerms: "", currency: "IRR" });
  const [reqOpen, setReqOpen] = useState(false); const [reqForm, setReqForm] = useState({ partId: "", partCode: "", partName: "", unit: "عدد", quantity: "1", estimatedUnitCost: "0", priority: "normal", justification: "" });
  const [dashboard, setDashboard] = useState<Record<string, string | number>>({});
  const [parts, setParts] = useState<Array<{ id: string; code: string; name: string; unit: string; unitCost: number }>>([]);
  const endpoint = tab === "requisitions" ? "procurement/requisitions" : tab === "orders" ? "procurement/purchase-orders" : tab === "receipts" ? "procurement/receipts" : tab === "returns" ? "procurement/returns" : "procurement/invoices";
  const load = (): void => { if (runtimeConfig.demoMode) return; setLoading(true); void api.get<DocumentRow[]>(tab === "suppliers" ? "procurement/suppliers" : endpoint).then((data) => tab === "suppliers" ? setSuppliers(data as unknown as Supplier[]) : setRows(data)).catch(() => setToast("دریافت اطلاعات ناموفق بود.")).finally(() => setLoading(false)); };
  useEffect(() => {
    if (runtimeConfig.demoMode) { setParts([{ id: "sp-demo", code: "DEMO-001", name: "قطعه نمونه", unit: "عدد", unitCost: 100000 }]); return; }
    void api.get<Record<string, string | number>>("procurement/dashboard").then(setDashboard).catch(() => undefined);
    void api.get<Array<{ id: string; code: string; name: string; unit: string; unitCost: number }>>("maintenance/spare-parts").then(setParts).catch(() => undefined);
  }, [api]);
  useEffect(() => { if (tab !== "overview") load(); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tab]);
  const saveSupplier = (): void => { const payload = { ...supplierForm, defaultLeadTimeDays: Number(supplierForm.defaultLeadTimeDays) }; if (runtimeConfig.demoMode) { setSuppliers((x) => [...x, { id: `demo-${Date.now()}`, ...payload, status: "active" }]); setSupplierOpen(false); setToast("تأمین‌کننده اضافه شد."); return; } void api.post<Supplier>("procurement/suppliers", payload).then((item) => { setSuppliers((x) => [...x, item]); setSupplierOpen(false); setToast("تأمین‌کننده اضافه شد."); }).catch(() => setToast("ذخیره ناموفق بود.")); };
  const saveRequisition = (): void => { const payload = { ...reqForm, quantity: Number(reqForm.quantity), estimatedUnitCost: Number(reqForm.estimatedUnitCost), lines: [{ ...reqForm, quantity: Number(reqForm.quantity), estimatedUnitCost: Number(reqForm.estimatedUnitCost) }] }; if (runtimeConfig.demoMode) { setReqOpen(false); setToast("درخواست خرید ایجاد شد."); return; } void api.post("procurement/requisitions", payload).then(() => { setReqOpen(false); setToast("درخواست خرید ایجاد شد."); }).catch(() => setToast("ذخیره ناموفق بود.")); };
  const columns = useMemo<DataTableColumn<DocumentRow>[]>(() => [{ key: "number", label: "شماره", accessor: (r) => r.number ?? r.id }, { key: "status", label: "وضعیت", accessor: (r) => r.status, render: (r) => <Badge tone={r.status === "approved" || r.status === "received" ? "success" : r.status === "rejected" || r.status === "cancelled" ? "danger" : "warning"}>{r.status}</Badge> }, { key: "total", label: "مبلغ", accessor: (r) => r.total ?? "—" }, { key: "createdAt", label: "تاریخ", accessor: (r) => r.createdAt ?? "—" }], []);
  return <div className="page"><SectionHeader eyebrow="CMMS" title="تدارکات و خرید" subtitle="چرخه‌ی تأمین قطعه از تأمین‌کننده تا رسید انبار و فاکتور." actions={<><PermissionGuard permission={PERMISSIONS.procurementSupplierManage}><Button variant="secondary" onClick={() => setSupplierOpen(true)}>افزودن تأمین‌کننده</Button></PermissionGuard><PermissionGuard permission={PERMISSIONS.procurementRequisitionCreate}><Button variant="primary" onClick={() => setReqOpen(true)}>درخواست خرید جدید</Button></PermissionGuard></>} />
    <div className="segmented-control" role="tablist">{tabs.map((item) => <button type="button" role="tab" aria-selected={tab === item} className={tab === item ? "is-active" : ""} onClick={() => setTab(item)} key={item}>{({ overview: "نمای کلی", suppliers: "تأمین‌کنندگان", requisitions: "درخواست‌ها", orders: "سفارش خرید", receipts: "رسید انبار", returns: "برگشت کالا", invoices: "فاکتورها" } as Record<Tab, string>)[item]}</button>)}</div>
    {tab === "overview" ? <div className="stats-grid"><Card padding="md"><strong>{runtimeConfig.demoMode ? 1 : dashboard.suppliers ?? 0}</strong><span>تأمین‌کننده فعال</span></Card><Card padding="md"><strong>{runtimeConfig.demoMode ? 2 : dashboard.openRequisitions ?? 0}</strong><span>درخواست باز</span></Card><Card padding="md"><strong>{runtimeConfig.demoMode ? 1 : dashboard.openPurchaseOrders ?? 0}</strong><span>سفارش باز</span></Card><Card padding="md"><strong>{runtimeConfig.demoMode ? 0 : dashboard.pendingReceipts ?? 0}</strong><span>رسید در انتظار</span></Card></div> : tab === "suppliers" ? <Card padding="none"><CardHeader title="فهرست تأمین‌کنندگان" /><DataTable columns={[{ key: "code", label: "کد", accessor: (r: Supplier) => r.code }, { key: "name", label: "نام", accessor: (r: Supplier) => r.name }, { key: "contact", label: "تماس", accessor: (r: Supplier) => `${r.contactName} ${r.phone}` }, { key: "lead", label: "Lead time", accessor: (r: Supplier) => `${r.defaultLeadTimeDays} روز` }, { key: "status", label: "وضعیت", accessor: (r: Supplier) => r.status }]} data={suppliers} rowKey={(r) => r.id} empty={{ title: loading ? "در حال بارگذاری…" : "تأمین‌کننده‌ای ثبت نشده است" }} /> </Card> : <Card padding="none"><CardHeader title={({ requisitions: "درخواست‌های خرید", orders: "سفارش‌های خرید", receipts: "رسیدهای انبار", returns: "برگشت کالا", invoices: "فاکتورهای تأمین‌کننده" } as Record<string, string>)[tab]} /><DataTable columns={columns} data={rows} rowKey={(r) => r.id} empty={{ title: loading ? "در حال بارگذاری…" : "موردی ثبت نشده است" }} /></Card>}
    <Modal open={supplierOpen} title="افزودن تأمین‌کننده" onClose={() => setSupplierOpen(false)} footer={<><Button variant="secondary" onClick={() => setSupplierOpen(false)}>انصراف</Button><Button variant="primary" onClick={saveSupplier}>ذخیره</Button></>}><div className="form-grid"><TextInput label="کد تأمین‌کننده" required value={supplierForm.code} onChange={(e) => setSupplierForm({ ...supplierForm, code: e.target.value })} /><TextInput label="نام تأمین‌کننده" required value={supplierForm.name} onChange={(e) => setSupplierForm({ ...supplierForm, name: e.target.value })} /><TextInput label="نام تماس" value={supplierForm.contactName} onChange={(e) => setSupplierForm({ ...supplierForm, contactName: e.target.value })} /><TextInput label="تلفن" value={supplierForm.phone} onChange={(e) => setSupplierForm({ ...supplierForm, phone: e.target.value })} /><TextInput label="Lead time روز" type="number" value={supplierForm.defaultLeadTimeDays} onChange={(e) => setSupplierForm({ ...supplierForm, defaultLeadTimeDays: e.target.value })} /><SelectInput label="ارز" value={supplierForm.currency} onChange={(e) => setSupplierForm({ ...supplierForm, currency: e.target.value })} options={[{ value: "IRR", label: "ریال" }, { value: "USD", label: "دلار" }, { value: "EUR", label: "یورو" }]} /><TextInput label="شرایط پرداخت" value={supplierForm.paymentTerms} onChange={(e) => setSupplierForm({ ...supplierForm, paymentTerms: e.target.value })} /></div></Modal>
    <Modal open={reqOpen} title="درخواست خرید جدید" onClose={() => setReqOpen(false)} footer={<><Button variant="secondary" onClick={() => setReqOpen(false)}>انصراف</Button><Button variant="primary" onClick={saveRequisition}>ایجاد درخواست</Button></>}><div className="form-grid"><SelectInput label="قطعه انبار" required value={reqForm.partId} onChange={(e) => { const part = parts.find((item) => item.id === e.target.value); setReqForm({ ...reqForm, partId: e.target.value, partCode: part?.code ?? "", partName: part?.name ?? "", unit: part?.unit ?? "عدد", estimatedUnitCost: String(part?.unitCost ?? 0) }); }} options={[{ value: "", label: "انتخاب قطعه…" }, ...parts.map((part) => ({ value: part.id, label: `${part.code} — ${part.name}` }))]} /><TextInput label="کد قطعه" value={reqForm.partCode} readOnly /><TextInput label="تعداد" type="number" required value={reqForm.quantity} onChange={(e) => setReqForm({ ...reqForm, quantity: e.target.value })} /><TextInput label="برآورد قیمت واحد" type="number" value={reqForm.estimatedUnitCost} onChange={(e) => setReqForm({ ...reqForm, estimatedUnitCost: e.target.value })} /><SelectInput label="اولویت" value={reqForm.priority} onChange={(e) => setReqForm({ ...reqForm, priority: e.target.value })} options={[{ value: "low", label: "کم" }, { value: "normal", label: "عادی" }, { value: "high", label: "بالا" }, { value: "critical", label: "بحرانی" }]} /><TextArea label="دلیل درخواست" value={reqForm.justification} onChange={(e) => setReqForm({ ...reqForm, justification: e.target.value })} /></div></Modal>{toast && <Toast message={toast} onClose={() => setToast("")} />}</div>;
}
