import { useEffect, useMemo, useState } from "react";
import { runtimeConfig } from "../app/configuration/runtimeConfig";
import { useApiClient } from "../core/api/apiContext";
import { PERMISSIONS } from "../core/permissions/permissionContext";
import { formatJalali } from "../core/localization/jalali";
import { JalaliDatePicker } from "../shared/components/JalaliDatePicker";
import { DataTable, type DataTableColumn } from "../shared/components/DataTable";
import { Modal, Toast } from "../shared/components/overlays";
import { Badge, Button, Card, CardHeader, PermissionGuard, SectionHeader, SelectInput, TextInput, TextArea } from "../shared/components/primitives";

type Supplier = { id: string; code: string; name: string; status: string; contactName: string; phone: string; defaultLeadTimeDays: number; currency: string };
type Line = { id?: string; partId: string; partCode: string; partName: string; unit: string; quantity: number | string; estimatedUnitCost?: number | string; unitPrice?: number | string; orderedQuantity?: number | string; receivedQuantity?: number | string };
type DocumentRow = { id: string; number?: string; status: string; total?: string | number; createdAt?: string; supplierId?: string; requisitionId?: string; lines?: Line[] };
const demoSuppliers: Supplier[] = [{ id: "sup-demo", code: "SUP-001", name: "تأمین‌کننده نمونه", status: "active", contactName: "واحد فروش", phone: "", defaultLeadTimeDays: 7, currency: "IRR" }];
const tabs = ["overview", "suppliers", "requisitions", "orders", "receipts", "returns", "invoices"] as const;
type Tab = typeof tabs[number];

export function ProcurementPage(): JSX.Element {
  const api = useApiClient(); const [tab, setTab] = useState<Tab>("overview");
  const [suppliers, setSuppliers] = useState<Supplier[]>(runtimeConfig.demoMode ? demoSuppliers : []);
  const [rows, setRows] = useState<DocumentRow[]>([]); const [loading, setLoading] = useState(!runtimeConfig.demoMode); const [toast, setToast] = useState("");
  const [supplierOpen, setSupplierOpen] = useState(false); const [supplierForm, setSupplierForm] = useState({ code: "", name: "", contactName: "", phone: "", defaultLeadTimeDays: "7", paymentTerms: "", currency: "IRR" });
  const [partOpen, setPartOpen] = useState(false); const [partForm, setPartForm] = useState({ code: "", name: "", unit: "عدد", quantityOnHand: "0", minimumStock: "0", unitCost: "0" });
  const [reqOpen, setReqOpen] = useState(false); const [reqForm, setReqForm] = useState({ partId: "", partCode: "", partName: "", unit: "عدد", quantity: "1", estimatedUnitCost: "0", priority: "normal", justification: "" });
  const [poOpen, setPoOpen] = useState(false); const [poForm, setPoForm] = useState({ supplierId: "", requisitionId: "", expectedDate: "", unitPrice: "0", taxAmount: "0" });
  const [receiptOpen, setReceiptOpen] = useState(false); const [receiptForm, setReceiptForm] = useState({ purchaseOrderId: "", purchaseOrderLineId: "", quantity: "1", rejectedQuantity: "0", unitCost: "0" });
  const [returnOpen, setReturnOpen] = useState(false); const [returnForm, setReturnForm] = useState({ supplierId: "", purchaseOrderId: "", partId: "", quantity: "1", unitCost: "0", reason: "" });
  const [invoiceOpen, setInvoiceOpen] = useState(false); const [invoiceForm, setInvoiceForm] = useState({ invoiceNumber: "", supplierId: "", purchaseOrderId: "", subtotal: "0", taxAmount: "0", total: "0", dueDate: "" });
  const [dashboard, setDashboard] = useState<Record<string, string | number>>({});
  const [historyOpen, setHistoryOpen] = useState(false); const [historyRows, setHistoryRows] = useState<Array<Record<string, unknown>>>([]); const [historyTitle, setHistoryTitle] = useState("");
  const [parts, setParts] = useState<Array<{ id: string; code: string; name: string; unit: string; unitCost: number }>>([]);
  const endpointFor = (target: Tab): string => target === "requisitions" ? "procurement/requisitions" : target === "orders" ? "procurement/purchase-orders" : target === "receipts" ? "procurement/receipts" : target === "returns" ? "procurement/returns" : "procurement/invoices";
  const refreshDashboard = (): void => { if (!runtimeConfig.demoMode) void api.get<Record<string, string | number>>("procurement/dashboard").then(setDashboard).catch(() => undefined); };
  const load = (target: Tab = tab): void => { if (runtimeConfig.demoMode || target === "overview") return; setLoading(true); void api.get<DocumentRow[]>(target === "suppliers" ? "procurement/suppliers" : endpointFor(target)).then((data) => target === "suppliers" ? setSuppliers(data as unknown as Supplier[]) : setRows(data)).catch(() => setToast("دریافت اطلاعات ناموفق بود.")).finally(() => setLoading(false)); };
  useEffect(() => { if (runtimeConfig.demoMode) { setParts([{ id: "sp-demo", code: "DEMO-001", name: "قطعه نمونه", unit: "عدد", unitCost: 100000 }]); return; } refreshDashboard(); void api.get<Array<{ id: string; code: string; name: string; unit: string; unitCost: number }>>("maintenance/spare-parts").then(setParts).catch(() => undefined); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [api]);
  useEffect(() => { if (tab === "overview") refreshDashboard(); else load(tab); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tab]);
  const openHistory = (documentType: "requisition" | "purchaseOrder", id: string, title: string): void => { setHistoryTitle(title); if (runtimeConfig.demoMode) { setHistoryRows([]); setHistoryOpen(true); return; } void api.get<Array<Record<string, unknown>>>(`procurement/approval-history/${documentType}/${id}`).then(setHistoryRows).catch(() => setHistoryRows([])).finally(() => setHistoryOpen(true)); };
  const action = (id: string, verb: string, nextTab: Tab): void => { if (runtimeConfig.demoMode) { setRows((current) => current.map((x) => x.id === id ? { ...x, status: verb === "submit" ? "submitted" : verb === "approve" ? "approved" : verb === "reject" ? "rejected" : x.status } : x)); setToast("عملیات انجام شد."); return; } void api.post(`procurement/${nextTab === "requisitions" ? "requisitions" : "purchase-orders"}/${id}/${verb}`, {}).then(() => { setToast("عملیات با موفقیت انجام شد."); load(nextTab); refreshDashboard(); }).catch(() => setToast("عملیات انجام نشد.")); };
  const saveSupplier = (): void => { const payload = { ...supplierForm, defaultLeadTimeDays: Number(supplierForm.defaultLeadTimeDays) }; if (runtimeConfig.demoMode) { setSuppliers((x) => [...x, { id: `demo-${Date.now()}`, ...payload, status: "active" }]); setSupplierOpen(false); setToast("تأمین‌کننده اضافه شد."); return; } void api.post<Supplier>("procurement/suppliers", payload).then((item) => { setSuppliers((x) => [...x, item]); setSupplierOpen(false); setToast("تأمین‌کننده اضافه شد."); }).catch(() => setToast("ذخیره ناموفق بود.")); };
  const savePart = (): void => {
    if (!partForm.code.trim() || !partForm.name.trim()) { setToast("کد و نام قطعه الزامی است."); return; }
    const payload = { ...partForm, quantityOnHand: Number(partForm.quantityOnHand), minimumStock: Number(partForm.minimumStock), unitCost: Number(partForm.unitCost) };
    if (runtimeConfig.demoMode) { const item = { id: `demo-part-${Date.now()}`, ...payload }; setParts((current) => [...current, item]); setReqForm((current) => ({ ...current, partId: item.id, partCode: item.code, partName: item.name, unit: item.unit, estimatedUnitCost: String(item.unitCost) })); setPartOpen(false); setToast("قطعه اضافه شد و انتخاب شد."); return; }
    void api.post<{ id: string; code: string; name: string; unit: string; unitCost: number }>("maintenance/spare-parts", payload).then((item) => { setParts((current) => [...current, item]); setReqForm((current) => ({ ...current, partId: item.id, partCode: item.code, partName: item.name, unit: item.unit, estimatedUnitCost: String(item.unitCost) })); setPartOpen(false); setToast("قطعه اضافه شد و انتخاب شد."); }).catch(() => setToast("ثبت قطعه ناموفق بود."));
  };
  const saveRequisition = (): void => { if (!reqForm.partId || Number(reqForm.quantity) <= 0) { setToast("قطعه و مقدار معتبر را انتخاب کن."); return; } const payload = { ...reqForm, quantity: Number(reqForm.quantity), estimatedUnitCost: Number(reqForm.estimatedUnitCost), lines: [{ ...reqForm, quantity: Number(reqForm.quantity), estimatedUnitCost: Number(reqForm.estimatedUnitCost) }] }; if (runtimeConfig.demoMode) { const created: DocumentRow = { id: `demo-pr-${Date.now()}`, number: `PR-DEMO-${Date.now().toString().slice(-5)}`, status: "draft", total: Number(reqForm.quantity) * Number(reqForm.estimatedUnitCost), createdAt: new Date().toISOString(), lines: [{ ...reqForm, quantity: Number(reqForm.quantity) }] }; setRows((current) => [created, ...current]); setDashboard((current) => ({ ...current, openRequisitions: Number(current.openRequisitions ?? 2) + 1 })); setReqOpen(false); setTab("requisitions"); setToast("درخواست خرید ایجاد شد."); return; } void api.post<DocumentRow>("procurement/requisitions", payload).then((created) => { setReqOpen(false); setRows((current) => [created, ...current]); setTab("requisitions"); load("requisitions"); refreshDashboard(); setToast("درخواست خرید ایجاد شد."); }).catch(() => setToast("ذخیره ناموفق بود.")); };
  const createOrder = (): void => { const req = rows.find((x) => x.id === poForm.requisitionId); const lines = req?.lines ?? []; if (!poForm.supplierId || !req || !lines.length) { setToast("یک درخواست تأییدشده و تأمین‌کننده انتخاب کن."); return; } const payload = { supplierId: poForm.supplierId, requisitionId: req.id, expectedDate: poForm.expectedDate || null, taxAmount: Number(poForm.taxAmount), lines: lines.map((line) => ({ partId: line.partId, partCode: line.partCode, partName: line.partName, unit: line.unit, quantity: Number(line.quantity), unitPrice: Number(poForm.unitPrice) })) }; void api.post("procurement/purchase-orders", payload).then(() => { setPoOpen(false); setToast("سفارش خرید ایجاد شد."); setTab("orders"); }).catch(() => setToast("ایجاد سفارش خرید ناموفق بود.")); };
  const postReceipt = (): void => { if (!receiptForm.purchaseOrderId || !receiptForm.purchaseOrderLineId) { setToast("سفارش و قلم سفارش را انتخاب کن."); return; } void api.post("procurement/receipts", { purchaseOrderId: receiptForm.purchaseOrderId, receiverName: "", lines: [{ purchaseOrderLineId: receiptForm.purchaseOrderLineId, quantity: Number(receiptForm.quantity), rejectedQuantity: Number(receiptForm.rejectedQuantity), unitCost: Number(receiptForm.unitCost) }] }).then(() => { setReceiptOpen(false); setToast("رسید انبار ثبت شد و موجودی به‌روزرسانی شد."); setTab("receipts"); }).catch(() => setToast("ثبت رسید ناموفق بود.")); };
  const postReturn = (): void => { if (!returnForm.supplierId || !returnForm.partId) { setToast("تأمین‌کننده و قطعه را انتخاب کن."); return; } void api.post("procurement/returns", { ...returnForm, purchaseOrderId: returnForm.purchaseOrderId || null, quantity: Number(returnForm.quantity), unitCost: Number(returnForm.unitCost), lines: [{ partId: returnForm.partId, quantity: Number(returnForm.quantity), unitCost: Number(returnForm.unitCost) }] }).then(() => { setReturnOpen(false); setToast("برگشت کالا ثبت شد و موجودی کم شد."); setTab("returns"); }).catch(() => setToast("ثبت برگشت ناموفق بود.")); };
  const postInvoice = (): void => { if (!invoiceForm.invoiceNumber || !invoiceForm.supplierId) { setToast("شماره فاکتور و تأمین‌کننده الزامی است."); return; } void api.post("procurement/invoices", { ...invoiceForm, subtotal: Number(invoiceForm.subtotal), taxAmount: Number(invoiceForm.taxAmount), total: Number(invoiceForm.total), purchaseOrderId: invoiceForm.purchaseOrderId || null, invoiceDate: null, dueDate: invoiceForm.dueDate || null }).then(() => { setInvoiceOpen(false); setToast("فاکتور ثبت شد."); setTab("invoices"); }).catch(() => setToast("ثبت فاکتور ناموفق بود.")); };
  const docColumns = useMemo<DataTableColumn<DocumentRow>[]>(() => [{ key: "number", label: "شماره", accessor: (r) => r.number ?? r.id }, { key: "status", label: "وضعیت", accessor: (r) => r.status, render: (r) => <Badge tone={r.status === "approved" || r.status === "received" ? "success" : r.status === "rejected" || r.status === "cancelled" ? "danger" : "warning"}>{r.status}</Badge> }, { key: "total", label: "مبلغ", accessor: (r) => r.total ?? "—" }, { key: "createdAt", label: "تاریخ ساخت", accessor: (r) => r.createdAt ? formatJalali(r.createdAt, { withTime: true }) : "—" }], []);
  const reqRows = rows.filter((x) => tab !== "requisitions" || x.status !== "rejected"); const chosenPo = rows.find((x) => x.id === receiptForm.purchaseOrderId); const chosenReq = rows.find((x) => x.id === poForm.requisitionId);
  return <div className="page procurement-page"><SectionHeader eyebrow="CMMS" title="تدارکات و خرید" subtitle="چرخه‌ی تأمین قطعه از تأمین‌کننده تا رسید انبار و فاکتور." actions={<><PermissionGuard permission={PERMISSIONS.procurementSupplierManage}><Button variant="secondary" onClick={() => setSupplierOpen(true)}>افزودن تأمین‌کننده</Button></PermissionGuard><PermissionGuard permission={PERMISSIONS.procurementRequisitionCreate}><Button variant="primary" onClick={() => setReqOpen(true)}>درخواست خرید جدید</Button></PermissionGuard></>} />
    <div className="segmented-control" role="tablist">{tabs.map((item) => <button type="button" role="tab" aria-selected={tab === item} className={tab === item ? "is-active" : ""} onClick={() => setTab(item)} key={item}>{({ overview: "نمای کلی", suppliers: "تأمین‌کنندگان", requisitions: "درخواست‌ها", orders: "سفارش خرید", receipts: "رسید انبار", returns: "برگشت کالا", invoices: "فاکتورها" } as Record<Tab, string>)[item]}</button>)}</div>
    {tab === "overview" ? <div className="stats-grid"><Card padding="md"><strong>{runtimeConfig.demoMode ? 1 : dashboard.suppliers ?? 0}</strong><span>تأمین‌کننده فعال</span></Card><Card padding="md"><strong>{runtimeConfig.demoMode ? dashboard.openRequisitions ?? 2 : dashboard.openRequisitions ?? 0}</strong><span>درخواست باز</span></Card><Card padding="md"><strong>{runtimeConfig.demoMode ? 1 : dashboard.openPurchaseOrders ?? 0}</strong><span>سفارش باز</span></Card><Card padding="md"><strong>{runtimeConfig.demoMode ? 0 : dashboard.pendingReceipts ?? 0}</strong><span>رسید در انتظار</span></Card></div> : tab === "suppliers" ? <Card padding="none"><CardHeader title="فهرست تأمین‌کنندگان" action={<PermissionGuard permission={PERMISSIONS.procurementSupplierManage}><Button size="sm" variant="secondary" onClick={() => setSupplierOpen(true)}>افزودن</Button></PermissionGuard>} /><DataTable columns={[{ key: "code", label: "کد", accessor: (r: Supplier) => r.code }, { key: "name", label: "نام", accessor: (r: Supplier) => r.name }, { key: "contact", label: "تماس", accessor: (r: Supplier) => `${r.contactName} ${r.phone}` }, { key: "lead", label: "Lead time", accessor: (r: Supplier) => `${r.defaultLeadTimeDays} روز` }, { key: "status", label: "وضعیت", accessor: (r: Supplier) => r.status }]} data={suppliers} rowKey={(r) => r.id} empty={{ title: loading ? "در حال بارگذاری…" : "تأمین‌کننده‌ای ثبت نشده است" }} /></Card> : <Card padding="none"><CardHeader title={({ requisitions: "درخواست‌های خرید", orders: "سفارش‌های خرید", receipts: "رسیدهای انبار", returns: "برگشت کالا", invoices: "فاکتورهای تأمین‌کننده" } as Record<string, string>)[tab]} action={<>{tab === "requisitions" && <PermissionGuard permission={PERMISSIONS.procurementPurchaseOrderCreate}><Button size="sm" variant="secondary" onClick={() => setPoOpen(true)}>ساخت سفارش خرید</Button></PermissionGuard>}{tab === "orders" && <PermissionGuard permission={PERMISSIONS.procurementReceiptPost}><Button size="sm" variant="secondary" onClick={() => setReceiptOpen(true)}>ثبت رسید انبار</Button></PermissionGuard>}{tab === "receipts" && <PermissionGuard permission={PERMISSIONS.procurementReturnPost}><Button size="sm" variant="secondary" onClick={() => setReturnOpen(true)}>ثبت برگشت کالا</Button></PermissionGuard>}{tab === "orders" && <PermissionGuard permission={PERMISSIONS.procurementInvoiceManage}><Button size="sm" variant="secondary" onClick={() => setInvoiceOpen(true)}>ثبت فاکتور</Button></PermissionGuard>}</>} /><DataTable columns={docColumns} data={reqRows} rowKey={(r) => r.id} empty={{ title: loading ? "در حال بارگذاری…" : "موردی ثبت نشده است" }} /></Card>}
    {tab === "requisitions" && <div className="procurement-action-list">{rows.map((item) => <div key={item.id} className="procurement-action-row"><span>{item.number ?? item.id}</span><Badge tone="warning">{item.status}</Badge><Button size="sm" variant="ghost" onClick={() => openHistory("requisition", item.id, item.number ?? item.id)}>تاریخچه</Button><PermissionGuard permission={PERMISSIONS.procurementRequisitionCreate}>{item.status === "draft" && <Button size="sm" variant="ghost" onClick={() => action(item.id, "submit", "requisitions")}>ارسال برای بررسی</Button>}</PermissionGuard><PermissionGuard permission={PERMISSIONS.procurementRequisitionApprove}>{item.status === "submitted" && <><Button size="sm" variant="ghost" onClick={() => action(item.id, "approve", "requisitions")}>تأیید</Button><Button size="sm" variant="ghost" onClick={() => action(item.id, "reject", "requisitions")}>رد</Button></>}</PermissionGuard></div>)}</div>}
    {tab === "orders" && <div className="procurement-action-list">{rows.map((item) => <div key={item.id} className="procurement-action-row"><span>{item.number ?? item.id}</span><Badge tone="warning">{item.status}</Badge><Button size="sm" variant="ghost" onClick={() => openHistory("purchaseOrder", item.id, item.number ?? item.id)}>تاریخچه</Button><PermissionGuard permission={PERMISSIONS.procurementPurchaseOrderApprove}>{item.status === "draft" && <Button size="sm" variant="ghost" onClick={() => action(item.id, "submit", "orders")}>ارسال سفارش</Button>}{item.status === "submitted" && <><Button size="sm" variant="ghost" onClick={() => action(item.id, "approve", "orders")}>تأیید سفارش</Button><Button size="sm" variant="ghost" onClick={() => action(item.id, "cancel", "orders")}>لغو سفارش</Button></>}</PermissionGuard></div>)}</div>}
    <Modal open={partOpen} title="افزودن قطعه به انبار" onClose={() => setPartOpen(false)} footer={<><Button variant="secondary" onClick={() => setPartOpen(false)}>انصراف</Button><Button variant="primary" onClick={savePart}>ثبت قطعه</Button></>}><div className="form-grid"><TextInput label="کد قطعه" required value={partForm.code} onChange={(e) => setPartForm({ ...partForm, code: e.target.value })} /><TextInput label="نام قطعه" required value={partForm.name} onChange={(e) => setPartForm({ ...partForm, name: e.target.value })} /><TextInput label="واحد" value={partForm.unit} onChange={(e) => setPartForm({ ...partForm, unit: e.target.value })} /><TextInput label="موجودی اولیه" type="number" value={partForm.quantityOnHand} onChange={(e) => setPartForm({ ...partForm, quantityOnHand: e.target.value })} /><TextInput label="حداقل موجودی" type="number" value={partForm.minimumStock} onChange={(e) => setPartForm({ ...partForm, minimumStock: e.target.value })} /><TextInput label="قیمت واحد" type="number" value={partForm.unitCost} onChange={(e) => setPartForm({ ...partForm, unitCost: e.target.value })} /></div></Modal>
    <Modal open={supplierOpen} title="افزودن تأمین‌کننده" onClose={() => setSupplierOpen(false)} footer={<><Button variant="secondary" onClick={() => setSupplierOpen(false)}>انصراف</Button><Button variant="primary" onClick={saveSupplier}>ذخیره</Button></>}><div className="form-grid"><TextInput label="کد تأمین‌کننده" required value={supplierForm.code} onChange={(e) => setSupplierForm({ ...supplierForm, code: e.target.value })} /><TextInput label="نام تأمین‌کننده" required value={supplierForm.name} onChange={(e) => setSupplierForm({ ...supplierForm, name: e.target.value })} /><TextInput label="نام تماس" value={supplierForm.contactName} onChange={(e) => setSupplierForm({ ...supplierForm, contactName: e.target.value })} /><TextInput label="تلفن" value={supplierForm.phone} onChange={(e) => setSupplierForm({ ...supplierForm, phone: e.target.value })} /><TextInput label="Lead time روز" type="number" value={supplierForm.defaultLeadTimeDays} onChange={(e) => setSupplierForm({ ...supplierForm, defaultLeadTimeDays: e.target.value })} /><SelectInput label="ارز" value={supplierForm.currency} onChange={(e) => setSupplierForm({ ...supplierForm, currency: e.target.value })} options={[{ value: "IRR", label: "ریال" }, { value: "USD", label: "دلار" }, { value: "EUR", label: "یورو" }]} /><TextInput label="شرایط پرداخت" value={supplierForm.paymentTerms} onChange={(e) => setSupplierForm({ ...supplierForm, paymentTerms: e.target.value })} /></div></Modal>
    <Modal open={reqOpen} title="درخواست خرید جدید" onClose={() => setReqOpen(false)} footer={<><Button variant="secondary" onClick={() => setReqOpen(false)}>انصراف</Button><Button variant="primary" onClick={saveRequisition}>ایجاد درخواست</Button></>}><div className="form-grid"><div className="select-with-action"><SelectInput label="قطعه انبار" required value={reqForm.partId} onChange={(e) => { const part = parts.find((item) => item.id === e.target.value); setReqForm({ ...reqForm, partId: e.target.value, partCode: part?.code ?? "", partName: part?.name ?? "", unit: part?.unit ?? "عدد", estimatedUnitCost: String(part?.unitCost ?? 0) }); }} options={[{ value: "", label: parts.length ? "انتخاب قطعه…" : "قطعه‌ای ثبت نشده — افزودن قطعه" }, ...parts.map((part) => ({ value: part.id, label: `${part.code} — ${part.name}` }))]} /><Button type="button" size="sm" variant="ghost" onClick={() => setPartOpen(true)}>افزودن قطعه</Button></div><TextInput label="کد قطعه" value={reqForm.partCode} readOnly /><TextInput label="تعداد" type="number" required value={reqForm.quantity} onChange={(e) => setReqForm({ ...reqForm, quantity: e.target.value })} /><TextInput label="برآورد قیمت واحد" type="number" value={reqForm.estimatedUnitCost} onChange={(e) => setReqForm({ ...reqForm, estimatedUnitCost: e.target.value })} /><SelectInput label="اولویت" value={reqForm.priority} onChange={(e) => setReqForm({ ...reqForm, priority: e.target.value })} options={[{ value: "low", label: "کم" }, { value: "normal", label: "عادی" }, { value: "high", label: "بالا" }, { value: "critical", label: "بحرانی" }]} /><TextArea label="دلیل درخواست" value={reqForm.justification} onChange={(e) => setReqForm({ ...reqForm, justification: e.target.value })} /></div></Modal>
    <Modal open={poOpen} title="ساخت سفارش خرید" onClose={() => setPoOpen(false)} footer={<><Button variant="secondary" onClick={() => setPoOpen(false)}>انصراف</Button><Button variant="primary" onClick={createOrder}>ثبت سفارش خرید</Button></>}><div className="form-grid"><SelectInput label="درخواست تأییدشده" value={poForm.requisitionId} onChange={(e) => setPoForm({ ...poForm, requisitionId: e.target.value })} options={[{ value: "", label: "انتخاب درخواست…" }, ...rows.filter((x) => x.status === "approved").map((x) => ({ value: x.id, label: x.number ?? x.id }))]} /><div className="select-with-action"><SelectInput label="تأمین‌کننده" value={poForm.supplierId} onChange={(e) => setPoForm({ ...poForm, supplierId: e.target.value })} options={[{ value: "", label: suppliers.length ? "انتخاب تأمین‌کننده…" : "تأمین‌کننده‌ای ثبت نشده" }, ...suppliers.map((x) => ({ value: x.id, label: `${x.code} — ${x.name}` }))]} /><Button type="button" size="sm" variant="ghost" onClick={() => setSupplierOpen(true)}>افزودن تأمین‌کننده</Button></div><TextInput label="قیمت واحد" type="number" value={poForm.unitPrice} onChange={(e) => setPoForm({ ...poForm, unitPrice: e.target.value })} /><JalaliDatePicker label="تاریخ مورد انتظار تحویل" value={poForm.expectedDate} onChange={(value) => setPoForm({ ...poForm, expectedDate: value })} /><TextInput label="مالیات" type="number" value={poForm.taxAmount} onChange={(e) => setPoForm({ ...poForm, taxAmount: e.target.value })} />{chosenReq?.lines?.[0] && <p>قطعه: {chosenReq.lines[0].partName} — تعداد: {chosenReq.lines[0].quantity}</p>}</div></Modal>
    <Modal open={receiptOpen} title="ثبت رسید انبار" onClose={() => setReceiptOpen(false)} footer={<><Button variant="secondary" onClick={() => setReceiptOpen(false)}>انصراف</Button><Button variant="primary" onClick={postReceipt}>ثبت رسید</Button></>}><div className="form-grid"><SelectInput label="سفارش خرید" value={receiptForm.purchaseOrderId} onChange={(e) => { const po = rows.find((x) => x.id === e.target.value); setReceiptForm({ ...receiptForm, purchaseOrderId: e.target.value, purchaseOrderLineId: po?.lines?.[0]?.id ?? "", unitCost: String(po?.lines?.[0]?.unitPrice ?? 0) }); }} options={[{ value: "", label: "انتخاب سفارش…" }, ...rows.filter((x) => x.status === "approved" || x.status === "partiallyReceived").map((x) => ({ value: x.id, label: x.number ?? x.id }))]} />{chosenPo?.lines?.[0] && <p>قطعه: {chosenPo.lines[0].partName}</p>}<TextInput label="مقدار دریافتی" type="number" value={receiptForm.quantity} onChange={(e) => setReceiptForm({ ...receiptForm, quantity: e.target.value })} /><TextInput label="مقدار مردودی" type="number" value={receiptForm.rejectedQuantity} onChange={(e) => setReceiptForm({ ...receiptForm, rejectedQuantity: e.target.value })} /></div></Modal>
    <Modal open={returnOpen} title="ثبت برگشت کالا" onClose={() => setReturnOpen(false)} footer={<><Button variant="secondary" onClick={() => setReturnOpen(false)}>انصراف</Button><Button variant="primary" onClick={postReturn}>ثبت برگشت</Button></>}><div className="form-grid"><div className="select-with-action"><SelectInput label="تأمین‌کننده" value={returnForm.supplierId} onChange={(e) => setReturnForm({ ...returnForm, supplierId: e.target.value })} options={[{ value: "", label: suppliers.length ? "انتخاب تأمین‌کننده…" : "تأمین‌کننده‌ای ثبت نشده" }, ...suppliers.map((x) => ({ value: x.id, label: x.name }))]} /><Button type="button" size="sm" variant="ghost" onClick={() => setSupplierOpen(true)}>افزودن تأمین‌کننده</Button></div><div className="select-with-action"><SelectInput label="قطعه" value={returnForm.partId} onChange={(e) => setReturnForm({ ...returnForm, partId: e.target.value })} options={[{ value: "", label: parts.length ? "انتخاب قطعه…" : "قطعه‌ای ثبت نشده" }, ...parts.map((x) => ({ value: x.id, label: `${x.code} — ${x.name}` }))]} /><Button type="button" size="sm" variant="ghost" onClick={() => setPartOpen(true)}>افزودن قطعه</Button></div><TextInput label="مقدار" type="number" value={returnForm.quantity} onChange={(e) => setReturnForm({ ...returnForm, quantity: e.target.value })} /><TextArea label="دلیل برگشت" value={returnForm.reason} onChange={(e) => setReturnForm({ ...returnForm, reason: e.target.value })} /></div></Modal>
    <Modal open={historyOpen} title={`تاریخچه تأیید — ${historyTitle}`} onClose={() => setHistoryOpen(false)} footer={<Button variant="primary" onClick={() => setHistoryOpen(false)}>بستن</Button>}><div className="procurement-history">{historyRows.length ? historyRows.map((item, index) => <div key={String(item.id ?? index)}><strong>{String(item.action ?? "activity")}</strong><span>{String(item.actorName ?? "System")}</span><small>{String(item.actedAt ?? item.createdAt ?? "")}</small><p>{String(item.comment ?? "")}</p></div>) : <p>هنوز سابقه‌ای ثبت نشده است.</p>}</div></Modal>
    <Modal open={invoiceOpen} title="ثبت فاکتور تأمین‌کننده" onClose={() => setInvoiceOpen(false)} footer={<><Button variant="secondary" onClick={() => setInvoiceOpen(false)}>انصراف</Button><Button variant="primary" onClick={postInvoice}>ثبت فاکتور</Button></>}><div className="form-grid"><TextInput label="شماره فاکتور" required value={invoiceForm.invoiceNumber} onChange={(e) => setInvoiceForm({ ...invoiceForm, invoiceNumber: e.target.value })} /><div className="select-with-action"><SelectInput label="تأمین‌کننده" value={invoiceForm.supplierId} onChange={(e) => setInvoiceForm({ ...invoiceForm, supplierId: e.target.value })} options={[{ value: "", label: suppliers.length ? "انتخاب تأمین‌کننده…" : "تأمین‌کننده‌ای ثبت نشده" }, ...suppliers.map((x) => ({ value: x.id, label: x.name }))]} /><Button type="button" size="sm" variant="ghost" onClick={() => setSupplierOpen(true)}>افزودن تأمین‌کننده</Button></div><TextInput label="مبلغ پایه" type="number" value={invoiceForm.subtotal} onChange={(e) => setInvoiceForm({ ...invoiceForm, subtotal: e.target.value })} /><TextInput label="مالیات" type="number" value={invoiceForm.taxAmount} onChange={(e) => setInvoiceForm({ ...invoiceForm, taxAmount: e.target.value })} /><TextInput label="مبلغ کل" type="number" value={invoiceForm.total} onChange={(e) => setInvoiceForm({ ...invoiceForm, total: e.target.value })} /><JalaliDatePicker label="سررسید فاکتور" value={invoiceForm.dueDate} onChange={(value) => setInvoiceForm({ ...invoiceForm, dueDate: value })} /></div></Modal>{toast && <Toast message={toast} onClose={() => setToast("")} />}</div>;
}
