import { useState } from "react";
import { useLocalization } from "../core/localization/localizationContext";
import { useTheme } from "../core/theme/themeContext";
import { useTenant } from "../core/tenant/tenantContext";
import { Card, CardHeader, Button, SelectInput, TextInput, Badge, SectionHeader } from "../shared/components/primitives";
import { Icon } from "../shared/components/Icon";
import { Toast } from "../shared/components/overlays";

export function SettingsPage(): JSX.Element {
  const { t, locale, setLocale } = useLocalization();
  const { theme, setTheme } = useTheme();
  const { selectedTenant } = useTenant();
  const [saved, setSaved] = useState(false);

  return <div className="page"><SectionHeader eyebrow={t("nav.account")} title={t("nav.settings")} subtitle={t("settings.subtitle")} actions={<Button variant="primary" icon="check" onClick={() => setSaved(true)}>{t("common.save")}</Button>} /><div className="settings-grid"><Card padding="md"><CardHeader title={t("settings.appearance")} subtitle={t("settings.appearanceHint")} /><div className="settings-form"><div className="setting-row"><div><strong>{t("settings.theme")}</strong><span>{t("settings.themeHint")}</span></div><div className="theme-switcher"><button type="button" className={theme === "light" ? "is-active" : ""} onClick={() => setTheme("light")}><Icon name="sun" size={16} />{t("settings.themeLight")}</button><button type="button" className={theme === "dark" ? "is-active" : ""} onClick={() => setTheme("dark")}><Icon name="moon" size={16} />{t("settings.themeDark")}</button></div></div><div className="setting-row"><div><strong>{t("settings.language")}</strong><span>{t("settings.languageHint")}</span></div><SelectInput aria-label={t("settings.language")} value={locale} onChange={(event) => setLocale(event.target.value as "en" | "fa" | "de")} options={[{ value: "en", label: "English · LTR" }, { value: "fa", label: "فارسی · RTL" }, { value: "de", label: "Deutsch · LTR" }]} /></div></div></Card><Card padding="md"><CardHeader title={t("settings.workspace")} subtitle={t("settings.workspaceHint")} /><div className="workspace-context"><span className="workspace-context__icon"><Icon name="building" size={22} /></span><div><span className="eyebrow">{t("header.tenant")}</span><h2>{selectedTenant.name}</h2><p>{selectedTenant.industry} · {selectedTenant.plan}</p></div><Badge tone="success" dot>{t("common.status.active")}</Badge></div><div className="context-security"><Icon name="shield" size={17} /><span>{t("settings.tenantNote")}</span></div></Card><Card padding="md"><CardHeader title={t("settings.accessibility")} subtitle={t("settings.accessibilityHint")} /><div className="accessibility-list"><span><Icon name="checkCircle" size={16} />{t("settings.a11yFocus")}</span><span><Icon name="checkCircle" size={16} />{t("settings.a11yLandmarks")}</span><span><Icon name="checkCircle" size={16} />{t("settings.a11yMotion")}</span><span><Icon name="checkCircle" size={16} />{t("settings.a11yRtl")}</span></div></Card><Card padding="md"><CardHeader title={t("settings.security")} subtitle={t("settings.securityHint")} /><div className="security-summary"><div><Icon name="lock" size={20} /><strong>{t("settings.protectedSession")}</strong><span>{t("settings.protectedSessionHint")}</span></div><div><Icon name="shield" size={20} /><strong>{t("settings.permissionUi")}</strong><span>{t("settings.permissionUiHint")}</span></div></div><TextInput label={t("settings.sessionPolicy")} value={t("settings.sessionPolicyValue")} readOnly /></Card></div>{saved && <Toast message={t("common.save")} onClose={() => setSaved(false)} />}</div>;
}
