# Generated by Django 6.1 on 2026-09-06 12:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_phase11_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachmentmodel',
            name='checksum',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='messageattachmentmodel',
            name='classification',
            field=models.CharField(default='INTERNAL', max_length=16),
        ),
        migrations.AddField(
            model_name='messageattachmentmodel',
            name='scanStatus',
            field=models.CharField(db_index=True, default='PENDING', max_length=12),
        ),
        migrations.AddField(
            model_name='messageattachmentmodel',
            name='storageKey',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='forwardSnapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='forwardedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='forwardedById',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='forwardedFromId',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='recordingmodel',
            name='checksum',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='recordingmodel',
            name='fileSizeBytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recordingmodel',
            name='storageKey',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='channelprofilemodel',
            name='conversationId',
            field=models.UUIDField(db_index=True, unique=True),
        ),
        migrations.CreateModel(
            name='CommunicationRetentionRunModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('requestedById', models.UUIDField(blank=True, null=True)),
                ('dryRun', models.BooleanField(default=True)),
                ('status', models.CharField(default='COMPLETED', max_length=12)),
                ('cutoff', models.DateTimeField()),
                ('counts', models.JSONField(default=dict)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communicationRetentionRuns',
                'indexes': [models.Index(fields=['tenantId', 'createdAt'], name='IX_CommRet_t_created')],
            },
        ),
        migrations.CreateModel(
            name='CommunicationSyncReceiptModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('userId', models.UUIDField(db_index=True)),
                ('clientBatchId', models.CharField(max_length=100)),
                ('requestHash', models.CharField(max_length=64)),
                ('result', models.JSONField(default=dict)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communicationSyncReceipts',
                'indexes': [models.Index(fields=['tenantId', 'userId', 'createdAt'], name='IX_CommSync_t_user')],
                'constraints': [models.UniqueConstraint(fields=('tenantId', 'userId', 'clientBatchId'), name='UQ_CommSync_t_user_batch')],
            },
        ),
    ]
