# Generated by Django 6.1 on 2026-08-31 11:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_phase10_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationPolicyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True, unique=True)),
                ('messageRetentionDays', models.IntegerField(default=2555)),
                ('recordingRetentionDays', models.IntegerField(default=730)),
                ('transcriptRetentionDays', models.IntegerField(default=2555)),
                ('presenceRetentionDays', models.IntegerField(default=30)),
                ('auditRetentionDays', models.IntegerField(default=3650)),
                ('maxAttachmentSize', models.BigIntegerField(default=26214400)),
                ('maxMessageLength', models.IntegerField(default=8000)),
                ('maxGroupMembers', models.IntegerField(default=5000)),
                ('maxMeetingParticipants', models.IntegerField(default=500)),
                ('allowedFileTypes', models.JSONField(default=list)),
                ('allowExternalUsers', models.BooleanField(default=False)),
                ('allowRecording', models.BooleanField(default=True)),
                ('allowScreenSharing', models.BooleanField(default=True)),
                ('allowMessageEdit', models.BooleanField(default=True)),
                ('allowMessageDelete', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communicationPolicies',
            },
        ),
        # NOTE: the auto-generated AlterField on channelprofilemodel.conversationId
        # is a pre-existing Phase-09 drift and is intentionally omitted so this
        # migration stays purely additive (Phase 11 tables only).
        migrations.CreateModel(
            name='ActionItemCandidateModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('meetingId', models.UUIDField(db_index=True)),
                ('summaryId', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('suggestedAssigneeId', models.UUIDField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('candidateState', models.CharField(db_index=True, default='CANDIDATE', max_length=12)),
                ('reviewNote', models.CharField(blank=True, default='', max_length=500)),
                ('dispatchedItemRef', models.CharField(blank=True, default='', max_length=120)),
                ('reviewedBy', models.UUIDField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communicationActionItemCandidates',
                'indexes': [models.Index(fields=['meetingId'], name='IX_Act_meeting'), models.Index(fields=['candidateState'], name='IX_Act_state')],
            },
        ),
        migrations.CreateModel(
            name='LegalHoldModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('holdScope', models.CharField(max_length=16)),
                ('targetId', models.UUIDField(db_index=True)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('holdStatus', models.CharField(db_index=True, default='ACTIVE', max_length=10)),
                ('createdById', models.UUIDField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('releasedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'communicationLegalHolds',
                'indexes': [models.Index(fields=['targetId', 'holdStatus'], name='IX_Hold_target_st')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('holdStatus', 'ACTIVE')), fields=('tenantId', 'holdScope', 'targetId'), name='UQ_Hold_active_scope_target')],
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('meetingId', models.UUIDField(db_index=True)),
                ('roomRef', models.CharField(db_index=True, max_length=64)),
                ('capacity', models.IntegerField(default=500)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communicationMeetingRooms',
                'indexes': [models.Index(fields=['meetingId'], name='IX_Room_meeting')],
            },
        ),
        migrations.CreateModel(
            name='MeetingSessionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('meetingId', models.UUIDField(db_index=True)),
                ('roomId', models.UUIDField(db_index=True)),
                ('sequence', models.IntegerField(default=1)),
                ('sessionStatus', models.CharField(db_index=True, default='WAITING', max_length=12)),
                ('participantCount', models.IntegerField(default=0)),
                ('startedAt', models.DateTimeField(blank=True, null=True)),
                ('endedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'communicationMeetingSessions',
                'indexes': [models.Index(fields=['meetingId', 'sequence'], name='IX_Sess_m_seq')],
                'constraints': [models.UniqueConstraint(fields=('meetingId', 'sequence'), name='UQ_Sess_meeting_seq')],
            },
        ),
        migrations.CreateModel(
            name='MeetingSummaryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('meetingId', models.UUIDField(db_index=True)),
                ('transcriptId', models.UUIDField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('keyPoints', models.JSONField(default=list)),
                ('decisions', models.JSONField(default=list)),
                ('actionItems', models.JSONField(default=list)),
                ('risks', models.JSONField(default=list)),
                ('topics', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('modelReference', models.CharField(blank=True, default='', max_length=120)),
                ('humanReviewStatus', models.CharField(db_index=True, default='PENDING', max_length=12)),
                ('reviewedBy', models.UUIDField(blank=True, null=True)),
                ('generatedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'communicationMeetingSummaries',
                'indexes': [models.Index(fields=['meetingId'], name='IX_Sum_meeting')],
            },
        ),
        migrations.CreateModel(
            name='MessageDeliveryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('messageId', models.UUIDField(db_index=True)),
                ('recipientId', models.UUIDField(db_index=True)),
                ('deliveryState', models.CharField(default='SENT', max_length=12)),
                ('failedReason', models.CharField(blank=True, default='', max_length=300)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'communicationMessageDeliveries',
                'indexes': [models.Index(fields=['messageId', 'recipientId'], name='IX_Deliv_mr')],
                'constraints': [models.UniqueConstraint(fields=('messageId', 'recipientId'), name='UQ_Deliv_pair')],
            },
        ),
        migrations.CreateModel(
            name='MessageReportModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('messageId', models.UUIDField(db_index=True)),
                ('reportedById', models.UUIDField(db_index=True)),
                ('reason', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('reportStatus', models.CharField(db_index=True, default='OPEN', max_length=14)),
                ('reviewedById', models.UUIDField(blank=True, null=True)),
                ('reviewedAt', models.DateTimeField(blank=True, null=True)),
                ('resolutionNote', models.CharField(blank=True, default='', max_length=500)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communicationMessageReports',
                'indexes': [models.Index(fields=['tenantId', 'reportStatus'], name='IX_Report_st'), models.Index(fields=['messageId'], name='IX_Report_msg')],
            },
        ),
        migrations.CreateModel(
            name='OfficialMessageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('officialKind', models.CharField(max_length=16)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('authorId', models.UUIDField(db_index=True)),
                ('officialStatus', models.CharField(db_index=True, default='DRAFT', max_length=14)),
                ('recipientIds', models.JSONField(default=list)),
                ('acknowledgedBy', models.JSONField(default=list)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communicationOfficialMessages',
                'indexes': [models.Index(fields=['tenantId', 'officialStatus'], name='IX_Official_st')],
            },
        ),
        migrations.CreateModel(
            name='ScreenShareSessionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('meetingId', models.UUIDField(db_index=True)),
                ('sessionId', models.UUIDField(blank=True, null=True)),
                ('sharerId', models.UUIDField(db_index=True)),
                ('shareKind', models.CharField(max_length=12)),
                ('shareStatus', models.CharField(default='ACTIVE', max_length=12)),
                ('startedAt', models.DateTimeField(blank=True, null=True)),
                ('endedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'communicationScreenShareSessions',
                'indexes': [models.Index(fields=['meetingId', 'shareStatus'], name='IX_SS_meet_st')],
            },
        ),
    ]
