"""Communication domain constants (Phase 08 §3–§7, §11–§16).

Plain string constants + validated value objects, framework-free — the
domain must stay independent of Channels/Redis/WebRTC/SQL (§2, §37).
"""

from __future__ import annotations

from apps.sharedKernel.domain.errors import ValidationFailedError
from apps.sharedKernel.domain.valueObjects import ValueObject

# §3.1 conversation types
CONVERSATION_DIRECT = "DIRECT"
CONVERSATION_GROUP = "GROUP"
CONVERSATION_CHANNEL = "CHANNEL"
CONVERSATION_MEETING = "MEETING"
CONVERSATION_TYPES = (
    CONVERSATION_DIRECT,
    CONVERSATION_GROUP,
    CONVERSATION_CHANNEL,
    CONVERSATION_MEETING,
)

# §4 channel visibility
CHANNEL_PUBLIC = "PUBLIC"
CHANNEL_PRIVATE = "PRIVATE"
CHANNEL_RESTRICTED = "RESTRICTED"
CHANNEL_VISIBILITIES = (CHANNEL_PUBLIC, CHANNEL_PRIVATE, CHANNEL_RESTRICTED)

# §3.2 participant roles
PARTICIPANT_OWNER = "OWNER"
PARTICIPANT_ADMIN = "ADMIN"
PARTICIPANT_MODERATOR = "MODERATOR"
PARTICIPANT_MEMBER = "MEMBER"
PARTICIPANT_GUEST = "GUEST"
PARTICIPANT_ROLES = (
    PARTICIPANT_OWNER,
    PARTICIPANT_ADMIN,
    PARTICIPANT_MODERATOR,
    PARTICIPANT_MEMBER,
    PARTICIPANT_GUEST,
)
#: Roles allowed to manage participants and pins (§4/§6).
MODERATING_ROLES = (PARTICIPANT_OWNER, PARTICIPANT_ADMIN, PARTICIPANT_MODERATOR)

# §3.3 message types
MESSAGE_TEXT = "TEXT"
MESSAGE_FILE = "FILE"
MESSAGE_IMAGE = "IMAGE"
MESSAGE_AUDIO = "AUDIO"
MESSAGE_VIDEO = "VIDEO"
MESSAGE_SYSTEM = "SYSTEM"
MESSAGE_MEETING = "MEETING"
MESSAGE_LOCATION = "LOCATION"
MESSAGE_LINK = "LINK"
MESSAGE_AI_GENERATED = "AI_GENERATED"
MESSAGE_TYPES = (
    MESSAGE_TEXT,
    MESSAGE_FILE,
    MESSAGE_IMAGE,
    MESSAGE_AUDIO,
    MESSAGE_VIDEO,
    MESSAGE_SYSTEM,
    MESSAGE_MEETING,
    MESSAGE_LOCATION,
    MESSAGE_LINK,
    MESSAGE_AI_GENERATED,
)

# §3.6 / §32 read states (monotonic)
READ_SENT = "SENT"
READ_DELIVERED = "DELIVERED"
READ_READ = "READ"
READ_STATES = (READ_SENT, READ_DELIVERED, READ_READ)
READ_STATE_RANK = {READ_SENT: 0, READ_DELIVERED: 1, READ_READ: 2}

# §7 presence states
PRESENCE_ONLINE = "ONLINE"
PRESENCE_OFFLINE = "OFFLINE"
PRESENCE_AWAY = "AWAY"
PRESENCE_BUSY = "BUSY"
PRESENCE_DO_NOT_DISTURB = "DO_NOT_DISTURB"
PRESENCE_IN_MEETING = "IN_MEETING"
# Phase 10 §17 — privacy state: the user appears OFFLINE to others while the
# connection is still tracked for delivery.
PRESENCE_INVISIBLE = "INVISIBLE"
PRESENCE_STATES = (
    PRESENCE_ONLINE,
    PRESENCE_OFFLINE,
    PRESENCE_AWAY,
    PRESENCE_BUSY,
    PRESENCE_DO_NOT_DISTURB,
    PRESENCE_IN_MEETING,
    PRESENCE_INVISIBLE,
)

# §11 signaling protocol
SIGNALING_PROTOCOL_VERSION = "communication.signal.v1"
REALTIME_PROTOCOL_VERSION = "communication.rt.v1"
SIGNAL_KINDS = (
    "OFFER",
    "ANSWER",
    "ICE_CANDIDATE",
    "CALL_INVITE",
    "CALL_ACCEPT",
    "CALL_REJECT",
    "CALL_END",
    "MEDIA_STATE_CHANGE",
)

# §10/§12 calls
CALL_AUDIO = "AUDIO"
CALL_VIDEO = "VIDEO"
CALL_SCREEN_SHARE = "SCREEN_SHARE"
CALL_MEDIA = (CALL_AUDIO, CALL_VIDEO, CALL_SCREEN_SHARE)

CALL_RINGING = "RINGING"
CALL_ACTIVE = "ACTIVE"
CALL_ENDED = "ENDED"
CALL_REJECTED = "REJECTED"
CALL_MISSED = "MISSED"
CALL_CANCELLED = "CANCELLED"
CALL_STATES = (
    CALL_RINGING,
    CALL_ACTIVE,
    CALL_ENDED,
    CALL_REJECTED,
    CALL_MISSED,
    CALL_CANCELLED,
)

# §13 meetings
MEETING_SCHEDULED = "SCHEDULED"
MEETING_WAITING = "WAITING"
MEETING_LIVE = "LIVE"
MEETING_ENDED = "ENDED"
MEETING_CANCELLED = "CANCELLED"
MEETING_STATES = (
    MEETING_SCHEDULED,
    MEETING_WAITING,
    MEETING_LIVE,
    MEETING_ENDED,
    MEETING_CANCELLED,
)
MEETING_TRANSITIONS: dict[str, tuple[str, ...]] = {
    MEETING_SCHEDULED: (MEETING_WAITING, MEETING_LIVE, MEETING_CANCELLED),
    MEETING_WAITING: (MEETING_LIVE, MEETING_CANCELLED),
    MEETING_LIVE: (MEETING_ENDED,),
    MEETING_ENDED: (),
    MEETING_CANCELLED: (),
}
MEETING_INVITED = "INVITED"
MEETING_ACCEPTED = "ACCEPTED"
MEETING_DECLINED = "DECLINED"
MEETING_JOINED = "JOINED"
MEETING_LEFT = "LEFT"
MEETING_RSVP_STATES = (
    MEETING_INVITED,
    MEETING_ACCEPTED,
    MEETING_DECLINED,
    MEETING_JOINED,
    MEETING_LEFT,
)

# §15 recording lifecycle
RECORDING_REQUESTED = "REQUESTED"
RECORDING_STARTED = "STARTED"
RECORDING_STOPPED = "STOPPED"
RECORDING_PROCESSING = "PROCESSING"
RECORDING_AVAILABLE = "AVAILABLE"
RECORDING_FAILED = "FAILED"
RECORDING_STATES = (
    RECORDING_REQUESTED,
    RECORDING_STARTED,
    RECORDING_STOPPED,
    RECORDING_PROCESSING,
    RECORDING_AVAILABLE,
    RECORDING_FAILED,
)
RECORDING_TRANSITIONS: dict[str, tuple[str, ...]] = {
    RECORDING_REQUESTED: (RECORDING_STARTED, RECORDING_FAILED),
    RECORDING_STARTED: (RECORDING_STOPPED, RECORDING_FAILED),
    RECORDING_STOPPED: (RECORDING_PROCESSING, RECORDING_FAILED),
    RECORDING_PROCESSING: (RECORDING_AVAILABLE, RECORDING_FAILED),
    RECORDING_AVAILABLE: (),
    RECORDING_FAILED: (),
}

# §16 official letters (dedicated model — NOT a message type)
LETTER_DRAFT = "DRAFT"
LETTER_IN_REVIEW = "IN_REVIEW"
LETTER_APPROVED = "APPROVED"
LETTER_SIGNED = "SIGNED"
LETTER_DISPATCHED = "DISPATCHED"
LETTER_RECEIVED = "RECEIVED"
LETTER_REJECTED = "REJECTED"
LETTER_STATES = (
    LETTER_DRAFT,
    LETTER_IN_REVIEW,
    LETTER_APPROVED,
    LETTER_SIGNED,
    LETTER_DISPATCHED,
    LETTER_RECEIVED,
    LETTER_REJECTED,
)
LETTER_TRANSITIONS: dict[str, tuple[str, ...]] = {
    LETTER_DRAFT: (LETTER_IN_REVIEW, LETTER_APPROVED),
    LETTER_IN_REVIEW: (LETTER_APPROVED, LETTER_REJECTED),
    LETTER_APPROVED: (LETTER_SIGNED, LETTER_REJECTED),
    LETTER_SIGNED: (LETTER_DISPATCHED,),
    LETTER_DISPATCHED: (LETTER_RECEIVED,),
    LETTER_RECEIVED: (),
    LETTER_REJECTED: (),
}

# §3.2 notification levels
NOTIFY_ALL = "ALL"
NOTIFY_MENTIONS = "MENTIONS"
NOTIFY_NONE = "NONE"
NOTIFICATION_LEVELS = (NOTIFY_ALL, NOTIFY_MENTIONS, NOTIFY_NONE)

#: §33 message edit window (minutes) — sender-editable period, configurable
#: per deployment via settings COMMUNICATION_POLICY.
DEFAULT_EDIT_WINDOW_MINUTES = 15


class ConversationType(ValueObject):
    """Validated conversation type (§3.1)."""

    def __init__(self, value: str) -> None:
        if value not in CONVERSATION_TYPES:
            raise ValidationFailedError(
                "Unknown conversation type.",
                fieldErrors={"type": value},
            )
        self.value = value

    def __str__(self) -> str:
        return self.value


class ChannelVisibility(ValueObject):
    """Validated channel visibility (§4)."""

    def __init__(self, value: str) -> None:
        if value not in CHANNEL_VISIBILITIES:
            raise ValidationFailedError(
                "Unknown channel visibility.",
                fieldErrors={"visibility": value},
            )
        self.value = value

    def __str__(self) -> str:
        return self.value


class PresenceStatus(ValueObject):
    """Validated presence state (§7)."""

    def __init__(self, value: str) -> None:
        if value not in PRESENCE_STATES:
            raise ValidationFailedError(
                "Unknown presence state.",
                fieldErrors={"presence": value},
            )
        self.value = value

    def __str__(self) -> str:
        return self.value
