# Generated by Django 6.1 on 2026-09-05 08:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelmodel',
            name='inputCostPer1k',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='aimodelmodel',
            name='outputCostPer1k',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name='AIQuotaPolicyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(max_length=20)),
                ('scopeReference', models.CharField(blank=True, max_length=160)),
                ('dimension', models.CharField(max_length=20)),
                ('window', models.CharField(max_length=20)),
                ('limitValue', models.DecimalField(decimal_places=8, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'aiQuotaPolicies',
                'unique_together': {('tenantId', 'scope', 'scopeReference', 'dimension', 'window')},
            },
        ),
        migrations.CreateModel(
            name='AIQuotaCounterModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('windowStart', models.DateTimeField(db_index=True)),
                ('consumedRequests', models.BigIntegerField(default=0)),
                ('consumedInputTokens', models.BigIntegerField(default=0)),
                ('consumedOutputTokens', models.BigIntegerField(default=0)),
                ('consumedCost', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counters', to='ai.aiquotapolicymodel')),
            ],
            options={
                'db_table': 'aiQuotaCounters',
                'indexes': [models.Index(fields=['tenantId', 'windowStart'], name='aiQuotaCoun_tenantI_2761a7_idx')],
                'unique_together': {('policy', 'windowStart')},
            },
        ),
        migrations.CreateModel(
            name='AIUsageAttemptModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('operationId', models.UUIDField(null=True)),
                ('attemptNumber', models.PositiveIntegerField(default=1)),
                ('providerCode', models.CharField(max_length=100)),
                ('modelCode', models.CharField(max_length=160)),
                ('capabilityCode', models.CharField(blank=True, max_length=100)),
                ('requestedBy', models.UUIDField(null=True)),
                ('inputTokens', models.PositiveIntegerField(default=0)),
                ('outputTokens', models.PositiveIntegerField(default=0)),
                ('totalTokens', models.PositiveIntegerField(default=0)),
                ('estimatedCost', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('queueTimeMs', models.PositiveIntegerField(default=0)),
                ('contextBuildTimeMs', models.PositiveIntegerField(default=0)),
                ('providerTimeMs', models.PositiveIntegerField(default=0)),
                ('validationTimeMs', models.PositiveIntegerField(default=0)),
                ('totalTimeMs', models.PositiveIntegerField(default=0)),
                ('outcome', models.CharField(default='SUCCEEDED', max_length=20)),
                ('errorCode', models.CharField(blank=True, max_length=80)),
                ('idempotencyKey', models.CharField(blank=True, db_index=True, max_length=160)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('correlationId', models.CharField(blank=True, max_length=128)),
                ('traceId', models.CharField(blank=True, max_length=128)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai.aimodelmodel')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai.aiprovidermodel')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usageAttempts', to='ai.airequestmodel')),
            ],
            options={
                'db_table': 'aiUsageAttempts',
                'indexes': [models.Index(fields=['tenantId', 'createdAt'], name='aiUsageAtte_tenantI_7eeb61_idx'), models.Index(fields=['tenantId', 'idempotencyKey'], name='aiUsageAtte_tenantI_60013c_idx')],
                'unique_together': {('tenantId', 'request', 'attemptNumber')},
            },
        ),
    ]
