# Generated by Django 6.1 on 2026-09-05 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_usageMetering'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAuditTrailModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('occurredAt', models.DateTimeField()),
                ('actorType', models.CharField(default='SYSTEM', max_length=20)),
                ('actorId', models.UUIDField(null=True)),
                ('action', models.CharField(max_length=40)),
                ('requestId', models.UUIDField(null=True)),
                ('attemptId', models.UUIDField(null=True)),
                ('policyId', models.UUIDField(null=True)),
                ('capabilityCode', models.CharField(blank=True, max_length=100)),
                ('providerCode', models.CharField(blank=True, max_length=100)),
                ('modelCode', models.CharField(blank=True, max_length=160)),
                ('promptVersion', models.CharField(blank=True, max_length=80)),
                ('classification', models.CharField(default='INTERNAL', max_length=20)),
                ('outcome', models.CharField(default='RECORDED', max_length=20)),
                ('errorCode', models.CharField(blank=True, max_length=80)),
                ('correlationId', models.CharField(blank=True, max_length=128)),
                ('traceId', models.CharField(blank=True, max_length=128)),
                ('contextSources', models.JSONField(default=list)),
                ('detail', models.JSONField(default=dict)),
                ('prevHash', models.CharField(blank=True, max_length=64)),
                ('hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'aiAuditTrail',
                'indexes': [models.Index(fields=['tenantId', 'occurredAt'], name='aiAuditTrai_tenantI_7d048f_idx'), models.Index(fields=['tenantId', 'action'], name='aiAuditTrai_tenantI_cb015b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIGovernancePolicyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='default', max_length=160)),
                ('allowedProviders', models.JSONField(default=list)),
                ('allowedModels', models.JSONField(default=list)),
                ('disabledCapabilities', models.JSONField(default=list)),
                ('allowRestrictedToExternal', models.BooleanField(default=False)),
                ('maxCostPerDay', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'aiGovernancePolicies',
                'constraints': [models.UniqueConstraint(fields=('tenantId',), name='unique_governance_policy_per_tenant')],
            },
        ),
    ]
