# Generated by Django 6.1 on 2026-09-05 09:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0003_auditGovernance"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIJobModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=40)),
                ("requestId", models.UUIDField(null=True)),
                ("payload", models.JSONField(default=dict)),
                ("idempotencyKey", models.CharField(blank=True, max_length=128)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("priority", models.PositiveIntegerField(default=5)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("maxAttempts", models.PositiveIntegerField(default=3)),
                ("runAt", models.DateTimeField()),
                ("claimedBy", models.CharField(blank=True, max_length=128)),
                ("leaseExpiresAt", models.DateTimeField(null=True)),
                ("resultSummary", models.JSONField(default=dict)),
                ("errorCode", models.CharField(blank=True, max_length=80)),
                ("correlationId", models.CharField(blank=True, max_length=128)),
                ("traceId", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "db_table": "aiJobs",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "status", "runAt"], name="aiJobs_tenantI_e6956b_idx"
                    ),
                    models.Index(
                        fields=["tenantId", "createdAt"], name="aiJobs_tenantI_617055_idx"
                    ),
                ],
                "unique_together": {("tenantId", "idempotencyKey")},
            },
        ),
    ]
