# Generated by Django 6.1 on 2026-09-05 12:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0004_queueWorker"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIStoredEmbeddingModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("spaceCode", models.CharField(max_length=80)),
                ("sourceType", models.CharField(max_length=40)),
                ("sourceId", models.CharField(max_length=160)),
                ("chunkId", models.UUIDField(null=True)),
                ("modelId", models.UUIDField(null=True)),
                ("providerCode", models.CharField(blank=True, max_length=80)),
                ("dimensions", models.PositiveIntegerField()),
                ("vector", models.JSONField(default=list)),
                ("contentHash", models.CharField(max_length=64)),
                ("tokenCount", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "aiEmbeddingVectors",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "spaceCode", "sourceType", "sourceId"],
                        name="aiEmbedding_tenantI_dc16b2_idx",
                    ),
                    models.Index(
                        fields=["tenantId", "spaceCode", "createdAt"],
                        name="aiEmbedding_tenantI_94f7a3_idx",
                    ),
                ],
                "unique_together": {("tenantId", "spaceCode", "contentHash")},
            },
        ),
        migrations.CreateModel(
            name="AIVectorSpaceModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("modelCode", models.CharField(max_length=120)),
                ("modelVersion", models.CharField(blank=True, max_length=80)),
                ("modelId", models.UUIDField(null=True)),
                ("providerCode", models.CharField(blank=True, max_length=80)),
                ("dimensions", models.PositiveIntegerField()),
                ("metric", models.CharField(default="COSINE", max_length=20)),
                ("normalization", models.CharField(default="L2", max_length=10)),
                ("description", models.TextField(blank=True)),
                ("isActive", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "aiVectorSpaces",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "isActive"], name="aiVectorSpa_tenantI_e4aaaf_idx"
                    )
                ],
                "unique_together": {("tenantId", "code")},
            },
        ),
    ]
