# Generated by Django 6.1 on 2026-09-05 12:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0005_embeddingFoundation"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIKnowledgeSourceModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("sourceDomain", models.CharField(max_length=40)),
                ("sourceEntityType", models.CharField(max_length=100)),
                ("sourceEntityId", models.CharField(max_length=160)),
                ("title", models.CharField(max_length=300)),
                ("checksum", models.CharField(max_length=64)),
                ("classification", models.CharField(default="INTERNAL", max_length=30)),
                ("status", models.CharField(default="PENDING", max_length=30)),
                ("spaceCode", models.CharField(blank=True, max_length=80)),
                ("policySignature", models.CharField(blank=True, max_length=120)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("chunkCount", models.PositiveIntegerField(default=0)),
                ("tokenCount", models.PositiveIntegerField(default=0)),
                ("errorCode", models.CharField(blank=True, max_length=80)),
                ("lastIndexedAt", models.DateTimeField(null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "aiKnowledgeSources",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "status", "updatedAt"],
                        name="aiKnowledge_tenantI_2638a4_idx",
                    ),
                    models.Index(
                        fields=["tenantId", "sourceDomain"], name="aiKnowledge_tenantI_836b5a_idx"
                    ),
                ],
                "unique_together": {
                    ("tenantId", "sourceDomain", "sourceEntityType", "sourceEntityId")
                },
            },
        ),
        migrations.CreateModel(
            name="AIKnowledgeChunkRecordModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("ordinal", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("checksum", models.CharField(max_length=64)),
                ("tokenCount", models.PositiveIntegerField(default=0)),
                ("startOffset", models.PositiveIntegerField(default=0)),
                ("endOffset", models.PositiveIntegerField(default=0)),
                ("classification", models.CharField(default="INTERNAL", max_length=30)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunkRecords",
                        to="ai.aiknowledgesourcemodel",
                    ),
                ),
            ],
            options={
                "db_table": "aiKnowledgeChunkRecords",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "source", "ordinal"],
                        name="aiKnowledge_tenantI_b52dc8_idx",
                    ),
                    models.Index(
                        fields=["tenantId", "checksum"], name="aiKnowledge_tenantI_2afb3d_idx"
                    ),
                ],
            },
        ),
    ]
