# Generated by Django 6.1 on 2026-09-06 06:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0006_knowledgeIngestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIMemoryEntryModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("scope", models.CharField(max_length=40)),
                ("memoryKey", models.CharField(max_length=160)),
                ("kind", models.CharField(default="FACT", max_length=30)),
                ("userId", models.UUIDField(null=True)),
                ("ownerKey", models.CharField(default="tenant", max_length=64)),
                ("conversationId", models.CharField(blank=True, max_length=160)),
                ("classification", models.CharField(default="INTERNAL", max_length=30)),
                ("value", models.JSONField(default=dict)),
                ("checksum", models.CharField(max_length=64)),
                ("sizeBytes", models.PositiveIntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=1)),
                ("isActive", models.BooleanField(default=True)),
                ("expiresAt", models.DateTimeField(null=True)),
                ("supersededAt", models.DateTimeField(null=True)),
                ("sourceReference", models.CharField(blank=True, max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "aiMemoryEntries",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "scope", "memoryKey", "isActive"],
                        name="aiMemoryEnt_tenantI_dab3d1_idx",
                    ),
                    models.Index(
                        fields=["tenantId", "isActive", "createdAt"],
                        name="aiMemoryEnt_tenantI_d4e61a_idx",
                    ),
                    models.Index(
                        fields=["tenantId", "conversationId"], name="aiMemoryEnt_tenantI_31c65a_idx"
                    ),
                ],
                "unique_together": {("tenantId", "scope", "memoryKey", "ownerKey", "version")},
            },
        ),
    ]
