# Generated by Django 6.1 on 2026-09-06 06:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0007_memoryPlatform"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIEvaluationCaseModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("suiteCode", models.CharField(max_length=80)),
                ("caseCode", models.CharField(max_length=80)),
                ("question", models.TextField()),
                ("expectedTerms", models.JSONField(blank=True, default=list)),
                ("forbiddenTerms", models.JSONField(blank=True, default=list)),
                ("expectedSchema", models.JSONField(blank=True, default=dict)),
                ("minimumCitations", models.PositiveIntegerField(default=0)),
                ("latencyBudgetMs", models.PositiveIntegerField(default=0)),
                ("costBudget", models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ("spaceCode", models.CharField(blank=True, max_length=80)),
                ("isActive", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "aiEvaluationCases",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "suiteCode", "isActive"],
                        name="aiEvaluatio_tenantI_3c4905_idx",
                    )
                ],
                "unique_together": {("tenantId", "suiteCode", "caseCode")},
            },
        ),
        migrations.CreateModel(
            name="AIEvaluationRunModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("suiteCode", models.CharField(max_length=80)),
                ("method", models.CharField(default="AUTOMATIC", max_length=20)),
                ("criteriaSignature", models.CharField(blank=True, max_length=500)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("verdict", models.CharField(default="PASS", max_length=10)),
                ("caseCount", models.PositiveIntegerField(default=0)),
                ("passedCount", models.PositiveIntegerField(default=0)),
                ("warnedCount", models.PositiveIntegerField(default=0)),
                ("failedCount", models.PositiveIntegerField(default=0)),
                ("overallScore", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ("baselineRunId", models.UUIDField(null=True)),
                ("triggeredBy", models.UUIDField(null=True)),
                ("errorCode", models.CharField(blank=True, max_length=80)),
                ("startedAt", models.DateTimeField(null=True)),
                ("completedAt", models.DateTimeField(null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "aiEvaluationRuns",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "suiteCode", "createdAt"],
                        name="aiEvaluatio_tenantI_6a2560_idx",
                    ),
                    models.Index(
                        fields=["tenantId", "status"], name="aiEvaluatio_tenantI_efc4ba_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIEvaluationResultModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("caseCode", models.CharField(max_length=80)),
                ("verdict", models.CharField(default="PASS", max_length=10)),
                ("score", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ("scores", models.JSONField(default=list)),
                ("latencyMs", models.PositiveIntegerField(default=0)),
                ("totalTokens", models.PositiveIntegerField(default=0)),
                ("cost", models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ("citationCount", models.PositiveIntegerField(default=0)),
                ("answerFingerprint", models.CharField(blank=True, max_length=64)),
                ("requestId", models.UUIDField(null=True)),
                ("errorCode", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="ai.aievaluationrunmodel",
                    ),
                ),
            ],
            options={
                "db_table": "aiEvaluationResults",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "caseCode", "createdAt"],
                        name="aiEvaluatio_tenantI_ffd162_idx",
                    )
                ],
                "unique_together": {("run", "caseCode")},
            },
        ),
    ]
