# Generated by Django 6.1 on 2026-09-06 06:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0008_evaluationPlatform"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIFeedbackEntryModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("requestId", models.UUIDField(db_index=True)),
                ("responseId", models.UUIDField(null=True)),
                ("userId", models.UUIDField(null=True)),
                ("kind", models.CharField(default="RATING", max_length=20)),
                ("rating", models.PositiveSmallIntegerField(null=True)),
                ("sentiment", models.CharField(default="NEUTRAL", max_length=20)),
                ("reason", models.CharField(blank=True, max_length=30)),
                ("comment", models.TextField(blank=True)),
                ("correction", models.TextField(blank=True)),
                ("question", models.TextField(blank=True)),
                ("modelCode", models.CharField(blank=True, max_length=160)),
                ("promptVersion", models.CharField(blank=True, max_length=80)),
                ("capabilityCode", models.CharField(blank=True, max_length=100)),
                ("suiteCode", models.CharField(blank=True, max_length=80)),
                ("status", models.CharField(default="NEW", max_length=20)),
                ("promotedCaseCode", models.CharField(blank=True, max_length=80)),
                ("rejectionReason", models.CharField(blank=True, max_length=500)),
                ("triagedBy", models.UUIDField(null=True)),
                ("triagedAt", models.DateTimeField(null=True)),
                ("fingerprint", models.CharField(max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "aiFeedbackEntries",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "status", "createdAt"],
                        name="aiFeedbackE_tenantI_d66df8_idx",
                    ),
                    models.Index(
                        fields=["tenantId", "sentiment", "createdAt"],
                        name="aiFeedbackE_tenantI_e05af2_idx",
                    ),
                    models.Index(
                        fields=["tenantId", "modelCode"], name="aiFeedbackE_tenantI_01b011_idx"
                    ),
                ],
                "unique_together": {("tenantId", "fingerprint")},
            },
        ),
    ]
