# Generated by Django 6.1 on 2026-09-06 07:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0009_feedbackPlatform"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAlertEventModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("ruleCode", models.CharField(max_length=80)),
                ("metric", models.CharField(max_length=80)),
                ("severity", models.CharField(default="WARNING", max_length=20)),
                ("state", models.CharField(default="FIRING", max_length=20)),
                ("observedValue", models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ("threshold", models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("firedAt", models.DateTimeField()),
                ("resolvedAt", models.DateTimeField(null=True)),
                ("acknowledgedAt", models.DateTimeField(null=True)),
                ("acknowledgedBy", models.UUIDField(null=True)),
                ("snapshotId", models.UUIDField(null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "aiAlertEvents",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "state", "firedAt"],
                        name="aiAlertEven_tenantI_34be60_idx",
                    ),
                    models.Index(
                        fields=["tenantId", "ruleCode", "firedAt"],
                        name="aiAlertEven_tenantI_e6a641_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIMetricSnapshotModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("windowStart", models.DateTimeField()),
                ("windowEnd", models.DateTimeField()),
                ("metrics", models.JSONField(default=dict)),
                ("labels", models.JSONField(blank=True, default=dict)),
                ("sampleCount", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "aiMetricSnapshots",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "windowEnd"], name="aiMetricSna_tenantI_eb5f23_idx"
                    ),
                    models.Index(
                        fields=["tenantId", "createdAt"], name="aiMetricSna_tenantI_b0daf2_idx"
                    ),
                ],
            },
        ),
    ]
