# Generated by Django 6.1 on 2026-09-06 07:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0010_observabilityPlatform"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIToolApprovalModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("toolCode", models.CharField(max_length=80)),
                ("toolVersion", models.PositiveIntegerField(default=1)),
                ("argumentFingerprint", models.CharField(max_length=64)),
                ("mode", models.CharField(default="HUMAN_REQUIRED", max_length=20)),
                ("decision", models.CharField(default="PENDING", max_length=20)),
                ("requiredApprovals", models.PositiveSmallIntegerField(default=1)),
                ("approvals", models.JSONField(default=list)),
                ("requestedBy", models.UUIDField(null=True)),
                ("invocationId", models.UUIDField(null=True)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("expiresAt", models.DateTimeField(null=True)),
                ("decidedAt", models.DateTimeField(null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "aiToolApprovals",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "toolCode", "argumentFingerprint"],
                        name="aiToolAppro_tenantI_f71335_idx",
                    ),
                    models.Index(
                        fields=["tenantId", "decision", "createdAt"],
                        name="aiToolAppro_tenantI_580199_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIToolDefinitionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField()),
                ("effect", models.CharField(default="READ_ONLY", max_length=20)),
                ("riskLevel", models.CharField(default="LOW", max_length=20)),
                ("inputSchema", models.JSONField(blank=True, default=dict)),
                ("outputSchema", models.JSONField(blank=True, default=dict)),
                ("requiredPermission", models.CharField(blank=True, max_length=100)),
                ("declaredApprovalMode", models.CharField(blank=True, max_length=20)),
                ("timeoutSeconds", models.PositiveIntegerField(default=30)),
                ("maxCallsPerRequest", models.PositiveIntegerField(default=5)),
                ("status", models.CharField(default="DRAFT", max_length=20)),
                ("approvedBy", models.UUIDField(null=True)),
                ("approvedAt", models.DateTimeField(null=True)),
                ("retiredAt", models.DateTimeField(null=True)),
                ("rejectionReason", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "aiToolDefinitions",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "code", "status"], name="aiToolDefin_tenantI_3cf010_idx"
                    ),
                    models.Index(
                        fields=["tenantId", "status"], name="aiToolDefin_tenantI_079a28_idx"
                    ),
                ],
                "unique_together": {("tenantId", "code", "version")},
            },
        ),
        migrations.CreateModel(
            name="AIToolInvocationModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("toolCode", models.CharField(max_length=80)),
                ("toolVersion", models.PositiveIntegerField(default=1)),
                ("toolId", models.UUIDField(null=True)),
                ("requestId", models.UUIDField(db_index=True, null=True)),
                ("actorId", models.UUIDField(null=True)),
                ("approvalId", models.UUIDField(null=True)),
                ("arguments", models.JSONField(default=dict)),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("errorCode", models.CharField(blank=True, max_length=80)),
                ("startedAt", models.DateTimeField(null=True)),
                ("completedAt", models.DateTimeField(null=True)),
                ("latencyMs", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "aiToolInvocations",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "toolCode", "createdAt"],
                        name="aiToolInvoc_tenantI_c4b8a5_idx",
                    ),
                    models.Index(
                        fields=["tenantId", "status", "createdAt"],
                        name="aiToolInvoc_tenantI_a05ae8_idx",
                    ),
                ],
            },
        ),
    ]
