# Generated by Django 6.1 on 2026-09-06 08:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0011_toolPlatform"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAgentApprovalModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("agentCode", models.CharField(max_length=80)),
                ("agentVersion", models.PositiveIntegerField(default=1)),
                ("inputFingerprint", models.CharField(max_length=64)),
                ("mode", models.CharField(default="HUMAN_REQUIRED", max_length=20)),
                ("decision", models.CharField(default="PENDING", max_length=20)),
                ("requiredApprovals", models.PositiveSmallIntegerField(default=1)),
                ("approvals", models.JSONField(default=list)),
                ("requestedBy", models.UUIDField(null=True)),
                ("executionId", models.UUIDField(null=True)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("expiresAt", models.DateTimeField(null=True)),
                ("decidedAt", models.DateTimeField(null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "aiAgentApprovals",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "agentCode", "inputFingerprint"],
                        name="aiAgentAppr_tenantI_6410fa_idx",
                    ),
                    models.Index(
                        fields=["tenantId", "decision", "createdAt"],
                        name="aiAgentAppr_tenantI_4397d7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIAgentDefinitionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("instructions", models.TextField()),
                ("accessLevel", models.CharField(default="ADVISORY", max_length=20)),
                ("riskLevel", models.CharField(default="LOW", max_length=20)),
                ("capabilityCodes", models.JSONField(default=list)),
                ("toolCodes", models.JSONField(default=list)),
                ("outputSchema", models.JSONField(blank=True, default=dict)),
                ("contextPolicy", models.JSONField(blank=True, default=dict)),
                ("modelPolicy", models.JSONField(blank=True, default=dict)),
                ("permissionPolicy", models.JSONField(blank=True, default=dict)),
                ("executionPolicy", models.JSONField(blank=True, default=dict)),
                ("declaredApprovalMode", models.CharField(blank=True, max_length=20)),
                ("status", models.CharField(default="DRAFT", max_length=20)),
                ("approvedBy", models.UUIDField(null=True)),
                ("approvedAt", models.DateTimeField(null=True)),
                ("retiredAt", models.DateTimeField(null=True)),
                ("rejectionReason", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "aiAgentDefinitions",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "code", "status"], name="aiAgentDefi_tenantI_de68c4_idx"
                    ),
                    models.Index(
                        fields=["tenantId", "status"], name="aiAgentDefi_tenantI_f86efa_idx"
                    ),
                ],
                "unique_together": {("tenantId", "code", "version")},
            },
        ),
        migrations.CreateModel(
            name="AIAgentRunModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("agentId", models.UUIDField()),
                ("agentCode", models.CharField(max_length=80)),
                ("agentVersion", models.PositiveIntegerField(default=1)),
                ("requestedBy", models.UUIDField(null=True)),
                ("input", models.JSONField(default=dict)),
                ("inputFingerprint", models.CharField(db_index=True, max_length=64)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("answer", models.TextField(blank=True)),
                ("output", models.JSONField(blank=True, default=dict)),
                ("errorCode", models.CharField(blank=True, max_length=80)),
                ("approvalId", models.UUIDField(null=True)),
                ("startedAt", models.DateTimeField(null=True)),
                ("completedAt", models.DateTimeField(null=True)),
                ("latencyMs", models.PositiveIntegerField(default=0)),
                ("modelCallCount", models.PositiveIntegerField(default=0)),
                ("toolCallCount", models.PositiveIntegerField(default=0)),
                ("inputTokens", models.PositiveIntegerField(default=0)),
                ("outputTokens", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "aiAgentRuns",
                "indexes": [
                    models.Index(
                        fields=["tenantId", "agentCode", "createdAt"],
                        name="aiAgentRuns_tenantI_03821a_idx",
                    ),
                    models.Index(
                        fields=["tenantId", "status", "createdAt"],
                        name="aiAgentRuns_tenantI_86f02d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIAgentStepModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("runId", models.UUIDField(db_index=True)),
                ("ordinal", models.PositiveIntegerField()),
                ("kind", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=20)),
                ("toolCode", models.CharField(blank=True, max_length=80)),
                ("toolVersion", models.PositiveIntegerField(default=0)),
                ("arguments", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("tokensIn", models.PositiveIntegerField(default=0)),
                ("tokensOut", models.PositiveIntegerField(default=0)),
                ("latencyMs", models.PositiveIntegerField(default=0)),
                ("errorCode", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "db_table": "aiAgentSteps",
                "indexes": [
                    models.Index(fields=["runId", "kind"], name="aiAgentStep_runId_f54229_idx"),
                    models.Index(
                        fields=["tenantId", "createdAt"], name="aiAgentStep_tenantI_133e6f_idx"
                    ),
                ],
                "unique_together": {("runId", "ordinal")},
            },
        ),
    ]
