# Generated by Django 6.1 on 2026-08-31 07:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_phase8_communication'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingCapabilityOverrideModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('meetingId', models.UUIDField(db_index=True)),
                ('userId', models.UUIDField(db_index=True)),
                ('capability', models.CharField(max_length=32)),
                ('granted', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communicationMeetingCapabilityOverrides',
                'indexes': [models.Index(fields=['meetingId', 'userId'], name='IX_Cap_m_user')],
                'constraints': [models.UniqueConstraint(fields=('meetingId', 'userId', 'capability'), name='UQ_Cap_meeting_user_cap')],
            },
        ),
        migrations.CreateModel(
            name='MeetingTranscriptModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('meetingId', models.UUIDField(db_index=True)),
                ('language', models.CharField(default='en-US', max_length=10)),
                ('transcriptStatus', models.CharField(db_index=True, default='PENDING', max_length=12)),
                ('contentReference', models.CharField(blank=True, default='', max_length=300)),
                ('segmentCount', models.IntegerField(default=0)),
                ('requestedBy', models.UUIDField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communicationMeetingTranscripts',
                'indexes': [models.Index(fields=['tenantId', 'meetingId'], name='IX_Tran_t_meeting'), models.Index(fields=['meetingId', 'transcriptStatus'], name='IX_Tran_m_status')],
            },
        ),
        migrations.CreateModel(
            name='MessageRevisionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('messageId', models.UUIDField(db_index=True)),
                ('conversationId', models.UUIDField(db_index=True)),
                ('revisionNumber', models.IntegerField()),
                ('previousBody', models.TextField(blank=True, default='')),
                ('newBody', models.TextField(blank=True, default='')),
                ('editedBy', models.UUIDField(db_index=True)),
                ('editedAt', models.DateTimeField(db_index=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communicationMessageRevisions',
                'indexes': [models.Index(fields=['messageId', 'revisionNumber'], name='IX_Rev_msg_seq'), models.Index(fields=['tenantId', 'messageId'], name='IX_Rev_t_msg')],
                'constraints': [models.UniqueConstraint(fields=('messageId', 'revisionNumber'), name='UQ_Revision_message_number')],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('transcriptId', models.UUIDField(db_index=True)),
                ('sequence', models.IntegerField()),
                ('speakerId', models.UUIDField(blank=True, db_index=True, null=True)),
                ('startTimeSeconds', models.FloatField()),
                ('endTimeSeconds', models.FloatField()),
                ('text', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communicationTranscriptSegments',
                'indexes': [models.Index(fields=['transcriptId', 'sequence'], name='IX_Seg_tran_seq')],
                'constraints': [models.UniqueConstraint(fields=('transcriptId', 'sequence'), name='UQ_Segment_transcript_seq')],
            },
        ),
        migrations.CreateModel(
            name='UserBlockModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('blockerId', models.UUIDField(db_index=True)),
                ('blockedUserId', models.UUIDField(db_index=True)),
                ('scopes', models.JSONField(default=list)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('blockStatus', models.CharField(db_index=True, default='ACTIVE', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('removedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'communicationUserBlocks',
                'indexes': [models.Index(fields=['tenantId', 'blockerId'], name='IX_Block_t_blocker'), models.Index(fields=['blockerId', 'blockedUserId', 'blockStatus'], name='IX_Block_pair_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('blockStatus', 'ACTIVE')), fields=('tenantId', 'blockerId', 'blockedUserId'), name='UQ_Block_active_pair')],
            },
        ),
    ]
