# Generated by Django 6.1 on 2026-08-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_phase10_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipantmodel',
            name='mutedUntil',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationparticipantmodel',
            name='notificationsEnabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meetingmodel',
            name='joinPolicy',
            field=models.CharField(blank=True, default='INVITE_ONLY', max_length=16),
        ),
        migrations.AddField(
            model_name='meetingmodel',
            name='meetingType',
            field=models.CharField(blank=True, default='SCHEDULED', max_length=16),
        ),
        migrations.AddField(
            model_name='meetingmodel',
            name='recordingPolicy',
            field=models.CharField(blank=True, default='ORGANIZER', max_length=16),
        ),
        migrations.AddField(
            model_name='meetingparticipantmodel',
            name='attendanceDuration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetingparticipantmodel',
            name='role',
            field=models.CharField(blank=True, default='PARTICIPANT', max_length=12),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='threadRootId',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        # NOTE: the auto-generated AlterField on channelprofilemodel.conversationId
        # is a pre-existing Phase-09 model/migration drift; it is intentionally
        # omitted here so the Phase 10 migration stays purely additive.
    ]
