# Generated by Django 6.1 on 2026-09-29 05:14

import uuid
from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoodsReceiptLineModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("receiptId", models.UUIDField(db_index=True)),
                ("purchaseOrderLineId", models.UUIDField(db_index=True)),
                ("partId", models.UUIDField(db_index=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("unitCost", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "rejectedQuantity",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=14),
                ),
            ],
            options={
                "db_table": "ProcurementGoodsReceiptLine",
            },
        ),
        migrations.CreateModel(
            name="ProcurementApprovalModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("documentType", models.CharField(max_length=20)),
                ("documentId", models.UUIDField(db_index=True)),
                ("step", models.PositiveIntegerField(default=1)),
                ("action", models.CharField(default="pending", max_length=20)),
                ("actorId", models.UUIDField(blank=True, null=True)),
                ("actorName", models.CharField(blank=True, default="", max_length=160)),
                ("comment", models.TextField(blank=True, default="")),
                ("actedAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ProcurementApproval",
                "ordering": ["step", "-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLineModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("purchaseOrderId", models.UUIDField(db_index=True)),
                ("partId", models.UUIDField(db_index=True)),
                ("partCode", models.CharField(max_length=60)),
                ("partName", models.CharField(max_length=240)),
                ("unit", models.CharField(default="عدد", max_length=30)),
                ("orderedQuantity", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "receivedQuantity",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=14),
                ),
                ("unitPrice", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "taxRate",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=6),
                ),
            ],
            options={
                "db_table": "ProcurementPurchaseOrderLine",
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequisitionLineModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("requisitionId", models.UUIDField(db_index=True)),
                ("partId", models.UUIDField(db_index=True)),
                ("partCode", models.CharField(max_length=60)),
                ("partName", models.CharField(max_length=240)),
                ("unit", models.CharField(default="عدد", max_length=30)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "estimatedUnitCost",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                ("preferredSupplierId", models.UUIDField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "db_table": "ProcurementRequisitionLine",
            },
        ),
        migrations.CreateModel(
            name="PurchaseReturnLineModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("returnId", models.UUIDField(db_index=True)),
                ("partId", models.UUIDField(db_index=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("unitCost", models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                "db_table": "ProcurementPurchaseReturnLine",
            },
        ),
        migrations.CreateModel(
            name="GoodsReceiptModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("posted", "posted"),
                            ("cancelled", "cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("purchaseOrderId", models.UUIDField(db_index=True)),
                ("receivedOn", models.DateField(auto_now_add=True)),
                ("receiverName", models.CharField(blank=True, default="", max_length=160)),
                ("deliveryNote", models.CharField(blank=True, default="", max_length=120)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "ProcurementGoodsReceipt",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenantId", "number"), name="uq_proc_receipt_number"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("submitted", "submitted"),
                            ("approved", "approved"),
                            ("partiallyReceived", "partiallyReceived"),
                            ("received", "received"),
                            ("cancelled", "cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("supplierId", models.UUIDField(db_index=True)),
                ("requisitionId", models.UUIDField(blank=True, db_index=True, null=True)),
                ("orderDate", models.DateField(auto_now_add=True)),
                ("expectedDate", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="IRR", max_length=8)),
                ("paymentTerms", models.CharField(blank=True, default="", max_length=120)),
                ("shippingAddress", models.TextField(blank=True, default="")),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "taxAmount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "ProcurementPurchaseOrder",
                "ordering": ["-createdAt"],
                "constraints": [
                    models.UniqueConstraint(fields=("tenantId", "number"), name="uq_proc_po_number")
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequisitionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("submitted", "submitted"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("cancelled", "cancelled"),
                            ("ordered", "ordered"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("requesterId", models.UUIDField(blank=True, null=True)),
                ("requesterName", models.CharField(blank=True, default="", max_length=160)),
                ("requestedOn", models.DateField(auto_now_add=True)),
                ("neededBy", models.DateField(blank=True, null=True)),
                ("priority", models.CharField(default="normal", max_length=20)),
                ("justification", models.TextField(blank=True, default="")),
                (
                    "totalEstimated",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
            ],
            options={
                "db_table": "ProcurementRequisition",
                "ordering": ["-createdAt"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenantId", "number"), name="uq_proc_requisition_number"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReturnModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("posted", "posted"),
                            ("cancelled", "cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("supplierId", models.UUIDField(db_index=True)),
                ("purchaseOrderId", models.UUIDField(blank=True, null=True)),
                ("returnedOn", models.DateField(auto_now_add=True)),
                ("reason", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "ProcurementPurchaseReturn",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenantId", "number"), name="uq_proc_return_number"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoiceModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("invoiceNumber", models.CharField(max_length=80)),
                ("supplierId", models.UUIDField(db_index=True)),
                ("purchaseOrderId", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("received", "received"),
                            ("approved", "approved"),
                            ("paid", "paid"),
                            ("disputed", "disputed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("invoiceDate", models.DateField(blank=True, null=True)),
                ("dueDate", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="IRR", max_length=8)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "taxAmount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "ProcurementSupplierInvoice",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenantId", "supplierId", "invoiceNumber"), name="uq_proc_invoice"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=240)),
                ("supplierType", models.CharField(default="vendor", max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("blocked", "Blocked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("contactName", models.CharField(blank=True, default="", max_length=160)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=60)),
                ("taxId", models.CharField(blank=True, default="", max_length=80)),
                ("address", models.TextField(blank=True, default="")),
                ("paymentTerms", models.CharField(blank=True, default="", max_length=120)),
                ("currency", models.CharField(default="IRR", max_length=8)),
                ("defaultLeadTimeDays", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "ProcurementSupplier",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenantId", "code"), name="uq_proc_supplier_code"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierPartModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("supplierId", models.UUIDField(db_index=True)),
                ("partId", models.UUIDField(db_index=True)),
                ("supplierSku", models.CharField(blank=True, default="", max_length=100)),
                (
                    "unitPrice",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "minimumOrderQty",
                    models.DecimalField(decimal_places=3, default=Decimal("1"), max_digits=14),
                ),
                ("leadTimeDays", models.PositiveIntegerField(default=0)),
                ("isPreferred", models.BooleanField(default=False)),
                ("lastQuotedAt", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "ProcurementSupplierPart",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenantId", "supplierId", "partId"), name="uq_proc_supplier_part"
                    )
                ],
            },
        ),
    ]
