"""Value objects for field operations: scan targets and sync operation kinds.

Keeping the vocabulary in the domain (not in the view) means the offline queue
on the phone, the REST layer and the tests all agree on one spelling, and an
unknown kind is a domain decision rather than a stray ``if`` in a serializer.
"""

from __future__ import annotations

from dataclasses import dataclass

# -- Scan targets --------------------------------------------------------------
SCAN_TARGET_DEVICE = "device"
SCAN_TARGET_WORK_ORDER = "workOrder"
SCAN_TARGET_SPARE_PART = "sparePart"
SCAN_TARGET_LOCATION = "location"

SCAN_TARGETS = (
    SCAN_TARGET_DEVICE,
    SCAN_TARGET_WORK_ORDER,
    SCAN_TARGET_SPARE_PART,
    SCAN_TARGET_LOCATION,
)

#: Symbologies the field app is expected to produce. QR carries a deep link;
#: the 1D codes carry a bare business code, which is why resolution has to
#: accept «just a code» as well as «a full URL» (BR-SCAN-002).
SCAN_SYMBOLOGIES = (
    "qr_code",
    "code_128",
    "code_39",
    "ean_13",
    "ean_8",
    "itf",
    "data_matrix",
    "manual",
)


# -- Offline sync --------------------------------------------------------------
SYNC_WORK_ORDER_STATUS = "workOrder.status"
SYNC_WORK_ORDER_LABOUR = "workOrder.labour"
SYNC_WORK_ORDER_PART = "workOrder.partUsage"
SYNC_TIMER_START = "workTimer.start"
SYNC_TIMER_STOP = "workTimer.stop"
SYNC_DEVICE_STATUS = "device.status"
SYNC_METER_READING = "meter.reading"

#: Everything a technician can legitimately do with no network. Reads are not
#: listed: they are served from the local cache and never replayed.
SYNC_KINDS = (
    SYNC_WORK_ORDER_STATUS,
    SYNC_WORK_ORDER_LABOUR,
    SYNC_WORK_ORDER_PART,
    SYNC_TIMER_START,
    SYNC_TIMER_STOP,
    SYNC_DEVICE_STATUS,
    SYNC_METER_READING,
)

#: Per-item outcome reported back to the queue.
#:
#: ``applied``   — executed now; drop it from the queue.
#: ``duplicate`` — already executed earlier (same clientRequestId, or the
#:                 server-side state shows the effect); drop it too.
#: ``conflict``  — someone else changed the same record while the phone was
#:                 offline, so replaying would silently overwrite their work;
#:                 drop it and make the technician look at the new state.
#: ``rejected``  — will never succeed (validation, permission, vanished
#:                 target); drop it and show the technician why.
#: ``failed``    — transient (server error, lock contention); keep it and
#:                 retry on the next sync.
SYNC_STATUS_APPLIED = "applied"
SYNC_STATUS_DUPLICATE = "duplicate"
SYNC_STATUS_REJECTED = "rejected"
SYNC_STATUS_CONFLICT = "conflict"
SYNC_STATUS_FAILED = "failed"

SYNC_STATUSES = (
    SYNC_STATUS_APPLIED,
    SYNC_STATUS_DUPLICATE,
    SYNC_STATUS_REJECTED,
    SYNC_STATUS_CONFLICT,
    SYNC_STATUS_FAILED,
)

#: Statuses persisted in the ledger. ``duplicate`` is never stored — it is a
#: *reply* about an already-stored row.
PERSISTED_SYNC_STATUSES = (
    SYNC_STATUS_APPLIED,
    SYNC_STATUS_FAILED,
    SYNC_STATUS_REJECTED,
    SYNC_STATUS_CONFLICT,
)

#: Payload key a client sends to say «this is the value I was looking at when
#: I queued the change». Absent ⇒ no concurrency check (older clients keep
#: working, last-write-wins as before).
SYNC_BASELINE_KEY = "baselineStatus"

#: One phone cannot flood the server with an unbounded backlog in one request.
MAX_SYNC_BATCH = 200

#: ``clientRequestId`` is generated by the phone (uuid v4 in practice) and is
#: the only thing standing between a double-sync and a double-charge.
MAX_CLIENT_REQUEST_ID_LENGTH = 80


@dataclass(frozen=True)
class ScanTarget:
    """What a scanned code resolved to, plus where the UI should navigate."""

    kind: str
    id: str
    code: str
    title: str
    subtitle: str
    route: str
    status: str = ""

    def __post_init__(self) -> None:
        if self.kind not in SCAN_TARGETS:
            raise ValueError(f"Unknown scan target kind: {self.kind}")


__all__ = [
    "MAX_CLIENT_REQUEST_ID_LENGTH",
    "MAX_SYNC_BATCH",
    "SCAN_SYMBOLOGIES",
    "SCAN_TARGETS",
    "SCAN_TARGET_DEVICE",
    "SCAN_TARGET_LOCATION",
    "SCAN_TARGET_SPARE_PART",
    "SCAN_TARGET_WORK_ORDER",
    "SYNC_DEVICE_STATUS",
    "SYNC_BASELINE_KEY",
    "SYNC_KINDS",
    "SYNC_METER_READING",
    "SYNC_STATUSES",
    "SYNC_STATUS_APPLIED",
    "SYNC_STATUS_CONFLICT",
    "SYNC_STATUS_DUPLICATE",
    "SYNC_STATUS_FAILED",
    "SYNC_STATUS_REJECTED",
    "SYNC_TIMER_START",
    "SYNC_TIMER_STOP",
    "SYNC_WORK_ORDER_LABOUR",
    "SYNC_WORK_ORDER_PART",
    "SYNC_WORK_ORDER_STATUS",
    "ScanTarget",
]
