# Generated by Django 6.1 on 2026-08-30 07:57

import uuid

from django.db import migrations, models


def _backfill_refresh_hashes(apps, schema_editor):
    """Give every legacy session a distinct placeholder refresh hash."""
    import uuid

    Session = apps.get_model("identity", "SessionModel")
    for row in Session.objects.all().iterator():
        if not row.refreshTokenHash:
            Session.objects.filter(id=row.id).update(refreshTokenHash=f"legacy-{uuid.uuid4().hex}")


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKeyModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("name", models.CharField(max_length=160)),
                ("prefix", models.CharField(db_index=True, max_length=16)),
                ("keyHash", models.CharField(max_length=64, unique=True)),
                ("ownerType", models.CharField(default="user", max_length=16)),
                ("ownerId", models.UUIDField(db_index=True)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("expiresAt", models.DateTimeField(blank=True, null=True)),
                ("revokedAt", models.DateTimeField(blank=True, null=True)),
                ("lastUsedAt", models.DateTimeField(blank=True, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ApiKey",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="MfaFactorModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("userId", models.UUIDField(db_index=True)),
                ("factorType", models.CharField(max_length=16)),
                ("secretRef", models.CharField(max_length=512)),
                ("status", models.CharField(default="pending", max_length=10)),
                ("confirmedAt", models.DateTimeField(blank=True, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "MfaFactor",
            },
        ),
        migrations.CreateModel(
            name="PasswordHistoryModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("userId", models.UUIDField(db_index=True)),
                ("passwordHash", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "PasswordHistory",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="PasswordResetTokenModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("userId", models.UUIDField(db_index=True)),
                ("tokenHash", models.CharField(max_length=64, unique=True)),
                ("expiresAt", models.DateTimeField(db_index=True)),
                ("usedAt", models.DateTimeField(blank=True, null=True)),
                ("requestIp", models.CharField(blank=True, default="", max_length=64)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "PasswordResetToken",
            },
        ),
        migrations.CreateModel(
            name="RecoveryCodeModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("userId", models.UUIDField(db_index=True)),
                ("codeHash", models.CharField(max_length=64)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("usedAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "RecoveryCode",
            },
        ),
        migrations.CreateModel(
            name="SecurityEventModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("occurredAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("eventType", models.CharField(db_index=True, max_length=40)),
                ("userId", models.UUIDField(blank=True, null=True)),
                ("tenantId", models.UUIDField(blank=True, db_index=True, null=True)),
                ("sessionId", models.UUIDField(blank=True, null=True)),
                ("ipAddress", models.CharField(blank=True, default="", max_length=64)),
                ("userAgent", models.CharField(blank=True, default="", max_length=300)),
                ("correlationId", models.CharField(blank=True, default="", max_length=64)),
                ("result", models.CharField(default="success", max_length=10)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
            ],
            options={
                "db_table": "SecurityEvent",
                "ordering": ["-occurredAt"],
            },
        ),
        migrations.CreateModel(
            name="ServiceAccountModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=160)),
                ("description", models.CharField(blank=True, default="", max_length=500)),
                ("status", models.CharField(default="active", max_length=10)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("disabledAt", models.DateTimeField(blank=True, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ServiceAccount",
            },
        ),
        migrations.CreateModel(
            name="VerificationTokenModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("userId", models.UUIDField(db_index=True)),
                ("channel", models.CharField(max_length=16)),
                ("destination", models.CharField(max_length=320)),
                ("tokenHash", models.CharField(max_length=64, unique=True)),
                ("expiresAt", models.DateTimeField(db_index=True)),
                ("verifiedAt", models.DateTimeField(blank=True, null=True)),
                ("attemptCount", models.IntegerField(default=0)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "VerificationToken",
            },
        ),
        migrations.RemoveConstraint(
            model_name="rolemodel",
            name="UQ_Role_code",
        ),
        migrations.RemoveField(
            model_name="sessionmodel",
            name="lastUsedAt",
        ),
        migrations.RemoveField(
            model_name="sessionmodel",
            name="tokenHash",
        ),
        migrations.AddField(
            model_name="sessionmodel",
            name="device",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="sessionmodel",
            name="ipAddress",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="sessionmodel",
            name="lastActivityAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sessionmodel",
            name="refreshTokenHash",
            field=models.CharField(default="", max_length=64),
        ),
        # Phase 07 §7 — backfill legacy rows with unique placeholders, then
        # enforce the §34 unique constraint on the refresh-token hash.
        migrations.RunPython(
            code=_backfill_refresh_hashes,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="sessionmodel",
            name="refreshTokenHash",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name="sessionmodel",
            name="userAgent",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="tenantmembershipmodel",
            name="defaultRole",
            field=models.CharField(blank=True, default="member", max_length=64),
        ),
        migrations.AddField(
            model_name="tenantmembershipmodel",
            name="isPrimary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenantmembershipmodel",
            name="status",
            field=models.CharField(default="active", max_length=12),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="expiresAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="failedLoginCount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="kind",
            field=models.CharField(default="human", max_length=12),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="lastLoginAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="lockedUntil",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="passwordChangedAt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="status",
            field=models.CharField(default="active", max_length=24),
        ),
        migrations.AddConstraint(
            model_name="rolemodel",
            constraint=models.UniqueConstraint(
                fields=("scopeType", "code"), name="UQ_Role_scope_code"
            ),
        ),
        migrations.AddIndex(
            model_name="securityeventmodel",
            index=models.Index(fields=["tenantId", "occurredAt"], name="IX_SecEvent_t_occ"),
        ),
        migrations.AddIndex(
            model_name="securityeventmodel",
            index=models.Index(fields=["userId", "eventType"], name="IX_SecEvent_u_event"),
        ),
        migrations.AddConstraint(
            model_name="serviceaccountmodel",
            constraint=models.UniqueConstraint(
                fields=("tenantId", "code"), name="UQ_ServiceAccount_code"
            ),
        ),
    ]
