# Generated by Django 6.1 on 2026-09-29 11:46

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetricDefinitionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, default="", max_length=1000)),
                ("formula", models.CharField(blank=True, default="", max_length=500)),
                ("unit", models.CharField(blank=True, default="", max_length=32)),
                ("aggregation", models.CharField(default="LAST", max_length=16)),
                (
                    "minimumValue",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
                ),
                (
                    "maximumValue",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
                ),
                ("isActive", models.BooleanField(db_index=True, default=True)),
                (
                    "createdAt",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updatedAt", models.DateTimeField(blank=True, null=True)),
                ("deletedAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "MetricDefinition",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["tenantId", "isActive"], name="ix_mdef_tenant_active")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deletedAt__isnull", True)),
                        fields=("tenantId", "code"),
                        name="uq_mdef_tenant_code",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("aggregation__in", ("LAST", "SUM", "AVERAGE", "MIN", "MAX", "COUNT"))
                        ),
                        name="ck_mdef_aggregation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("minimumValue__isnull", True),
                            ("maximumValue__isnull", True),
                            ("minimumValue__lte", models.F("maximumValue")),
                            _connector="OR",
                        ),
                        name="ck_mdef_value_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricReadingModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("value", models.DecimalField(decimal_places=6, max_digits=18)),
                ("dimensions", models.JSONField(blank=True, default=dict)),
                ("quality", models.CharField(default="GOOD", max_length=12)),
                ("periodStart", models.DateTimeField(db_index=True)),
                ("periodEnd", models.DateTimeField(db_index=True)),
                ("sourceType", models.CharField(blank=True, default="", max_length=64)),
                ("sourceId", models.CharField(blank=True, default="", max_length=128)),
                ("ingestionKey", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "recordedAt",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("recordedById", models.UUIDField(blank=True, null=True)),
                ("correlationId", models.CharField(blank=True, default="", max_length=64)),
                (
                    "metric",
                    models.ForeignKey(
                        db_column="metricId",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readings",
                        to="analytics.metricdefinitionmodel",
                    ),
                ),
            ],
            options={
                "db_table": "MetricReading",
                "ordering": ["-periodStart", "-id"],
                "indexes": [
                    models.Index(
                        fields=["tenantId", "metric", "periodStart"],
                        name="ix_mread_tenant_metric_time",
                    ),
                    models.Index(
                        fields=["tenantId", "sourceType", "sourceId", "periodStart"],
                        name="ix_mread_tenant_source_time",
                    ),
                    models.Index(
                        fields=["tenantId", "recordedAt"], name="ix_mread_tenant_recorded"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ingestionKey__isnull", False)),
                        fields=("tenantId", "ingestionKey"),
                        name="uq_mread_tenant_ingestion",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quality__in", ("GOOD", "SUSPECT", "BAD", "UNKNOWN"))),
                        name="ck_mread_quality",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("periodEnd__gte", models.F("periodStart"))),
                        name="ck_mread_period",
                    ),
                ],
            },
        ),
    ]
