# Generated by Django 6.1 on 2026-08-31 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_phase9_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAttemptModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('deliveryId', models.UUIDField(db_index=True)),
                ('attemptNumber', models.IntegerField()),
                ('outcome', models.CharField(max_length=12)),
                ('provider', models.CharField(blank=True, default='', max_length=48)),
                ('providerMessageId', models.CharField(blank=True, default='', max_length=120)),
                ('errorCode', models.CharField(blank=True, default='', max_length=48)),
                ('errorMessage', models.CharField(blank=True, default='', max_length=500)),
                ('responseMetadata', models.JSONField(blank=True, default=dict)),
                ('startedAt', models.DateTimeField(blank=True, null=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificationAttempts',
                'indexes': [models.Index(fields=['deliveryId', 'attemptNumber'], name='IX_Att_dlv_num')],
                'constraints': [models.UniqueConstraint(fields=('deliveryId', 'attemptNumber'), name='UQ_Att_dlv_num')],
            },
        ),
        migrations.CreateModel(
            name='NotificationEventModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('eventId', models.CharField(db_index=True, max_length=80)),
                ('eventType', models.CharField(db_index=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificationEvents',
                'constraints': [models.UniqueConstraint(fields=('tenantId', 'eventId'), name='UQ_Event_tenant_evt')],
            },
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('notificationType', models.CharField(db_index=True, max_length=120)),
                ('severity', models.CharField(default='INFO', max_length=16)),
                ('priority', models.CharField(db_index=True, default='NORMAL', max_length=16)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('sourceType', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('sourceId', models.CharField(blank=True, default='', max_length=120)),
                ('deepLink', models.CharField(blank=True, default='', max_length=300)),
                ('language', models.CharField(blank=True, default='', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotencyKey', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('correlationId', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['tenantId', 'notificationType'], name='IX_Ntf12_type'), models.Index(fields=['tenantId', 'priority'], name='IX_Ntf12_pri')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotencyKey__gt', '')), fields=('tenantId', 'idempotencyKey'), name='UQ_Notifications12_idem')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipientDeliveryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('notificationId', models.UUIDField(db_index=True)),
                ('recipientId', models.UUIDField(db_index=True)),
                ('channel', models.CharField(db_index=True, max_length=16)),
                ('provider', models.CharField(blank=True, default='', max_length=48)),
                ('deliveryStatus', models.CharField(db_index=True, default='PENDING', max_length=16)),
                ('attemptCount', models.IntegerField(default=0)),
                ('maxAttempts', models.IntegerField(default=5)),
                ('errorCode', models.CharField(blank=True, default='', max_length=48)),
                ('errorMessage', models.CharField(blank=True, default='', max_length=500)),
                ('lastAttemptAt', models.DateTimeField(blank=True, null=True)),
                ('nextAttemptAt', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notificationDeliveries',
                'indexes': [models.Index(fields=['deliveryStatus', 'nextAttemptAt'], name='IX_Dlv12_retry'), models.Index(fields=['notificationId', 'recipientId', 'channel'], name='IX_Dlv12_nrc')],
                'constraints': [models.UniqueConstraint(fields=('notificationId', 'recipientId', 'channel'), name='UQ_Dlv12_triple')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipientModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('notificationId', models.UUIDField(db_index=True)),
                ('userId', models.UUIDField(db_index=True)),
                ('recipientState', models.CharField(db_index=True, default='UNREAD', max_length=12)),
                ('readAt', models.DateTimeField(blank=True, null=True)),
                ('archivedAt', models.DateTimeField(blank=True, null=True)),
                ('dismissedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificationRecipients',
                'indexes': [models.Index(fields=['tenantId', 'userId', 'recipientState', 'createdAt'], name='IX_Recp_inbox'), models.Index(fields=['notificationId', 'userId'], name='IX_Recp_n_u')],
                'constraints': [models.UniqueConstraint(fields=('notificationId', 'userId'), name='UQ_Recp_notif_user')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRuleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=160)),
                ('eventType', models.CharField(db_index=True, max_length=120)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('recipientStrategy', models.CharField(default='TARGET', max_length=24)),
                ('channels', models.JSONField(default=list)),
                ('priority', models.CharField(default='NORMAL', max_length=16)),
                ('templateKey', models.CharField(blank=True, default='', max_length=120)),
                ('isActive', models.BooleanField(db_index=True, default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificationRules',
                'indexes': [models.Index(fields=['tenantId', 'eventType', 'isActive'], name='IX_Rule_evt')],
            },
        ),
    ]
