# Generated by Django 6.1 on 2026-08-30 09:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('initiatorId', models.UUIDField(db_index=True)),
                ('conversationId', models.UUIDField(blank=True, db_index=True, null=True)),
                ('meetingId', models.UUIDField(blank=True, db_index=True, null=True)),
                ('mediaType', models.CharField(default='AUDIO', max_length=12)),
                ('callStatus', models.CharField(db_index=True, default='RINGING', max_length=10)),
                ('mediaSessionRef', models.CharField(blank=True, default='', max_length=120)),
                ('clientRequestId', models.CharField(blank=True, default='', max_length=80)),
                ('startedAt', models.DateTimeField(blank=True, null=True)),
                ('endedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communicationCalls',
                'indexes': [models.Index(fields=['meetingId', 'callStatus'], name='IX_Call_m_status'), models.Index(fields=['callStatus', 'startedAt'], name='IX_Call_status_start')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('clientRequestId__gt', '')), fields=('tenantId', 'initiatorId', 'clientRequestId'), name='UQ_Call_idempotency')],
            },
        ),
        migrations.CreateModel(
            name='CallParticipantModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('callId', models.UUIDField(db_index=True)),
                ('userId', models.UUIDField(db_index=True)),
                ('joinedAt', models.DateTimeField(auto_now_add=True)),
                ('leftAt', models.DateTimeField(blank=True, null=True)),
                ('mediaState', models.CharField(default='connected', max_length=32)),
            ],
            options={
                'db_table': 'communicationCallParticipants',
                'constraints': [models.UniqueConstraint(fields=('callId', 'userId'), name='UQ_CallParticipant')],
            },
        ),
        migrations.CreateModel(
            name='ChannelMembershipModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversationId', models.UUIDField(db_index=True)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('userId', models.UUIDField(db_index=True)),
                ('requestedBy', models.UUIDField(blank=True, null=True)),
                ('joinedAt', models.DateTimeField(auto_now_add=True)),
                ('leftAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'communicationChannelMemberships',
                'indexes': [models.Index(fields=['conversationId', 'userId'], name='IX_ChanM_c_u')],
            },
        ),
        migrations.CreateModel(
            name='ConversationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('conversationType', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=160)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('directKey', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('isActive', models.BooleanField(db_index=True, default=True)),
                ('createdBy', models.UUIDField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('archivedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'communicationConversations',
                'indexes': [models.Index(fields=['tenantId', 'conversationType'], name='IX_Conv_t_type'), models.Index(fields=['tenantId', 'isActive'], name='IX_Conv_t_active')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('conversationType', 'DIRECT'), ('directKey__gt', '')), fields=('tenantId', 'directKey'), name='UQ_Conversation_direct_key')],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipantModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversationId', models.UUIDField(db_index=True)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('userId', models.UUIDField(db_index=True)),
                ('role', models.CharField(default='MEMBER', max_length=12)),
                ('invitedBy', models.UUIDField(blank=True, null=True)),
                ('joinedAt', models.DateTimeField(auto_now_add=True)),
                ('leftAt', models.DateTimeField(blank=True, null=True)),
                ('isMuted', models.BooleanField(default=False)),
                ('notificationLevel', models.CharField(default='ALL', max_length=12)),
                ('lastReadMessageId', models.UUIDField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communicationConversationParticipants',
                'indexes': [models.Index(fields=['conversationId', 'userId'], name='IX_Part_c_u')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('leftAt__isnull', True)), fields=('conversationId', 'userId'), name='UQ_Participant_active')],
            },
        ),
        migrations.CreateModel(
            name='MeetingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('conversationId', models.UUIDField(db_index=True)),
                ('organizerId', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('scheduledStart', models.DateTimeField(blank=True, null=True)),
                ('scheduledEnd', models.DateTimeField(blank=True, null=True)),
                ('actualStart', models.DateTimeField(blank=True, null=True)),
                ('actualEnd', models.DateTimeField(blank=True, null=True)),
                ('meetingStatus', models.CharField(db_index=True, default='SCHEDULED', max_length=12)),
                ('clientRequestId', models.CharField(blank=True, default='', max_length=80)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communicationMeetings',
                'indexes': [models.Index(fields=['tenantId', 'scheduledStart'], name='IX_Meet_t_start'), models.Index(fields=['tenantId', 'meetingStatus'], name='IX_Meet_t_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('clientRequestId__gt', '')), fields=('tenantId', 'organizerId', 'clientRequestId'), name='UQ_Meeting_idempotency')],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipantModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('meetingId', models.UUIDField(db_index=True)),
                ('userId', models.UUIDField(db_index=True)),
                ('status', models.CharField(default='INVITED', max_length=10)),
                ('respondedAt', models.DateTimeField(blank=True, null=True)),
                ('joinedAt', models.DateTimeField(blank=True, null=True)),
                ('leftAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communicationMeetingParticipants',
                'constraints': [models.UniqueConstraint(fields=('meetingId', 'userId'), name='UQ_MeetingParticipant')],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('messageId', models.UUIDField(db_index=True)),
                ('fileName', models.CharField(max_length=255)),
                ('mimeType', models.CharField(default='application/octet-stream', max_length=120)),
                ('sizeBytes', models.BigIntegerField(default=0)),
                ('documentRef', models.CharField(blank=True, default='', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communicationMessageAttachments',
                'indexes': [models.Index(fields=['messageId'], name='IX_Att_m')],
            },
        ),
        migrations.CreateModel(
            name='MessageMentionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('messageId', models.UUIDField(db_index=True)),
                ('mentionedUserId', models.UUIDField(db_index=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communicationMessageMentions',
                'indexes': [models.Index(fields=['messageId'], name='IX_Men_m')],
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('conversationId', models.UUIDField(db_index=True)),
                ('senderId', models.UUIDField(db_index=True)),
                ('messageType', models.CharField(default='TEXT', max_length=20)),
                ('body', models.TextField(blank=True, default='')),
                ('replyToId', models.UUIDField(blank=True, db_index=True, null=True)),
                ('clientRequestId', models.CharField(blank=True, default='', max_length=80)),
                ('editedAt', models.DateTimeField(blank=True, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communicationMessages',
                'indexes': [models.Index(fields=['conversationId', 'createdAt'], name='IX_Msg_c_created'), models.Index(fields=['senderId', 'createdAt'], name='IX_Msg_s_created')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('clientRequestId__gt', '')), fields=('tenantId', 'conversationId', 'senderId', 'clientRequestId'), name='UQ_Message_idempotency')],
            },
        ),
        migrations.CreateModel(
            name='MessageReactionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('messageId', models.UUIDField(db_index=True)),
                ('userId', models.UUIDField(db_index=True)),
                ('reaction', models.CharField(max_length=16)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communicationMessageReactions',
                'constraints': [models.UniqueConstraint(fields=('messageId', 'userId', 'reaction'), name='UQ_Reaction_unique')],
            },
        ),
        migrations.CreateModel(
            name='MessageReadStateModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('conversationId', models.UUIDField(db_index=True)),
                ('messageId', models.UUIDField(db_index=True)),
                ('userId', models.UUIDField(db_index=True)),
                ('state', models.CharField(default='SENT', max_length=10)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communicationMessageReadStates',
                'indexes': [models.Index(fields=['messageId', 'userId'], name='IX_Read_m_u')],
                'constraints': [models.UniqueConstraint(fields=('messageId', 'userId'), name='UQ_ReadState_m_u')],
            },
        ),
        migrations.CreateModel(
            name='OfficialLetterModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('referenceNumber', models.CharField(db_index=True, max_length=20)),
                ('senderId', models.UUIDField(db_index=True)),
                ('recipientId', models.UUIDField(db_index=True)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('recipientOrganization', models.CharField(blank=True, default='', max_length=160)),
                ('recipientUnit', models.CharField(blank=True, default='', max_length=160)),
                ('letterStatus', models.CharField(db_index=True, default='DRAFT', max_length=12)),
                ('approvedBy', models.UUIDField(blank=True, null=True)),
                ('signedBy', models.UUIDField(blank=True, null=True)),
                ('dispatchedAt', models.DateTimeField(blank=True, null=True)),
                ('receivedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communicationOfficialLetters',
                'constraints': [models.UniqueConstraint(fields=('tenantId', 'referenceNumber'), name='UQ_Letter_reference')],
            },
        ),
        migrations.CreateModel(
            name='OutboxModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('eventType', models.CharField(db_index=True, max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('occurredAt', models.DateTimeField()),
                ('publishedAt', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'communicationOutbox',
                'indexes': [models.Index(fields=['publishedAt', 'occurredAt'], name='IX_Outbox_pending')],
            },
        ),
        migrations.CreateModel(
            name='PinnedMessageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('conversationId', models.UUIDField(db_index=True)),
                ('messageId', models.UUIDField(db_index=True)),
                ('pinnedBy', models.UUIDField()),
                ('pinnedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communicationPins',
                'constraints': [models.UniqueConstraint(fields=('conversationId', 'messageId'), name='UQ_Pin_unique')],
            },
        ),
        migrations.CreateModel(
            name='RecordingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('meetingId', models.UUIDField(db_index=True)),
                ('requestedBy', models.UUIDField(db_index=True)),
                ('recordingStatus', models.CharField(default='REQUESTED', max_length=12)),
                ('startedAt', models.DateTimeField(blank=True, null=True)),
                ('stoppedAt', models.DateTimeField(blank=True, null=True)),
                ('storageRef', models.CharField(blank=True, default='', max_length=255)),
                ('durationSeconds', models.IntegerField(default=0)),
                ('failureReason', models.CharField(blank=True, default='', max_length=300)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communicationRecordings',
                'indexes': [models.Index(fields=['tenantId', 'meetingId'], name='IX_Rec_t_m')],
            },
        ),
        migrations.CreateModel(
            name='ChannelProfileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('topic', models.CharField(blank=True, default='', max_length=300)),
                ('visibility', models.CharField(default='PUBLIC', max_length=12)),
                ('isArchived', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('conversationId', models.OneToOneField(db_column='conversationId', on_delete=django.db.models.deletion.CASCADE, to='communication.conversationmodel')),
            ],
            options={
                'db_table': 'communicationChannels',
                'constraints': [models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('tenantId', 'code'), name='UQ_Channel_code')],
            },
        ),
    ]
