# Generated by Django 6.1 on 2026-10-05 09:06

from django.db import migrations, models

import apps.documents.infrastructure.models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentmodel",
            name="file",
            field=models.FileField(
                max_length=500, upload_to=apps.documents.infrastructure.models.documentStoragePath
            ),
        ),
    ]
