"""Public Phase 13 AI errors."""

from apps.ai.domain.exceptions.aiExceptions import (
    AIConfigurationError,
    AIContextTooLarge,
    AIError,
    AIIdempotencyConflict,
    AIModelUnavailable,
    AIPermissionDenied,
    AIPromptNotFound,
    AIProviderAlreadyRegistered,
    AIProviderInactive,
    AIProviderNotRegistered,
    AIProviderRateLimited,
    AIProviderRegistrationInvalid,
    AIProviderUnavailable,
    AIQuotaExceeded,
    AIRequestTimeout,
    AITokenLimitExceeded,
    AIToolDenied,
    AIOutputValidationFailed,
)

__all__ = [
    "AIConfigurationError",
    "AIContextTooLarge",
    "AIError",
    "AIIdempotencyConflict",
    "AIModelUnavailable",
    "AIProviderAlreadyRegistered",
    "AIProviderInactive",
    "AIProviderNotRegistered",
    "AIProviderRateLimited",
    "AIProviderRegistrationInvalid",
    "AIPermissionDenied",
    "AIPromptNotFound",
    "AIProviderUnavailable",
    "AIQuotaExceeded",
    "AIRequestTimeout",
    "AITokenLimitExceeded",
    "AIToolDenied",
    "AIOutputValidationFailed",
]
