# Generated by Django 6.1 on 2026-10-07 13:50

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermitEventModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('permitId', models.UUIDField(db_index=True)),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('fromStatus', models.CharField(blank=True, default='', max_length=16)),
                ('toStatus', models.CharField(blank=True, default='', max_length=16)),
                ('actorId', models.UUIDField(blank=True, null=True)),
                ('actorName', models.CharField(blank=True, default='', max_length=160)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('occurredAt', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'SafetyPermitEvent',
                'ordering': ['occurredAt', 'createdAt'],
            },
        ),
        migrations.CreateModel(
            name='PermitIsolationPointModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('permitId', models.UUIDField(db_index=True)),
                ('pointCode', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=500)),
                ('energyType', models.CharField(choices=[('electrical', 'electrical'), ('mechanical', 'mechanical'), ('hydraulic', 'hydraulic'), ('pneumatic', 'pneumatic'), ('chemical', 'chemical'), ('thermal', 'thermal'), ('gravity', 'gravity'), ('radiation', 'radiation')], max_length=16)),
                ('isolationMethod', models.CharField(blank=True, default='', max_length=240)),
                ('lockTag', models.CharField(blank=True, default='', max_length=60)),
                ('appliedById', models.UUIDField(blank=True, null=True)),
                ('appliedByName', models.CharField(blank=True, default='', max_length=160)),
                ('appliedAt', models.DateTimeField(blank=True, null=True)),
                ('verifiedById', models.UUIDField(blank=True, null=True)),
                ('verifiedByName', models.CharField(blank=True, default='', max_length=160)),
                ('verifiedAt', models.DateTimeField(blank=True, null=True)),
                ('removedById', models.UUIDField(blank=True, null=True)),
                ('removedByName', models.CharField(blank=True, default='', max_length=160)),
                ('removedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SafetyPermitIsolationPoint',
                'ordering': ['pointCode'],
            },
        ),
        migrations.CreateModel(
            name='PermitPrecautionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('permitId', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=500)),
                ('isMandatory', models.BooleanField(default=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmedById', models.UUIDField(blank=True, null=True)),
                ('confirmedByName', models.CharField(blank=True, default='', max_length=160)),
                ('confirmedAt', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'db_table': 'SafetyPermitPrecaution',
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='PermitToWorkModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(max_length=40)),
                ('permitType', models.CharField(choices=[('hotWork', 'hotWork'), ('confinedSpace', 'confinedSpace'), ('electrical', 'electrical'), ('workAtHeight', 'workAtHeight'), ('excavation', 'excavation'), ('lineBreaking', 'lineBreaking'), ('radiography', 'radiography'), ('general', 'general')], db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('approved', 'approved'), ('active', 'active'), ('suspended', 'suspended'), ('completed', 'completed'), ('closed', 'closed'), ('rejected', 'rejected'), ('cancelled', 'cancelled'), ('expired', 'expired')], db_index=True, default='draft', max_length=16)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('riskLevel', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], default='medium', max_length=12)),
                ('deviceId', models.UUIDField(blank=True, db_index=True, null=True)),
                ('workOrderId', models.UUIDField(blank=True, db_index=True, null=True)),
                ('locationId', models.UUIDField(blank=True, db_index=True, null=True)),
                ('locationName', models.CharField(blank=True, default='', max_length=240)),
                ('requesterId', models.UUIDField(blank=True, db_index=True, null=True)),
                ('requesterName', models.CharField(blank=True, default='', max_length=160)),
                ('performerName', models.CharField(blank=True, default='', max_length=240)),
                ('contractorName', models.CharField(blank=True, default='', max_length=240)),
                ('personnelCount', models.PositiveIntegerField(default=1)),
                ('approverId', models.UUIDField(blank=True, null=True)),
                ('approverName', models.CharField(blank=True, default='', max_length=160)),
                ('closedById', models.UUIDField(blank=True, null=True)),
                ('closedByName', models.CharField(blank=True, default='', max_length=160)),
                ('validFrom', models.DateTimeField(blank=True, null=True)),
                ('validTo', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('submittedAt', models.DateTimeField(blank=True, null=True)),
                ('approvedAt', models.DateTimeField(blank=True, null=True)),
                ('activatedAt', models.DateTimeField(blank=True, null=True)),
                ('suspendedAt', models.DateTimeField(blank=True, null=True)),
                ('completedAt', models.DateTimeField(blank=True, null=True)),
                ('closedAt', models.DateTimeField(blank=True, null=True)),
                ('suspensionReason', models.CharField(blank=True, default='', max_length=500)),
                ('rejectionReason', models.CharField(blank=True, default='', max_length=500)),
                ('cancellationReason', models.CharField(blank=True, default='', max_length=500)),
                ('closureNote', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'SafetyPermitToWork',
                'ordering': ['-createdAt'],
                'indexes': [models.Index(fields=['tenantId', 'status'], name='ix_safety_permit_status')],
                'constraints': [models.UniqueConstraint(fields=('tenantId', 'number'), name='uq_safety_permit_number')],
            },
        ),
    ]
