# Generated by Django 6.1 on 2026-10-08 10:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrganizationAuditModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(blank=True, null=True)),
                ("entity", models.CharField(db_index=True, max_length=32)),
                ("entityId", models.UUIDField(blank=True, db_index=True, null=True)),
                ("action", models.CharField(max_length=40)),
                ("summary", models.CharField(blank=True, default="", max_length=500)),
                ("actorUserId", models.UUIDField(blank=True, null=True)),
                ("actorName", models.CharField(blank=True, default="", max_length=160)),
                ("occurredAt", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "OrganizationAudit",
                "ordering": ["-occurredAt"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationAccessRuleModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(blank=True, null=True)),
                ("positionId", models.UUIDField(db_index=True)),
                ("departmentId", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("workOrder", "workOrder"),
                            ("device", "device"),
                            ("preventiveMaintenance", "preventiveMaintenance"),
                            ("inventory", "inventory"),
                            ("purchaseRequisition", "purchaseRequisition"),
                            ("purchaseOrder", "purchaseOrder"),
                            ("permitToWork", "permitToWork"),
                            ("report", "report"),
                            ("organizationUnit", "organizationUnit"),
                            ("unitMembers", "unitMembers"),
                            ("accessMatrix", "accessMatrix"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "view"),
                            ("create", "create"),
                            ("edit", "edit"),
                            ("delete", "delete"),
                            ("approve", "approve"),
                            ("assign", "assign"),
                            ("close", "close"),
                            ("export", "export"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("own", "own"),
                            ("team", "team"),
                            ("department", "department"),
                            ("all", "all"),
                        ],
                        default="department",
                        max_length=16,
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("updatedByUserId", models.UUIDField(blank=True, null=True)),
                ("updatedByName", models.CharField(blank=True, default="", max_length=160)),
            ],
            options={
                "db_table": "OrganizationAccessRule",
                "ordering": ["capability", "action"],
                "indexes": [
                    models.Index(fields=["tenantId", "positionId"], name="ix_org_rule_position")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenantId", "positionId", "departmentId", "capability", "action"),
                        name="uq_org_rule_cell",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationAssignmentModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(blank=True, null=True)),
                ("userId", models.UUIDField(db_index=True)),
                ("userDisplayName", models.CharField(blank=True, default="", max_length=160)),
                ("departmentId", models.UUIDField(db_index=True)),
                ("positionId", models.UUIDField(db_index=True)),
                ("isPrimary", models.BooleanField(default=True)),
                ("isActive", models.BooleanField(default=True)),
                ("reportsToUserId", models.UUIDField(blank=True, db_index=True, null=True)),
                ("startedAt", models.DateTimeField(blank=True, null=True)),
                ("endedAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "OrganizationAssignment",
                "ordering": ["-isPrimary", "-createdAt"],
                "indexes": [
                    models.Index(fields=["tenantId", "userId"], name="ix_org_assign_user"),
                    models.Index(fields=["tenantId", "departmentId"], name="ix_org_assign_dept"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenantId", "userId", "departmentId", "positionId"),
                        name="uq_org_assignment_once",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationDepartmentModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=160)),
                ("description", models.CharField(blank=True, default="", max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("parentId", models.UUIDField(blank=True, db_index=True, null=True)),
                ("managerUserId", models.UUIDField(blank=True, null=True)),
                ("managerName", models.CharField(blank=True, default="", max_length=160)),
                ("isSystem", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "OrganizationDepartment",
                "ordering": ["code"],
                "indexes": [models.Index(fields=["tenantId", "status"], name="ix_org_dept_status")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenantId", "code"), name="uq_org_department_code"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationPositionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=160)),
                ("description", models.CharField(blank=True, default="", max_length=500)),
                ("level", models.IntegerField(db_index=True, default=0)),
                ("isActive", models.BooleanField(default=True)),
                ("isSystem", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "OrganizationPosition",
                "ordering": ["-level", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenantId", "code"), name="uq_org_position_code"
                    )
                ],
            },
        ),
    ]
