# Generated by Django 6.1 on 2026-08-30 06:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PermissionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("module", models.CharField(max_length=40)),
                ("description", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "db_table": "Permission",
            },
        ),
        migrations.CreateModel(
            name="RoleModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=160)),
                ("scopeType", models.CharField(default="TENANT", max_length=20)),
                ("isActive", models.BooleanField(default=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Role",
                "constraints": [models.UniqueConstraint(fields=("code",), name="UQ_Role_code")],
            },
        ),
        migrations.CreateModel(
            name="RolePermissionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("roleId", models.UUIDField(db_index=True)),
                ("permissionId", models.UUIDField()),
                ("actionPattern", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "RolePermission",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("roleId", "actionPattern"), name="UQ_RolePermission_once"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("userId", models.UUIDField(db_index=True)),
                ("tenantId", models.UUIDField()),
                ("tokenHash", models.CharField(max_length=64, unique=True)),
                ("issuedAt", models.DateTimeField(auto_now_add=True)),
                ("expiresAt", models.DateTimeField(db_index=True)),
                ("lastUsedAt", models.DateTimeField(blank=True, null=True)),
                ("revokedAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Session",
                "indexes": [models.Index(fields=["userId", "expiresAt"], name="IX_Session_u_exp")],
            },
        ),
        migrations.CreateModel(
            name="TenantMembershipModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("userId", models.UUIDField(db_index=True)),
                ("tenantId", models.UUIDField(db_index=True)),
                ("joinedAt", models.DateTimeField(auto_now_add=True)),
                ("leftAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "TenantMembership",
                "indexes": [models.Index(fields=["userId", "tenantId"], name="IX_TM_user_tenant")],
            },
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("username", models.CharField(max_length=64)),
                ("email", models.CharField(max_length=320)),
                ("passwordHash", models.CharField(max_length=255)),
                ("displayName", models.CharField(blank=True, default="", max_length=160)),
                ("status", models.CharField(default="active", max_length=20)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(blank=True, null=True)),
                ("deletedAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "User",
                "ordering": ["-createdAt"],
                "indexes": [models.Index(fields=["tenantId", "status"], name="IX_User_t_status")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenantId", "username"), name="UQ_User_tenant_username"
                    ),
                    models.UniqueConstraint(
                        fields=("tenantId", "email"), name="UQ_User_tenant_email"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserPermissionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("userId", models.UUIDField(db_index=True)),
                ("permissionId", models.UUIDField()),
                ("actionPattern", models.CharField(max_length=64)),
                (
                    "effect",
                    models.CharField(choices=[("allow", "allow"), ("deny", "deny")], max_length=6),
                ),
                ("scopeType", models.CharField(default="TENANT", max_length=20)),
                ("scopeRef", models.CharField(blank=True, default="", max_length=64)),
                ("grantedAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "UserPermission",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("userId", "actionPattern", "effect", "scopeType"),
                        name="UQ_UserPermission_once",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRoleModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("userId", models.UUIDField(db_index=True)),
                ("roleId", models.UUIDField()),
                ("tenantId", models.UUIDField(blank=True, null=True)),
                ("scopeType", models.CharField(default="GLOBAL", max_length=20)),
                ("scopeRef", models.CharField(blank=True, default="", max_length=64)),
                ("grantedAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "UserRole",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("userId", "roleId", "scopeType"), name="UQ_UserRole_once"
                    )
                ],
            },
        ),
    ]
