# Generated by Django 6.1 on 2026-09-22 08:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkOrderModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("deviceId", models.UUIDField(db_index=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                ("orderType", models.CharField(default="corrective", max_length=20)),
                ("priority", models.CharField(default="normal", max_length=20)),
                ("status", models.CharField(default="submitted", max_length=20)),
                ("requestedByName", models.CharField(blank=True, default="", max_length=160)),
                ("assignedToName", models.CharField(blank=True, default="", max_length=160)),
                ("resolutionNote", models.TextField(blank=True, default="")),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(blank=True, null=True)),
                ("closedAt", models.DateTimeField(blank=True, null=True)),
                ("deletedAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "WorkOrder",
                "ordering": ["-createdAt"],
            },
        ),
        migrations.CreateModel(
            name="DeviceModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                ("status", models.CharField(default="operational", max_length=24)),
                ("pmIntervalDays", models.IntegerField(default=0)),
                ("lastPmDate", models.DateField(blank=True, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updatedAt", models.DateTimeField(blank=True, null=True)),
                ("deletedAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Device",
                "ordering": ["-createdAt"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deletedAt__isnull", True)),
                        fields=("tenantId", "code"),
                        name="uq_device_tenant_code",
                    )
                ],
            },
        ),
    ]
