# Generated by Django 6.1 on 2026-09-22 12:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_devicemodel_department_workordermodel_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderHistoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('workOrderId', models.UUIDField(db_index=True)),
                ('action', models.CharField(max_length=32)),
                ('fromStatus', models.CharField(blank=True, default='', max_length=20)),
                ('toStatus', models.CharField(blank=True, default='', max_length=20)),
                ('fromDepartment', models.CharField(blank=True, default='', max_length=24)),
                ('toDepartment', models.CharField(blank=True, default='', max_length=24)),
                ('actorName', models.CharField(blank=True, default='', max_length=160)),
                ('note', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'WorkOrderHistory',
                'ordering': ['createdAt'],
            },
        ),
    ]
