# Generated by Django 6.1 on 2026-09-23 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_workorderhistorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHistoryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('deviceId', models.UUIDField(db_index=True)),
                ('action', models.CharField(max_length=32)),
                ('fromStatus', models.CharField(blank=True, default='', max_length=20)),
                ('toStatus', models.CharField(blank=True, default='', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('actorName', models.CharField(blank=True, default='', max_length=160)),
                ('createdAt', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'DeviceHistory',
                'ordering': ['createdAt'],
            },
        ),
    ]
