# Generated by Django 6.1 on 2026-09-26 08:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_maintenance_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='assetType',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='capacity',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='commissionedOn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='criticality',
            field=models.CharField(db_index=True, default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='electricalSpec',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='installedOn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='locationId',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='locationPath',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='manufactureYear',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='modelNumber',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='operatorUnit',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='parentDeviceId',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='powerRating',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='purchaseCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='purchasedOn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='runningHours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='serialNumber',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='warrantyUntil',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='actionTaken',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='downtimeMinutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='failedComponent',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='failureReportedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='failureSymptom',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='failureType',
            field=models.CharField(blank=True, db_index=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='labourCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='labourHours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='partsCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='pmPlanId',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='repairFinishedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='repairStartedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='repeatFailure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='returnedToServiceAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='rootCause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='DeviceAssignmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('deviceId', models.UUIDField(db_index=True)),
                ('personnelId', models.UUIDField(blank=True, db_index=True, null=True)),
                ('personnelName', models.CharField(blank=True, default='', max_length=200)),
                ('role', models.CharField(default='technician', max_length=20)),
                ('unit', models.CharField(blank=True, default='', max_length=160)),
                ('fromDate', models.DateField(blank=True, null=True)),
                ('toDate', models.DateField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'DeviceAssignment',
                'ordering': ['role', 'personnelName'],
                'indexes': [models.Index(fields=['tenantId', 'deviceId', 'role'], name='DeviceAssig_tenantI_524797_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('role__in', ('operator', 'responsible', 'technician', 'deputy'))), name='ck_device_assignment_role')],
            },
        ),
        migrations.CreateModel(
            name='DeviceBomModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('deviceId', models.UUIDField(db_index=True)),
                ('partId', models.UUIDField(db_index=True)),
                ('position', models.CharField(blank=True, default='', max_length=160)),
                ('standardQuantity', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('createdAt', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'DeviceBom',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('tenantId', 'deviceId', 'partId'), name='uq_device_bom_device_part'), models.CheckConstraint(condition=models.Q(('standardQuantity__gt', 0)), name='ck_device_bom_quantity_positive')],
            },
        ),
        migrations.CreateModel(
            name='DeviceSpecificationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('deviceId', models.UUIDField(db_index=True)),
                ('label', models.CharField(max_length=160)),
                ('value', models.CharField(blank=True, default='', max_length=500)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('sortOrder', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'DeviceSpecification',
                'ordering': ['sortOrder', 'label'],
                'indexes': [models.Index(fields=['tenantId', 'deviceId'], name='DeviceSpeci_tenantI_a02168_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLocationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('parentId', models.UUIDField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(default='site', max_length=20)),
                ('path', models.CharField(blank=True, default='', max_length=800)),
                ('note', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(db_index=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MaintenanceLocation',
                'ordering': ['path', 'name'],
                'indexes': [models.Index(fields=['tenantId', 'parentId'], name='Maintenance_tenantI_8979f0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deletedAt__isnull', True)), fields=('tenantId', 'code'), name='uq_maintenance_location_tenant_code'), models.CheckConstraint(condition=models.Q(('kind__in', ('site', 'building', 'floor', 'hall', 'line', 'room', 'area'))), name='ck_maintenance_location_kind')],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePersonnelModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('personnelCode', models.CharField(max_length=60)),
                ('fullName', models.CharField(max_length=200)),
                ('specialty', models.CharField(db_index=True, default='general', max_length=24)),
                ('unit', models.CharField(blank=True, default='', max_length=160)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('shift', models.CharField(blank=True, default='', max_length=60)),
                ('skills', models.TextField(blank=True, default='')),
                ('certifications', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(db_index=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MaintenancePersonnel',
                'ordering': ['fullName'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deletedAt__isnull', True)), fields=('tenantId', 'personnelCode'), name='uq_maintenance_personnel_tenant_code')],
            },
        ),
        migrations.CreateModel(
            name='PmExecutionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('planId', models.UUIDField(db_index=True)),
                ('deviceId', models.UUIDField(db_index=True)),
                ('discipline', models.CharField(db_index=True, default='general', max_length=24)),
                ('performedOn', models.DateField(db_index=True)),
                ('dueOn', models.DateField(blank=True, null=True)),
                ('onTime', models.BooleanField(default=True)),
                ('performedByName', models.CharField(blank=True, default='', max_length=160)),
                ('durationMinutes', models.IntegerField(default=0)),
                ('findings', models.TextField(blank=True, default='')),
                ('workOrderId', models.UUIDField(blank=True, db_index=True, null=True)),
                ('createdAt', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'PmExecution',
                'ordering': ['-performedOn'],
                'indexes': [models.Index(fields=['tenantId', 'deviceId', 'performedOn'], name='PmExecution_tenantI_88e5c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PmPlanModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('deviceId', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=300)),
                ('discipline', models.CharField(db_index=True, default='general', max_length=24)),
                ('description', models.TextField(blank=True, default='')),
                ('checklist', models.TextField(blank=True, default='')),
                ('frequencyEvery', models.IntegerField(default=1)),
                ('frequencyUnit', models.CharField(default='month', max_length=20)),
                ('estimatedMinutes', models.IntegerField(default=0)),
                ('responsibleName', models.CharField(blank=True, default='', max_length=160)),
                ('lastExecutedOn', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(db_index=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PmPlan',
                'ordering': ['discipline', 'title'],
                'indexes': [models.Index(fields=['tenantId', 'deviceId', 'discipline'], name='PmPlan_tenantI_ab20e5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('frequencyEvery__gt', 0)), name='ck_pm_plan_frequency_positive'), models.CheckConstraint(condition=models.Q(('frequencyUnit__in', ('day', 'week', 'month', 'runningHour'))), name='ck_pm_plan_frequency_unit')],
            },
        ),
    ]
