# Generated by Django 6.1 on 2026-09-28 12:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0010_team_sync"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartTransactionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("partId", models.UUIDField(db_index=True)),
                ("partCode", models.CharField(max_length=60)),
                ("partName", models.CharField(max_length=200)),
                ("unit", models.CharField(default="عدد", max_length=30)),
                (
                    "transactionType",
                    models.CharField(
                        choices=[
                            ("RECEIPT", "رسید"),
                            ("ISSUE", "حواله"),
                            ("RETURN", "برگشت"),
                            ("ADJUSTMENT", "تعدیل"),
                        ],
                        max_length=12,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                ("balanceAfter", models.DecimalField(decimal_places=3, max_digits=14)),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                ("reference", models.CharField(blank=True, default="", max_length=120)),
                ("actorId", models.UUIDField(blank=True, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "PartTransaction",
                "ordering": ["-createdAt"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity", 0), _negated=True),
                        name="ck_part_transaction_nonzero_quantity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("balanceAfter__gte", 0)),
                        name="ck_part_transaction_nonnegative_balance",
                    ),
                ],
            },
        ),
    ]
