# Generated by Django 6.1 on 2026-10-03 06:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_pm_metric_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterPointModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('deviceId', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, default='', max_length=30)),
                ('kind', models.CharField(db_index=True, default='gauge', max_length=12)),
                ('sensorKey', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('minimumValue', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('maximumValue', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('rolloverMaximum', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('maximumStepPerHour', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('drivesRunningHours', models.BooleanField(default=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('lastValue', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('lastReadingAt', models.DateTimeField(blank=True, null=True)),
                ('lastCaptureMode', models.CharField(blank=True, default='', max_length=10)),
                ('readingCount', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(db_index=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MeterPoint',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MeterReadingModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('deviceId', models.UUIDField(db_index=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('delta', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('capturedAt', models.DateTimeField(db_index=True)),
                ('captureMode', models.CharField(db_index=True, default='manual', max_length=10)),
                ('quality', models.CharField(db_index=True, default='good', max_length=10)),
                ('rolloverApplied', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('sensorKey', models.CharField(blank=True, default='', max_length=120)),
                ('sourceRef', models.CharField(blank=True, default='', max_length=160)),
                ('ingestionKey', models.CharField(blank=True, max_length=128, null=True)),
                ('recordedById', models.UUIDField(blank=True, null=True)),
                ('recordedByName', models.CharField(blank=True, default='', max_length=160)),
                ('correctsReadingId', models.UUIDField(blank=True, db_index=True, null=True)),
                ('supersededByReadingId', models.UUIDField(blank=True, null=True)),
                ('correlationId', models.CharField(blank=True, default='', max_length=64)),
                ('createdAt', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'MeterReading',
                'ordering': ['-capturedAt', '-createdAt'],
            },
        ),
        migrations.AddField(
            model_name='pmexecutionmodel',
            name='meterValue',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='pmplanmodel',
            name='lastExecutedMeterValue',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddIndex(
            model_name='pmplanmodel',
            index=models.Index(fields=['tenantId', 'triggerType', 'active'], name='ix_pm_plan_tenant_trigger'),
        ),
        migrations.AddConstraint(
            model_name='pmplanmodel',
            constraint=models.CheckConstraint(condition=models.Q(('triggerType__in', ('calendar', 'meter', 'condition'))), name='ck_pm_plan_trigger_type'),
        ),
        migrations.AddConstraint(
            model_name='pmplanmodel',
            constraint=models.CheckConstraint(condition=models.Q(('thresholdOperator__in', ('>=', '<=', '>', '<'))), name='ck_pm_plan_threshold_operator'),
        ),
        migrations.AddConstraint(
            model_name='pmplanmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('triggerType', 'meter'), _negated=True), ('metricInterval__gt', 0), _connector='OR'), name='ck_pm_plan_meter_interval'),
        ),
        migrations.AddConstraint(
            model_name='pmplanmodel',
            constraint=models.CheckConstraint(condition=models.Q(('triggerType', 'calendar'), models.Q(('metricType', ''), _negated=True), _connector='OR'), name='ck_pm_plan_metric_type_required'),
        ),
        migrations.AddIndex(
            model_name='meterpointmodel',
            index=models.Index(fields=['tenantId', 'deviceId', 'active'], name='ix_mpoint_tenant_dev'),
        ),
        migrations.AddConstraint(
            model_name='meterpointmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('deletedAt__isnull', True)), fields=('tenantId', 'deviceId', 'code'), name='uq_meter_point_device_code'),
        ),
        migrations.AddConstraint(
            model_name='meterpointmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('deletedAt__isnull', True), models.Q(('sensorKey', ''), _negated=True)), fields=('tenantId', 'sensorKey'), name='uq_meter_point_sensor_key'),
        ),
        migrations.AddConstraint(
            model_name='meterpointmodel',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('cumulative', 'gauge'))), name='ck_meter_point_kind'),
        ),
        migrations.AddConstraint(
            model_name='meterpointmodel',
            constraint=models.CheckConstraint(condition=models.Q(('minimumValue__isnull', True), ('maximumValue__isnull', True), ('minimumValue__lte', models.F('maximumValue')), _connector='OR'), name='ck_meter_point_range'),
        ),
        migrations.AddConstraint(
            model_name='meterpointmodel',
            constraint=models.CheckConstraint(condition=models.Q(('rolloverMaximum__isnull', True), ('rolloverMaximum__gt', 0), _connector='OR'), name='ck_meter_point_rollover_positive'),
        ),
        migrations.AddConstraint(
            model_name='meterpointmodel',
            constraint=models.CheckConstraint(condition=models.Q(('rolloverMaximum__isnull', True), ('kind', 'cumulative'), _connector='OR'), name='ck_meter_point_rollover_cumulative_only'),
        ),
        migrations.AddConstraint(
            model_name='meterpointmodel',
            constraint=models.CheckConstraint(condition=models.Q(('drivesRunningHours', False), ('kind', 'cumulative'), _connector='OR'), name='ck_meter_point_hours_cumulative_only'),
        ),
        migrations.AddField(
            model_name='meterreadingmodel',
            name='meterPoint',
            field=models.ForeignKey(db_column='meterPointId', on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='maintenance.meterpointmodel'),
        ),
        migrations.AddIndex(
            model_name='meterreadingmodel',
            index=models.Index(fields=['tenantId', 'meterPoint', 'capturedAt'], name='ix_mr_tenant_point_time'),
        ),
        migrations.AddIndex(
            model_name='meterreadingmodel',
            index=models.Index(fields=['tenantId', 'deviceId', 'capturedAt'], name='ix_mr_tenant_device_time'),
        ),
        migrations.AddIndex(
            model_name='meterreadingmodel',
            index=models.Index(fields=['tenantId', 'captureMode', 'capturedAt'], name='ix_mr_tenant_mode_time'),
        ),
        migrations.AddConstraint(
            model_name='meterreadingmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('ingestionKey__isnull', False)), fields=('tenantId', 'ingestionKey'), name='uq_meter_reading_ingestion_key'),
        ),
        migrations.AddConstraint(
            model_name='meterreadingmodel',
            constraint=models.CheckConstraint(condition=models.Q(('captureMode__in', ('manual', 'sensor'))), name='ck_meter_reading_capture_mode'),
        ),
        migrations.AddConstraint(
            model_name='meterreadingmodel',
            constraint=models.CheckConstraint(condition=models.Q(('quality__in', ('good', 'suspect', 'estimated', 'bad'))), name='ck_meter_reading_quality'),
        ),
        migrations.AddConstraint(
            model_name='meterreadingmodel',
            constraint=models.CheckConstraint(condition=models.Q(('supersededByReadingId', models.F('id')), _negated=True), name='ck_meter_reading_no_self_supersede'),
        ),
        migrations.AddConstraint(
            model_name='meterreadingmodel',
            constraint=models.CheckConstraint(condition=models.Q(('correctsReadingId', models.F('id')), _negated=True), name='ck_meter_reading_no_self_correction'),
        ),
    ]
