# Generated by Django 6.1 on 2026-10-03 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_runningHourPlansBecomeMeterDriven'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSyncOperationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('clientRequestId', models.CharField(max_length=80)),
                ('kind', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(db_index=True, default='applied', max_length=12)),
                ('resultId', models.CharField(blank=True, default='', max_length=64)),
                ('resultPayload', models.JSONField(blank=True, default=dict)),
                ('errorCode', models.CharField(blank=True, default='', max_length=60)),
                ('errorMessage', models.CharField(blank=True, default='', max_length=500)),
                ('actorName', models.CharField(blank=True, default='', max_length=160)),
                ('capturedAt', models.DateTimeField(blank=True, null=True)),
                ('receivedAt', models.DateTimeField(db_index=True)),
                ('deviceLabel', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'db_table': 'OfflineSyncOperation',
                'ordering': ['-receivedAt'],
                'indexes': [models.Index(fields=['tenantId', 'kind', 'receivedAt'], name='ix_sync_tenant_kind_time')],
                'constraints': [models.UniqueConstraint(fields=('tenantId', 'clientRequestId'), name='uq_sync_operation_client_request'), models.CheckConstraint(condition=models.Q(('status__in', ('applied', 'failed', 'rejected'))), name='ck_sync_operation_status')],
            },
        ),
        migrations.CreateModel(
            name='WorkTimerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('workOrderId', models.UUIDField(db_index=True)),
                ('technicianName', models.CharField(max_length=160)),
                ('technicianUserId', models.UUIDField(blank=True, db_index=True, null=True)),
                ('startedAt', models.DateTimeField(db_index=True)),
                ('endedAt', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pausedSeconds', models.IntegerField(default=0)),
                ('hourlyRate', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('startNote', models.CharField(blank=True, default='', max_length=500)),
                ('endNote', models.CharField(blank=True, default='', max_length=500)),
                ('labourEntryId', models.UUIDField(blank=True, db_index=True, null=True)),
                ('capturedOffline', models.BooleanField(default=False)),
                ('startedVia', models.CharField(default='online', max_length=12)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'WorkTimer',
                'ordering': ['-startedAt'],
                'indexes': [models.Index(fields=['tenantId', 'workOrderId', 'startedAt'], name='ix_wt_tenant_order_start'), models.Index(fields=['tenantId', 'technicianName', 'startedAt'], name='ix_wt_tenant_tech_start')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('endedAt__isnull', True)), fields=('tenantId', 'workOrderId', 'technicianName'), name='uq_work_timer_one_running_per_tech'), models.CheckConstraint(condition=models.Q(('endedAt__isnull', True), ('endedAt__gte', models.F('startedAt')), _connector='OR'), name='ck_work_timer_end_after_start'), models.CheckConstraint(condition=models.Q(('pausedSeconds__gte', 0)), name='ck_work_timer_paused_nonnegative')],
            },
        ),
    ]
