# Generated by Django 6.1 on 2026-10-03 11:46

"""Widen the sync ledger's status check to admit the «conflict» verdict.

Separate from 0015 on purpose: anyone who already ran 0015 (the first
field-operations release) must be able to move forward without re-creating
the table.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0015_fieldOperations"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="offlinesyncoperationmodel",
            name="ck_sync_operation_status",
        ),
        migrations.AddConstraint(
            model_name="offlinesyncoperationmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("applied", "failed", "rejected", "conflict"))),
                name="ck_sync_operation_status",
            ),
        ),
    ]
