# Generated by Django 6.1 on 2026-10-04 08:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0016_syncConflictVerdict"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicemodel",
            name="assetLevel",
            field=models.CharField(db_index=True, default="mainEquipment", max_length=20),
        ),
        migrations.AddField(
            model_name="devicemodel",
            name="costCenterCode",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="devicemodel",
            name="costCenterName",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="devicemodel",
            name="retiredOn",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="devicemodel",
            name="retirementReason",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.CreateModel(
            name="AssetMovementModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("deviceId", models.UUIDField(db_index=True)),
                ("fromLocationId", models.UUIDField(blank=True, null=True)),
                ("fromLocationPath", models.CharField(blank=True, default="", max_length=800)),
                ("toLocationId", models.UUIDField(blank=True, null=True)),
                ("toLocationPath", models.CharField(blank=True, default="", max_length=800)),
                ("fromParentDeviceId", models.UUIDField(blank=True, null=True)),
                ("toParentDeviceId", models.UUIDField(blank=True, null=True)),
                ("movedOn", models.DateField(db_index=True)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("performedBy", models.CharField(blank=True, default="", max_length=160)),
                ("note", models.TextField(blank=True, default="")),
                ("createdAt", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "AssetMovement",
                "ordering": ["-movedOn", "-createdAt"],
                "indexes": [
                    models.Index(
                        fields=["tenantId", "deviceId", "-movedOn"],
                        name="AssetMoveme_tenantI_61a825_idx",
                    )
                ],
            },
        ),
    ]
