# Generated by Django 6.1 on 2026-10-04 09:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0017_assetHierarchy"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarHolidayModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("calendarId", models.UUIDField(db_index=True)),
                ("onDate", models.DateField(db_index=True)),
                ("name", models.CharField(max_length=200)),
                ("kind", models.CharField(default="official", max_length=16)),
                ("recursAnnually", models.BooleanField(default=False)),
                ("jalaliMonth", models.PositiveSmallIntegerField(default=0)),
                ("jalaliDay", models.PositiveSmallIntegerField(default=0)),
                ("createdAt", models.DateTimeField(db_index=True)),
                ("deletedAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "MaintenanceCalendarHoliday",
                "ordering": ["onDate"],
                "indexes": [
                    models.Index(
                        fields=["tenantId", "calendarId", "onDate"],
                        name="Maintenance_tenantI_afd9af_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deletedAt__isnull", True)),
                        fields=("tenantId", "calendarId", "onDate"),
                        name="uq_maintenance_holiday_calendar_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShiftAssignmentModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("shiftId", models.UUIDField(db_index=True)),
                ("personnelId", models.UUIDField(db_index=True)),
                ("fromDate", models.DateField(db_index=True)),
                ("toDate", models.DateField(blank=True, null=True)),
                ("createdAt", models.DateTimeField(db_index=True)),
                ("deletedAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "MaintenanceShiftAssignment",
                "ordering": ["-fromDate"],
                "indexes": [
                    models.Index(
                        fields=["tenantId", "shiftId", "fromDate"],
                        name="Maintenance_tenantI_8551f0_idx",
                    ),
                    models.Index(
                        fields=["tenantId", "personnelId"], name="Maintenance_tenantI_a7d342_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkCalendarModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=200)),
                ("locationId", models.UUIDField(blank=True, db_index=True, null=True)),
                ("timezone", models.CharField(default="Asia/Tehran", max_length=64)),
                ("weekendDays", models.CharField(default="4", max_length=32)),
                ("rollPolicy", models.CharField(default="forward", max_length=16)),
                ("isDefault", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, default="", max_length=400)),
                ("createdAt", models.DateTimeField(db_index=True)),
                ("updatedAt", models.DateTimeField(blank=True, null=True)),
                ("deletedAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "MaintenanceWorkCalendar",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deletedAt__isnull", True)),
                        fields=("tenantId", "code"),
                        name="uq_maintenance_calendar_tenant_code",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("deletedAt__isnull", True), ("locationId__isnull", False)
                        ),
                        fields=("tenantId", "locationId"),
                        name="uq_maintenance_calendar_tenant_location",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkShiftModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("calendarId", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=200)),
                ("kind", models.CharField(default="general", max_length=16)),
                ("startTime", models.TimeField()),
                ("endTime", models.TimeField()),
                ("weekdays", models.CharField(blank=True, default="", max_length=32)),
                ("headcount", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("createdAt", models.DateTimeField(db_index=True)),
                ("updatedAt", models.DateTimeField(blank=True, null=True)),
                ("deletedAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "MaintenanceWorkShift",
                "ordering": ["startTime"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deletedAt__isnull", True)),
                        fields=("tenantId", "calendarId", "code"),
                        name="uq_maintenance_shift_calendar_code",
                    )
                ],
            },
        ),
    ]
