# Generated by Django 6.1 on 2026-10-04 13:28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0019_backfillHolidayJalaliParts"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceRaterScoreModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("cycleId", models.UUIDField(db_index=True)),
                ("personnelId", models.UUIDField(db_index=True)),
                ("raterRole", models.CharField(db_index=True, max_length=32)),
                ("raterUserId", models.UUIDField(blank=True, null=True)),
                ("raterName", models.CharField(blank=True, default="", max_length=200)),
                ("score", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("note", models.CharField(blank=True, default="", max_length=600)),
                ("submittedAt", models.DateTimeField(db_index=True)),
                ("updatedAt", models.DateTimeField(blank=True, null=True)),
                ("deletedAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "MaintenancePerformanceRaterScore",
                "ordering": ["raterRole"],
                "indexes": [
                    models.Index(
                        fields=["tenantId", "cycleId", "personnelId"],
                        name="ix_perfscore_cycle_person",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deletedAt__isnull", True)),
                        fields=("tenantId", "cycleId", "personnelId", "raterRole"),
                        name="uq_maintenance_perfscore_cycle_person_role",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceResultModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("cycleId", models.UUIDField(db_index=True)),
                ("personnelId", models.UUIDField(db_index=True)),
                ("finalScore", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("humanScore", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                (
                    "systemScore",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("consensus", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("spread", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("raterCount", models.PositiveSmallIntegerField(default=0)),
                ("dampedCount", models.PositiveSmallIntegerField(default=0)),
                ("systemWeightPercent", models.PositiveSmallIntegerField(default=30)),
                ("breakdown", models.TextField(blank=True, default="")),
                ("computedAt", models.DateTimeField(db_index=True)),
                ("deletedAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "MaintenancePerformanceResult",
                "ordering": ["-finalScore"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deletedAt__isnull", True)),
                        fields=("tenantId", "cycleId", "personnelId"),
                        name="uq_maintenance_perfresult_cycle_person",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceReviewCycleModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenantId", models.UUIDField(db_index=True)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=200)),
                ("fromDate", models.DateField()),
                ("toDate", models.DateField()),
                ("status", models.CharField(db_index=True, default="draft", max_length=16)),
                ("systemWeightPercent", models.PositiveSmallIntegerField(default=30)),
                ("roleWeights", models.TextField(blank=True, default="")),
                ("note", models.CharField(blank=True, default="", max_length=400)),
                ("createdAt", models.DateTimeField(db_index=True)),
                ("updatedAt", models.DateTimeField(blank=True, null=True)),
                ("deletedAt", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "MaintenancePerformanceCycle",
                "ordering": ["-fromDate", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deletedAt__isnull", True)),
                        fields=("tenantId", "code"),
                        name="uq_maintenance_perfcycle_tenant_code",
                    )
                ],
            },
        ),
    ]
