# Generated by Django 6.1 on 2026-10-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_sparePartReorderPolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermodel',
            name='assignedToUserId',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='orgDepartmentId',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='workordermodel',
            name='requestedByUserId',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
