# Generated by Django 6.1 on 2026-09-06 13:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_phase12_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='actorId',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='cancelledAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='deliveredAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='expiresAt',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='failedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='payloadVersion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='scheduledAt',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='sentAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='status',
            field=models.CharField(db_index=True, default='CREATED', max_length=32),
        ),
        migrations.AddField(
            model_name='notificationrecipientdeliverymodel',
            name='failedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationrecipientdeliverymodel',
            name='providerMessageId',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='notificationrecipientdeliverymodel',
            name='sentAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NotificationAuditModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('eventType', models.CharField(db_index=True, max_length=64)),
                ('resourceType', models.CharField(max_length=48)),
                ('resourceId', models.CharField(blank=True, default='', max_length=120)),
                ('actorId', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurredAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificationAudit',
                'indexes': [models.Index(fields=['tenantId', 'occurredAt'], name='IX_NtfAudit_t_time')],
            },
        ),
        migrations.CreateModel(
            name='NotificationCleanupRunModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('requestedById', models.UUIDField(blank=True, null=True)),
                ('dryRun', models.BooleanField(default=True)),
                ('cutoff', models.DateTimeField()),
                ('counts', models.JSONField(default=dict)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificationCleanupRuns',
                'indexes': [models.Index(fields=['tenantId', 'createdAt'], name='IX_NtfClean_t_time')],
            },
        ),
        migrations.CreateModel(
            name='NotificationProviderConfigurationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('channel', models.CharField(max_length=16)),
                ('provider', models.CharField(max_length=48)),
                ('credentialRef', models.CharField(blank=True, default='', max_length=255)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('isActive', models.BooleanField(db_index=True, default=True)),
                ('createdById', models.UUIDField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notificationProviderConfigurations',
                'constraints': [models.UniqueConstraint(fields=('tenantId', 'channel', 'provider'), name='UQ_NtfProvider_t_channel_name')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPushSubscriptionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('userId', models.UUIDField(db_index=True)),
                ('endpointHash', models.CharField(max_length=64)),
                ('encryptedSubscription', models.TextField()),
                ('isActive', models.BooleanField(db_index=True, default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('expiresAt', models.DateTimeField(blank=True, null=True)),
                ('revokedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificationPushSubscriptions',
                'indexes': [models.Index(fields=['tenantId', 'userId', 'isActive'], name='IX_NtfPush_t_user')],
                'constraints': [models.UniqueConstraint(fields=('tenantId', 'userId', 'endpointHash'), name='UQ_NtfPush_t_user_endpoint')],
            },
        ),
        migrations.CreateModel(
            name='NotificationWebhookReceiptModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenantId', models.UUIDField(db_index=True)),
                ('provider', models.CharField(max_length=48)),
                ('providerEventId', models.CharField(max_length=120)),
                ('payloadHash', models.CharField(max_length=64)),
                ('outcome', models.CharField(max_length=16)),
                ('receivedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificationWebhookReceipts',
                'indexes': [models.Index(fields=['tenantId', 'receivedAt'], name='IX_NtfHook_t_received')],
                'constraints': [models.UniqueConstraint(fields=('tenantId', 'provider', 'providerEventId'), name='UQ_NtfHook_t_provider_event')],
            },
        ),
    ]
