import type { MaintenanceDevice, WorkOrder } from "../../shared/types/domain";

/** Offline demo devices — Persian labels, used only when demo mode is active. */
export const demoDevices: MaintenanceDevice[] = [
  {
    id: "dev-1",
    code: "PUMP-01",
    name: "پمپ خنک‌کننده اصلی",
    location: "سالن تولید A",
    status: "operational",
    department: "mechanical",
    pmIntervalDays: 30,
    lastPmDate: "2026-08-20",
    nextDueDate: "2026-09-19",
    pmDue: true,
    createdAt: "2026-07-01",
  },
  {
    id: "dev-2",
    code: "CNC-14",
    name: "دستگاه تراش CNC",
    location: "کارگاه ماشین‌کاری",
    status: "underMaintenance",
    department: "mechanical",
    pmIntervalDays: 45,
    lastPmDate: "2026-09-10",
    nextDueDate: "2026-10-25",
    pmDue: false,
    createdAt: "2026-06-15",
  },
  {
    id: "dev-3",
    code: "COMP-07",
    name: "کمپرسور هوا",
    location: "اتاق تأسیسات",
    status: "operational",
    department: "facilities",
    pmIntervalDays: 60,
    lastPmDate: "2026-09-01",
    nextDueDate: "2026-10-31",
    pmDue: false,
    createdAt: "2026-05-20",
  },
  {
    id: "dev-4",
    code: "GEN-02",
    name: "ژنراتور اضطراری",
    location: "محوطه بیرونی",
    status: "outOfService",
    department: "electrical",
    pmIntervalDays: 90,
    lastPmDate: "2026-04-01",
    nextDueDate: "2026-06-30",
    pmDue: true,
    createdAt: "2026-03-10",
  },
];

/** Offline demo work orders — Persian labels, used only when demo mode is active. */
export const demoWorkOrders: WorkOrder[] = [
  {
    id: "wo-1",
    deviceId: "dev-1",
    title: "صدای غیرعادی از یاتاقان پمپ",
    description: "هنگام کار صدای سایش شنیده می‌شود.",
    orderType: "corrective",
    priority: "high",
    status: "assigned",
    department: "mechanical",
    requestedByName: "علی رضایی",
    assignedToName: "رضا احمدی",
    resolutionNote: "",
    createdAt: "2026-09-18",
    closedAt: "",
  },
  {
    id: "wo-2",
    deviceId: "dev-2",
    title: "کالیبراسیون دوره‌ای محور Z",
    description: "طبق برنامه نگهداری پیشگیرانه.",
    orderType: "preventive",
    priority: "normal",
    status: "inProgress",
    department: "mechanical",
    requestedByName: "سیستم PM",
    assignedToName: "مریم کریمی",
    resolutionNote: "",
    createdAt: "2026-09-15",
    closedAt: "",
  },
  {
    id: "wo-3",
    deviceId: "dev-4",
    title: "تعویض باتری ژنراتور",
    description: "باتری فرسوده و غیرقابل شارژ است.",
    orderType: "corrective",
    priority: "critical",
    status: "submitted",
    department: "electrical",
    requestedByName: "حسین محمدی",
    assignedToName: "",
    resolutionNote: "",
    createdAt: "2026-09-20",
    closedAt: "",
  },
  {
    id: "wo-4",
    deviceId: "dev-3",
    title: "بازرسی فشار مخزن هوا",
    description: "بازرسی ماهانه ایمنی.",
    orderType: "inspection",
    priority: "low",
    status: "completed",
    department: "facilities",
    requestedByName: "سیستم PM",
    assignedToName: "رضا احمدی",
    resolutionNote: "فشار در محدوده مجاز بود.",
    createdAt: "2026-09-05",
    closedAt: "2026-09-06",
  },
];
