# Generated by Django 6.1 on 2026-08-30 06:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEventModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("occurredAt", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actorUserId", models.UUIDField(blank=True, null=True)),
                ("tenantId", models.UUIDField(blank=True, db_index=True, null=True)),
                ("action", models.CharField(max_length=40)),
                ("resourceType", models.CharField(max_length=80)),
                ("resourceId", models.CharField(blank=True, default="", max_length=64)),
                ("ipAddress", models.CharField(blank=True, default="", max_length=64)),
                ("userAgent", models.CharField(blank=True, default="", max_length=300)),
                ("beforeState", models.JSONField(blank=True, null=True)),
                ("afterState", models.JSONField(blank=True, null=True)),
                (
                    "correlationId",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                ("requestId", models.CharField(blank=True, default="", max_length=64)),
            ],
            options={
                "db_table": "AuditEvent",
                "ordering": ["-occurredAt"],
                "indexes": [
                    models.Index(fields=["tenantId", "occurredAt"], name="IX_AuditEvent_t_occ"),
                    models.Index(fields=["tenantId", "correlationId"], name="IX_AuditEvent_t_corr"),
                    models.Index(
                        fields=["tenantId", "actorUserId", "action"], name="IX_AuditEvent_t_act"
                    ),
                ],
            },
        ),
    ]
